// Code generated by dddgen. DO NOT EDIT.
package workspace

import (
	kratoshttp "github.com/go-kratos/kratos/v3/transport/http"
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
	"github.com/multica-ai/multica/server/internal/modules/workspace/internal/application"
	grpcadapter "github.com/multica-ai/multica/server/internal/modules/workspace/internal/interfaces/grpc"
	"github.com/multica-ai/multica/server/internal/modules/workspace/internal/interfaces/local"
	protoadapter "github.com/multica-ai/multica/server/internal/modules/workspace/internal/interfaces/proto"
	platformmodule "github.com/multica-ai/multica/server/internal/platform/module"
	stdgrpc "google.golang.org/grpc"
)

type ProjectExtension struct {
	local  contract.ProjectService
	server *protoadapter.ProjectServer
}

func NewProjectExtension() *ProjectExtension {
	client := local.NewProject(application.NewProjectService())
	return &ProjectExtension{local: client, server: protoadapter.NewProjectServer(client)}
}

func init()                                                 { RegisterExtension(func() platformmodule.Extension { return NewProjectExtension() }) }
func (e *ProjectExtension) RegisterHTTP(*kratoshttp.Server) {}
func (e *ProjectExtension) RegisterGRPC(registrar stdgrpc.ServiceRegistrar) {
	workspacev1.RegisterProjectServiceServer(registrar, e.server)
}
func (e *ProjectExtension) Local() contract.ProjectService { return e.local }
func (m *Module) ProjectLocal() contract.ProjectService {
	for _, extension := range m.extensions {
		if typed, ok := extension.(*ProjectExtension); ok {
			return typed.Local()
		}
	}
	panic("Project extension is not registered")
}
func NewProjectGRPCClient(connection stdgrpc.ClientConnInterface) contract.ProjectService {
	return grpcadapter.NewProject(workspacev1.NewProjectServiceClient(connection))
}
