// Code generated by dddgen. DO NOT EDIT.
package workspace

import (
	kratoshttp "github.com/go-kratos/kratos/v3/transport/http"
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
	"github.com/multica-ai/multica/server/internal/modules/workspace/internal/application"
	grpcadapter "github.com/multica-ai/multica/server/internal/modules/workspace/internal/interfaces/grpc"
	"github.com/multica-ai/multica/server/internal/modules/workspace/internal/interfaces/local"
	protoadapter "github.com/multica-ai/multica/server/internal/modules/workspace/internal/interfaces/proto"
	platformmodule "github.com/multica-ai/multica/server/internal/platform/module"
	stdgrpc "google.golang.org/grpc"
)

type RelationshipExtension struct {
	local  contract.RelationshipService
	server *protoadapter.RelationshipServer
}

func NewRelationshipExtension() *RelationshipExtension {
	client := local.NewRelationship(application.NewRelationshipService())
	return &RelationshipExtension{local: client, server: protoadapter.NewRelationshipServer(client)}
}

func init()                                                      { RegisterExtension(func() platformmodule.Extension { return NewRelationshipExtension() }) }
func (e *RelationshipExtension) RegisterHTTP(*kratoshttp.Server) {}
func (e *RelationshipExtension) RegisterGRPC(registrar stdgrpc.ServiceRegistrar) {
	workspacev1.RegisterRelationshipServiceServer(registrar, e.server)
}
func (e *RelationshipExtension) Local() contract.RelationshipService { return e.local }
func (m *Module) RelationshipLocal() contract.RelationshipService {
	for _, extension := range m.extensions {
		if typed, ok := extension.(*RelationshipExtension); ok {
			return typed.Local()
		}
	}
	panic("Relationship extension is not registered")
}
func NewRelationshipGRPCClient(connection stdgrpc.ClientConnInterface) contract.RelationshipService {
	return grpcadapter.NewRelationship(workspacev1.NewRelationshipServiceClient(connection))
}
