// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"github.com/multica-ai/multica/server/internal/modules/system/contract"
)

type SkillClient struct{ service contract.SkillService }

func NewSkill(service contract.SkillService) *SkillClient { return &SkillClient{service: service} }

var _ contract.SkillService = (*SkillClient)(nil)
