// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type IssueClient struct {
	client workspacev1.IssueServiceClient
}

func NewIssue(client workspacev1.IssueServiceClient) *IssueClient {
	return &IssueClient{client: client}
}

func (c *IssueClient) CreateIssue(ctx context.Context, request contract.CreateIssueRequest) (contract.CreateIssueResponse, error) {
	protoRequest := &workspacev1.CreateIssueRequest{}
	if err := encodeIssueContract(request, protoRequest); err != nil {
		return contract.CreateIssueResponse{}, err
	}
	response, err := c.client.CreateIssue(ctx, protoRequest)
	if err != nil {
		return contract.CreateIssueResponse{}, err
	}
	var result contract.CreateIssueResponse
	if err := decodeIssueProto(response, &result); err != nil {
		return contract.CreateIssueResponse{}, err
	}
	return result, nil
}

func (c *IssueClient) GetIssue(ctx context.Context, request contract.GetIssueRequest) (contract.GetIssueResponse, error) {
	protoRequest := &workspacev1.GetIssueRequest{}
	if err := encodeIssueContract(request, protoRequest); err != nil {
		return contract.GetIssueResponse{}, err
	}
	response, err := c.client.GetIssue(ctx, protoRequest)
	if err != nil {
		return contract.GetIssueResponse{}, err
	}
	var result contract.GetIssueResponse
	if err := decodeIssueProto(response, &result); err != nil {
		return contract.GetIssueResponse{}, err
	}
	return result, nil
}

func (c *IssueClient) ListIssues(ctx context.Context, request contract.ListIssuesRequest) (contract.ListIssuesResponse, error) {
	protoRequest := &workspacev1.ListIssuesRequest{}
	if err := encodeIssueContract(request, protoRequest); err != nil {
		return contract.ListIssuesResponse{}, err
	}
	response, err := c.client.ListIssues(ctx, protoRequest)
	if err != nil {
		return contract.ListIssuesResponse{}, err
	}
	var result contract.ListIssuesResponse
	if err := decodeIssueProto(response, &result); err != nil {
		return contract.ListIssuesResponse{}, err
	}
	return result, nil
}

func (c *IssueClient) UpdateIssue(ctx context.Context, request contract.UpdateIssueRequest) (contract.UpdateIssueResponse, error) {
	protoRequest := &workspacev1.UpdateIssueRequest{}
	if err := encodeIssueContract(request, protoRequest); err != nil {
		return contract.UpdateIssueResponse{}, err
	}
	response, err := c.client.UpdateIssue(ctx, protoRequest)
	if err != nil {
		return contract.UpdateIssueResponse{}, err
	}
	var result contract.UpdateIssueResponse
	if err := decodeIssueProto(response, &result); err != nil {
		return contract.UpdateIssueResponse{}, err
	}
	return result, nil
}

func (c *IssueClient) UpdateIssueStatus(ctx context.Context, request contract.UpdateIssueStatusRequest) (contract.UpdateIssueStatusResponse, error) {
	protoRequest := &workspacev1.UpdateIssueStatusRequest{}
	if err := encodeIssueContract(request, protoRequest); err != nil {
		return contract.UpdateIssueStatusResponse{}, err
	}
	response, err := c.client.UpdateIssueStatus(ctx, protoRequest)
	if err != nil {
		return contract.UpdateIssueStatusResponse{}, err
	}
	var result contract.UpdateIssueStatusResponse
	if err := decodeIssueProto(response, &result); err != nil {
		return contract.UpdateIssueStatusResponse{}, err
	}
	return result, nil
}

func decodeIssueProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeIssueContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.IssueService = (*IssueClient)(nil)
