// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type RequirementClient struct {
	client workspacev1.RequirementServiceClient
}

func NewRequirement(client workspacev1.RequirementServiceClient) *RequirementClient {
	return &RequirementClient{client: client}
}

func (c *RequirementClient) SaveRequirementVersion(ctx context.Context, request contract.SaveRequirementVersionRequest) (contract.SaveRequirementVersionResponse, error) {
	protoRequest := &workspacev1.SaveRequirementVersionRequest{}
	if err := encodeRequirementContract(request, protoRequest); err != nil {
		return contract.SaveRequirementVersionResponse{}, err
	}
	response, err := c.client.SaveRequirementVersion(ctx, protoRequest)
	if err != nil {
		return contract.SaveRequirementVersionResponse{}, err
	}
	var result contract.SaveRequirementVersionResponse
	if err := decodeRequirementProto(response, &result); err != nil {
		return contract.SaveRequirementVersionResponse{}, err
	}
	return result, nil
}

func (c *RequirementClient) GetRequirement(ctx context.Context, request contract.GetRequirementRequest) (contract.GetRequirementResponse, error) {
	protoRequest := &workspacev1.GetRequirementRequest{}
	if err := encodeRequirementContract(request, protoRequest); err != nil {
		return contract.GetRequirementResponse{}, err
	}
	response, err := c.client.GetRequirement(ctx, protoRequest)
	if err != nil {
		return contract.GetRequirementResponse{}, err
	}
	var result contract.GetRequirementResponse
	if err := decodeRequirementProto(response, &result); err != nil {
		return contract.GetRequirementResponse{}, err
	}
	return result, nil
}

func decodeRequirementProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeRequirementContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.RequirementService = (*RequirementClient)(nil)
