// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type SettingClient struct {
	client workspacev1.SettingServiceClient
}

func NewSetting(client workspacev1.SettingServiceClient) *SettingClient {
	return &SettingClient{client: client}
}

func (c *SettingClient) PutWorkspaceSetting(ctx context.Context, request contract.PutWorkspaceSettingRequest) (contract.PutWorkspaceSettingResponse, error) {
	protoRequest := &workspacev1.PutWorkspaceSettingRequest{}
	if err := encodeSettingContract(request, protoRequest); err != nil {
		return contract.PutWorkspaceSettingResponse{}, err
	}
	response, err := c.client.PutWorkspaceSetting(ctx, protoRequest)
	if err != nil {
		return contract.PutWorkspaceSettingResponse{}, err
	}
	var result contract.PutWorkspaceSettingResponse
	if err := decodeSettingProto(response, &result); err != nil {
		return contract.PutWorkspaceSettingResponse{}, err
	}
	return result, nil
}

func (c *SettingClient) PutWorkspaceSkillBinding(ctx context.Context, request contract.PutWorkspaceSkillBindingRequest) (contract.PutWorkspaceSkillBindingResponse, error) {
	protoRequest := &workspacev1.PutWorkspaceSkillBindingRequest{}
	if err := encodeSettingContract(request, protoRequest); err != nil {
		return contract.PutWorkspaceSkillBindingResponse{}, err
	}
	response, err := c.client.PutWorkspaceSkillBinding(ctx, protoRequest)
	if err != nil {
		return contract.PutWorkspaceSkillBindingResponse{}, err
	}
	var result contract.PutWorkspaceSkillBindingResponse
	if err := decodeSettingProto(response, &result); err != nil {
		return contract.PutWorkspaceSkillBindingResponse{}, err
	}
	return result, nil
}

func decodeSettingProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeSettingContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.SettingService = (*SettingClient)(nil)
