run:
  timeout: 10m
  tests: true

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
