// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/system/contract"
	systemv1 "github.com/hvritual/workspace/rpc/pb/system/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type SkillServer struct {
	systemv1.UnimplementedSkillServiceServer
	service contract.SkillService
}

func NewSkillServer(service contract.SkillService) *SkillServer {
	return &SkillServer{service: service}
}

func (s *SkillServer) PublishSkillVersion(ctx context.Context, request *systemv1.PublishSkillVersionRequest) (*systemv1.PublishSkillVersionResponse, error) {
	var input contract.PublishSkillVersionRequest
	if err := decodeSkillProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.PublishSkillVersion(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &systemv1.PublishSkillVersionResponse{}
	if err := encodeSkillContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *SkillServer) GetSkill(ctx context.Context, request *systemv1.GetSkillRequest) (*systemv1.GetSkillResponse, error) {
	var input contract.GetSkillRequest
	if err := decodeSkillProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.GetSkill(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &systemv1.GetSkillResponse{}
	if err := encodeSkillContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeSkillProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeSkillContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
