// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/auth/contract"
	authv1 "github.com/hvritual/workspace/rpc/pb/auth/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type MemberClient struct{ client authv1.MemberServiceClient }

func NewMember(client authv1.MemberServiceClient) *MemberClient { return &MemberClient{client: client} }

func (c *MemberClient) ProvisionWorkspaceOwner(ctx context.Context, request contract.ProvisionWorkspaceOwnerRequest) (contract.ProvisionWorkspaceOwnerResponse, error) {
	protoRequest := &authv1.ProvisionWorkspaceOwnerRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.ProvisionWorkspaceOwnerResponse{}, err
	}
	response, err := c.client.ProvisionWorkspaceOwner(ctx, protoRequest)
	if err != nil {
		return contract.ProvisionWorkspaceOwnerResponse{}, err
	}
	var result contract.ProvisionWorkspaceOwnerResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.ProvisionWorkspaceOwnerResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) ListMembers(ctx context.Context, request contract.ListMembersRequest) (contract.ListMembersResponse, error) {
	protoRequest := &authv1.ListMembersRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.ListMembersResponse{}, err
	}
	response, err := c.client.ListMembers(ctx, protoRequest)
	if err != nil {
		return contract.ListMembersResponse{}, err
	}
	var result contract.ListMembersResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.ListMembersResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) UpdateMemberRole(ctx context.Context, request contract.UpdateMemberRoleRequest) (contract.UpdateMemberRoleResponse, error) {
	protoRequest := &authv1.UpdateMemberRoleRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.UpdateMemberRoleResponse{}, err
	}
	response, err := c.client.UpdateMemberRole(ctx, protoRequest)
	if err != nil {
		return contract.UpdateMemberRoleResponse{}, err
	}
	var result contract.UpdateMemberRoleResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.UpdateMemberRoleResponse{}, err
	}
	return result, nil
}

func decodeMemberProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeMemberContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.MemberService = (*MemberClient)(nil)
