// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	systemv1 "github.com/multica-ai/multica/server/gen/go/system/v1"
	"github.com/multica-ai/multica/server/internal/modules/system/contract"
)

type AgentReleaseServer struct {
	systemv1.UnimplementedAgentReleaseServiceServer
	service contract.AgentReleaseService
}

func NewAgentReleaseServer(service contract.AgentReleaseService) *AgentReleaseServer {
	return &AgentReleaseServer{service: service}
}
