// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/auth/contract"
)

type MemberClient struct{ service contract.MemberService }

func NewMember(service contract.MemberService) *MemberClient { return &MemberClient{service: service} }

func (c *MemberClient) ProvisionWorkspaceOwner(ctx context.Context, request contract.ProvisionWorkspaceOwnerRequest) (contract.ProvisionWorkspaceOwnerResponse, error) {
	return c.service.ProvisionWorkspaceOwner(ctx, request)
}

func (c *MemberClient) ListMembers(ctx context.Context, request contract.ListMembersRequest) (contract.ListMembersResponse, error) {
	return c.service.ListMembers(ctx, request)
}

func (c *MemberClient) UpdateMemberRole(ctx context.Context, request contract.UpdateMemberRoleRequest) (contract.UpdateMemberRoleResponse, error) {
	return c.service.UpdateMemberRole(ctx, request)
}

var _ contract.MemberService = (*MemberClient)(nil)
