package workstation

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestLocalExecutorCreatesRevisionWorktreeAndSignedPatch(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("fake Codex shell fixture is POSIX-only")
	}
	requireGit(t)
	repository, baseCommit := createGitFixture(t)
	fakeCodex := writeExecutable(t, "fake-codex-success", `#!/bin/sh
printf '%s\n' '{"type":"thread.started","thread_id":"thread-local"}'
printf '%s\n' 'generated by fake codex' > generated.txt
printf '%s\n' '{"type":"turn.completed","usage":{"input_tokens":10,"output_tokens":5}}'
`)
	service, _ := newTestService(t, 2)
	key := testDeviceKey('l')
	registerTestRunner(t, service, "runner-local", key, []string{"alpha"}, []string{"codex", "go"})
	request := testEnqueueRequest("alpha", "local-success", "create generated.txt")
	request.ExecutionPack.RepositoryID = "fixture"
	request.ExecutionPack.BaseCommit = baseCommit
	request.ExecutionPack.AllowedPaths = []string{"generated.txt"}
	request.ExecutionPack.Verification = []CommandSpec{{
		Name: "generated file exists",
		Argv: []string{"/bin/sh", "-c", "test -f generated.txt"},
	}}
	task, err := service.Enqueue(request)
	if err != nil {
		t.Fatalf("Enqueue: %v", err)
	}
	claim := mustClaim(t, service, "runner-local", "alpha", "local-claim")
	executor, err := NewLocalExecutor(LocalExecConfig{
		RunnerID:               "runner-local",
		DeviceKeyPath:          filepath.Join(service.Config().Root, "credentials", "runner-local.key"),
		WorkRoot:               filepath.Join(t.TempDir(), "worktrees"),
		RepositoryPaths:        map[string]string{"fixture": repository},
		CodexCommand:           fakeCodex,
		TimeoutSeconds:         30,
		UnsafeHostVerification: true,
	})
	if err != nil {
		t.Fatalf("NewLocalExecutor: %v", err)
	}
	evidence, err := executor.ExecuteClaim(context.Background(), claim)
	if err != nil {
		t.Fatalf("ExecuteClaim: %v\nmetadata: %#v\nchecks: %#v", err, evidence.Metadata, evidence.Checks)
	}
	if evidence.Outcome != "completed" {
		t.Fatalf("outcome = %s", evidence.Outcome)
	}
	if err := VerifyEvidenceBundle(evidence, key); err != nil {
		t.Fatalf("VerifyEvidenceBundle: %v", err)
	}
	if evidence.DiffPatch == "" || !strings.Contains(evidence.DiffPatch, "generated by fake codex") {
		t.Fatalf("missing recoverable patch: %q", evidence.DiffPatch)
	}
	if evidence.DiffSHA256 != sha256Bytes([]byte(evidence.DiffPatch)) {
		t.Fatal("local diff digest mismatch")
	}
	if len(evidence.ChangedFiles) != 1 || evidence.ChangedFiles[0] != "generated.txt" {
		t.Fatalf("changed files = %#v", evidence.ChangedFiles)
	}
	if !strings.Contains(evidence.Metadata["worktree_relative"], "r1-a1") {
		t.Fatalf("worktree is not revision isolated: %s", evidence.Metadata["worktree_relative"])
	}
	if evidence.HeadCommit != baseCommit || evidence.CommitSHA != "" {
		t.Fatalf("executor committed changes: head=%s commit=%s", evidence.HeadCommit, evidence.CommitSHA)
	}
	if _, err := os.Stat(filepath.Join(repository, "generated.txt")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("base checkout was modified: %v", err)
	}
	completed, err := service.Complete(CompleteRequest{
		RunnerID: "runner-local", TaskID: task.ID, LeaseID: claim.Lease.ID,
		IdempotencyKey: "local-complete", Evidence: evidence,
	})
	if err != nil {
		t.Fatalf("Complete local evidence: %v", err)
	}
	if completed.Status != TaskCompleted {
		t.Fatalf("completed status = %s", completed.Status)
	}
	stored, err := service.GetEvidenceBundle(task.ID)
	if err != nil {
		t.Fatalf("GetEvidenceBundle: %v", err)
	}
	if stored.DiffPatch != evidence.DiffPatch {
		t.Fatal("stored local patch changed")
	}
}

func TestLocalExecutorReturnsSignedFailureForDeniedPath(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("fake Codex shell fixture is POSIX-only")
	}
	requireGit(t)
	repository, baseCommit := createGitFixture(t)
	fakeCodex := writeExecutable(t, "fake-codex-denied", `#!/bin/sh
printf '%s\n' '{"type":"thread.started","thread_id":"thread-denied"}'
printf '%s\n' 'must not change' > forbidden.txt
printf '%s\n' '{"type":"turn.completed","usage":{"input_tokens":10,"output_tokens":5}}'
`)
	service, _ := newTestService(t, 2)
	key := testDeviceKey('m')
	registerTestRunner(t, service, "runner-local", key, []string{"alpha"}, []string{"codex", "go"})
	request := testEnqueueRequest("alpha", "local-denied", "modify forbidden.txt")
	request.ExecutionPack.RepositoryID = "fixture"
	request.ExecutionPack.BaseCommit = baseCommit
	request.ExecutionPack.AllowedPaths = []string{"**"}
	request.ExecutionPack.DeniedPaths = []string{"forbidden.txt"}
	request.ExecutionPack.Verification = []CommandSpec{{
		Name: "fixture exists", Argv: []string{"/bin/sh", "-c", "test -f forbidden.txt"},
	}}
	task, err := service.Enqueue(request)
	if err != nil {
		t.Fatalf("Enqueue: %v", err)
	}
	claim := mustClaim(t, service, "runner-local", "alpha", "local-denied-claim")
	executor, err := NewLocalExecutor(LocalExecConfig{
		RunnerID:               "runner-local",
		DeviceKeyPath:          filepath.Join(service.Config().Root, "credentials", "runner-local.key"),
		WorkRoot:               filepath.Join(t.TempDir(), "worktrees"),
		RepositoryPaths:        map[string]string{"fixture": repository},
		CodexCommand:           fakeCodex,
		TimeoutSeconds:         30,
		UnsafeHostVerification: true,
	})
	if err != nil {
		t.Fatalf("NewLocalExecutor: %v", err)
	}
	evidence, executeErr := executor.ExecuteClaim(context.Background(), claim)
	if executeErr == nil {
		t.Fatal("denied path execution unexpectedly passed")
	}
	if evidence.Outcome != "failed" {
		t.Fatalf("failure outcome = %s", evidence.Outcome)
	}
	if err := VerifyEvidenceBundle(evidence, key); err != nil {
		t.Fatalf("signed failure did not verify: %v", err)
	}
	foundPolicyFailure := false
	for _, check := range evidence.Checks {
		if check.Name == "scope-policy" && !check.Passed &&
			strings.Contains(check.Details, "denied path changed") {
			foundPolicyFailure = true
		}
	}
	if !foundPolicyFailure {
		t.Fatalf("scope failure missing from evidence: %#v", evidence.Checks)
	}
	failed, err := service.Fail(FailRequest{
		RunnerID: "runner-local", TaskID: task.ID, LeaseID: claim.Lease.ID,
		IdempotencyKey: "local-fail", Error: executeErr.Error(), Evidence: &evidence,
	})
	if err != nil {
		t.Fatalf("Fail with signed evidence: %v", err)
	}
	if failed.Status != TaskFailed || failed.LastFailure == nil || failed.LastFailure.Evidence == nil {
		t.Fatalf("failed task = %#v", failed)
	}
}

func TestLocalExecutorEvidenceIncludesVerificationMutations(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("fake Codex shell fixture is POSIX-only")
	}
	requireGit(t)
	repository, baseCommit := createGitFixture(t)
	fakeCodex := writeExecutable(t, "fake-codex-verifier", `#!/bin/sh
printf '%s\n' '{"type":"thread.started","thread_id":"thread-verifier"}'
printf '%s\n' 'created by codex' > generated.txt
printf '%s\n' '{"type":"turn.completed","usage":{"input_tokens":10,"output_tokens":5}}'
`)
	service, _ := newTestService(t, 2)
	key := testDeviceKey('v')
	registerTestRunner(t, service, "runner-verifier", key, []string{"alpha"}, []string{"codex", "go"})
	request := testEnqueueRequest("alpha", "local-verifier", "create generated.txt")
	request.ExecutionPack.RepositoryID = "fixture"
	request.ExecutionPack.BaseCommit = baseCommit
	request.ExecutionPack.AllowedPaths = []string{"generated.txt"}
	request.ExecutionPack.Verification = []CommandSpec{{
		Name: "format generated file",
		Argv: []string{"/bin/sh", "-c", "printf '%s\\n' 'updated by verifier' > generated.txt"},
	}}
	if _, err := service.Enqueue(request); err != nil {
		t.Fatalf("Enqueue: %v", err)
	}
	claim := mustClaim(t, service, "runner-verifier", "alpha", "local-verifier-claim")
	executor, err := NewLocalExecutor(LocalExecConfig{
		RunnerID:               "runner-verifier",
		DeviceKeyPath:          filepath.Join(service.Config().Root, "credentials", "runner-verifier.key"),
		WorkRoot:               filepath.Join(t.TempDir(), "worktrees"),
		RepositoryPaths:        map[string]string{"fixture": repository},
		CodexCommand:           fakeCodex,
		TimeoutSeconds:         30,
		UnsafeHostVerification: true,
	})
	if err != nil {
		t.Fatalf("NewLocalExecutor: %v", err)
	}
	evidence, err := executor.ExecuteClaim(context.Background(), claim)
	if err != nil {
		t.Fatalf("ExecuteClaim: %v", err)
	}
	if !strings.Contains(evidence.DiffPatch, "updated by verifier") ||
		strings.Contains(evidence.DiffPatch, "created by codex") {
		t.Fatalf("signed patch does not reflect post-verification worktree: %q", evidence.DiffPatch)
	}
	if err := VerifyEvidenceBundle(evidence, key); err != nil {
		t.Fatalf("VerifyEvidenceBundle: %v", err)
	}
}

func TestLocalExecutorRejectsOverexposedDeviceKey(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("POSIX permission bits are not portable to Windows")
	}
	repository, _ := createGitFixture(t)
	keyPath := filepath.Join(t.TempDir(), "runner.key")
	if err := os.WriteFile(keyPath, testDeviceKey('p'), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := NewLocalExecutor(LocalExecConfig{
		RunnerID:        "runner-permissions",
		DeviceKeyPath:   keyPath,
		WorkRoot:        filepath.Join(t.TempDir(), "worktrees"),
		RepositoryPaths: map[string]string{"fixture": repository},
	})
	if err == nil || !strings.Contains(err.Error(), "group or others") {
		t.Fatalf("expected unsafe device key permissions to fail, got %v", err)
	}
}

func TestLocalExecutorRequiresVerificationIsolation(t *testing.T) {
	repository, _ := createGitFixture(t)
	keyPath := filepath.Join(t.TempDir(), "runner.key")
	if err := os.WriteFile(keyPath, testDeviceKey('s'), 0o600); err != nil {
		t.Fatal(err)
	}
	_, err := NewLocalExecutor(LocalExecConfig{
		RunnerID:        "runner-sandbox-required",
		DeviceKeyPath:   keyPath,
		WorkRoot:        filepath.Join(t.TempDir(), "worktrees"),
		RepositoryPaths: map[string]string{"fixture": repository},
	})
	if err == nil || !strings.Contains(err.Error(), "verification_sandbox is required") {
		t.Fatalf("expected fail-closed verification sandbox error, got %v", err)
	}
	wrapper := writeExecutable(t, "mutually-exclusive-wrapper", "#!/bin/sh\nexit 0\n")
	_, err = NewLocalExecutor(LocalExecConfig{
		RunnerID:               "runner-sandbox-required",
		DeviceKeyPath:          keyPath,
		WorkRoot:               filepath.Join(t.TempDir(), "worktrees"),
		RepositoryPaths:        map[string]string{"fixture": repository},
		VerificationSandbox:    []string{wrapper},
		UnsafeHostVerification: true,
	})
	if err == nil || !strings.Contains(err.Error(), "mutually exclusive") {
		t.Fatalf("expected mutually exclusive verification mode error, got %v", err)
	}
}

func TestSanitizedLocalEnvironmentProtectsControlPlaneSecrets(t *testing.T) {
	input := []string{
		"PATH=/usr/bin",
		"HOME=/home/alice",
		"GOCLAW_USER_TOKEN=user-secret",
		"GOCLAW_GATEWAY_TOKEN=gateway-secret",
		"GOCLAW_REVIEWER_TOKEN=test-only-reviewer",
		"GOCLAW_RUNNER_KEY_FILE=/run/secrets/runner.key",
		"GOCLAW_RUNNER_DEVICE_KEY=device-secret",
		"CODEX_ACCESS_TOKEN=test-only-codex-access",
		"CODEX_REFRESH_TOKEN=test-only-codex-refresh",
		"GOSKILLS_GATEWAY_WEBSOCKET_AUTH_TOKEN=legacy-secret",
		"GITHUB_TOKEN=github-secret",
		"NPM_TOKEN=npm-secret",
		"PUBLIC_VALUE=visible",
		"SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket",
		"DOCKER_HOST=unix:///run/docker.sock",
		"KUBECONFIG=/home/alice/.kube/config",
		"AWS_SHARED_CREDENTIALS_FILE=/home/alice/.aws/credentials",
		"LD_PRELOAD=/tmp/host-injection.so",
		"NODE_OPTIONS=--require=/tmp/host-injection.js",
	}
	got := sanitizedLocalEnvironment(
		input,
		[]string{
			"NPM_TOKEN",
			"GOCLAW_USER_TOKEN",
			"GOCLAW_REVIEWER_TOKEN",
			"CODEX_ACCESS_TOKEN",
			"CODEX_REFRESH_TOKEN",
			"PUBLIC_VALUE",
			"SSH_AUTH_SOCK",
			"LD_PRELOAD",
			"NODE_OPTIONS",
		},
	)
	joined := strings.Join(got, "\n")
	for _, expected := range []string{
		"PATH=/usr/bin",
		"NPM_TOKEN=npm-secret",
		"PUBLIC_VALUE=visible",
	} {
		if !strings.Contains(joined, expected) {
			t.Fatalf("expected %q in environment: %v", expected, got)
		}
	}
	for _, forbidden := range []string{
		"GOCLAW_USER_TOKEN",
		"GOCLAW_GATEWAY_TOKEN",
		"GOCLAW_REVIEWER_TOKEN",
		"GOCLAW_RUNNER_KEY_FILE",
		"GOCLAW_RUNNER_DEVICE_KEY",
		"CODEX_ACCESS_TOKEN",
		"CODEX_REFRESH_TOKEN",
		"GOSKILLS_GATEWAY_WEBSOCKET_AUTH_TOKEN",
		"GITHUB_TOKEN",
		"HOME=/home/alice",
		"SSH_AUTH_SOCK",
		"DOCKER_HOST",
		"KUBECONFIG",
		"AWS_SHARED_CREDENTIALS_FILE",
		"LD_PRELOAD",
		"NODE_OPTIONS",
	} {
		if strings.Contains(joined, forbidden) {
			t.Fatalf("protected %s leaked into environment: %v", forbidden, got)
		}
	}
}

func TestVerificationCommandUsesIsolatedEnvironment(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("POSIX shell fixture is not portable to Windows")
	}
	repository, _ := createGitFixture(t)
	keyPath := filepath.Join(t.TempDir(), "runner.key")
	if err := os.WriteFile(keyPath, testDeviceKey('i'), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("NPM_TOKEN", "must-not-reach-verifier")
	t.Setenv("CODEX_HOME", "/sensitive/codex-home")
	executor, err := NewLocalExecutor(LocalExecConfig{
		RunnerID:               "runner-isolated-verifier",
		DeviceKeyPath:          keyPath,
		WorkRoot:               filepath.Join(t.TempDir(), "worktrees"),
		RepositoryPaths:        map[string]string{"fixture": repository},
		AllowedEnvironment:     []string{"NPM_TOKEN"},
		UnsafeHostVerification: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	verificationHome := filepath.Join(t.TempDir(), "verification-home")
	result, err := executor.verificationCommand(
		context.Background(),
		repository,
		verificationHome,
		"/bin/sh",
		"-c",
		`printf '%s|%s|%s' "$HOME" "$CODEX_HOME" "$NPM_TOKEN"`,
	)
	if err != nil {
		t.Fatalf("verification command: %v: %s", err, result.Stderr)
	}
	expected := verificationHome + "|" +
		filepath.Join(verificationHome, ".codex") + "|"
	if result.Stdout != expected {
		t.Fatalf("verifier environment = %q, want %q", result.Stdout, expected)
	}
}

func TestCodexPermissionProfileDeniesCredentialHome(t *testing.T) {
	codexHome := filepath.Join(string(filepath.Separator), "sensitive", "codex-home")
	joined := strings.Join(codexPermissionProfileArgs(codexHome), "\n")
	for _, expected := range []string{
		`default_permissions="goclaw-runner"`,
		`permissions.goclaw-runner.extends=":workspace"`,
		`permissions.goclaw-runner.filesystem."` + codexHome + `"="deny"`,
		`permissions.goclaw-runner.network.enabled=false`,
	} {
		if !strings.Contains(joined, expected) {
			t.Fatalf("permission profile missing %q: %s", expected, joined)
		}
	}
	if strings.Contains(joined, "sandbox_mode") {
		t.Fatalf("legacy sandbox setting disables permission profiles: %s", joined)
	}
}

func TestCodexCredentialCanaryFailsClosedBeforeModelCall(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("POSIX shell fixture is not portable to Windows")
	}
	runtimeRoot := t.TempDir()
	modelMarker := filepath.Join(runtimeRoot, "model-called")
	fakeCodex := writeExecutable(t, "fake-codex-canary-failure", `#!/bin/sh
case " $* " in
  *" sandbox linux "*) exit 23 ;;
esac
printf '%s\n' called > "$MODEL_MARKER"
`)
	executor := &LocalExecutor{
		cfg: LocalExecConfig{
			CodexCommand:   fakeCodex,
			TimeoutSeconds: 30,
		},
		codexHome: filepath.Join(runtimeRoot, "real-codex-home"),
	}
	t.Setenv("MODEL_MARKER", modelMarker)
	result, err := executor.runCodex(
		context.Background(),
		runtimeRoot,
		runtimeRoot,
		ExecutionPack{},
	)
	if err == nil {
		t.Fatalf("credential canary unexpectedly passed: %#v", result)
	}
	if !strings.Contains(err.Error(), "credential isolation canary failed closed") {
		t.Fatalf("unexpected canary failure: %v", err)
	}
	if _, statErr := os.Stat(modelMarker); !errors.Is(statErr, os.ErrNotExist) {
		t.Fatalf("model command ran after canary failure: %v", statErr)
	}
}

func requireGit(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git is not installed")
	}
}

func createGitFixture(t *testing.T) (string, string) {
	t.Helper()
	repository := filepath.Join(t.TempDir(), "repo")
	if err := os.MkdirAll(repository, 0o755); err != nil {
		t.Fatalf("MkdirAll repo: %v", err)
	}
	runGitFixture(t, repository, "init")
	runGitFixture(t, repository, "config", "user.name", "GoClaw Test")
	runGitFixture(t, repository, "config", "user.email", "goclaw@example.invalid")
	if err := os.WriteFile(filepath.Join(repository, "README.md"), []byte("# fixture\n"), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	runGitFixture(t, repository, "add", "README.md")
	runGitFixture(t, repository, "commit", "-m", "initial")
	return repository, strings.TrimSpace(runGitFixture(t, repository, "rev-parse", "HEAD"))
}

func runGitFixture(t *testing.T, repository string, args ...string) string {
	t.Helper()
	command := exec.Command("git", append([]string{"-C", repository}, args...)...)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v: %s", args, err, output)
	}
	return string(output)
}

func writeExecutable(t *testing.T, name, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(content), 0o700); err != nil {
		t.Fatalf("write executable: %v", err)
	}
	return path
}
