// Code generated by dddgen. DO NOT EDIT.
package contract_test

import (
	"testing"

	kratoshttp "github.com/go-kratos/kratos/v3/transport/http"
	"github.com/multica-ai/multica/server/internal/modules/auth"
	"google.golang.org/grpc"
)

func TestAuthMemberRegistration(t *testing.T) {
	extension := auth.NewMemberExtension()
	extension.RegisterHTTP(kratoshttp.NewServer())
	extension.RegisterGRPC(grpc.NewServer())
}
