// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrIssueNotImplemented = errors.New("IssueService application method requires implementation")

type IssueService interface {
	UpdateIssueStatus(context.Context, Issue_UpdateIssueStatusRequest) (Issue_Issue, error)
}

type Issue_Int32Value = int32

type Issue_Issue struct {
	Id            string         `json:"id,omitempty"`
	WorkspaceId   string         `json:"workspaceId,omitempty"`
	Number        int32          `json:"number,omitempty"`
	Identifier    string         `json:"identifier,omitempty"`
	Title         string         `json:"title,omitempty"`
	Description   *string        `json:"description,omitempty"`
	Status        string         `json:"status,omitempty"`
	Priority      string         `json:"priority,omitempty"`
	AssigneeType  *string        `json:"assigneeType,omitempty"`
	AssigneeId    *string        `json:"assigneeId,omitempty"`
	CreatorType   string         `json:"creatorType,omitempty"`
	CreatorId     string         `json:"creatorId,omitempty"`
	ParentIssueId *string        `json:"parentIssueId,omitempty"`
	ProjectId     *string        `json:"projectId,omitempty"`
	Position      float64        `json:"position,omitempty"`
	Stage         *int32         `json:"stage,omitempty"`
	StartDate     *string        `json:"startDate,omitempty"`
	DueDate       *string        `json:"dueDate,omitempty"`
	CreatedAt     string         `json:"createdAt,omitempty"`
	UpdatedAt     string         `json:"updatedAt,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
	Properties    map[string]any `json:"properties,omitempty"`
}

type Issue_StringValue = string

type Issue_Struct = map[string]any

type Issue_UpdateIssueStatusRequest struct {
	Id     string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
}
