// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrKnowledgeNotImplemented = errors.New("KnowledgeService application method requires implementation")

type KnowledgeService interface {
}
