// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrProjectNotImplemented = errors.New("ProjectService application method requires implementation")

type ProjectService interface {
}
