// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrRequirementNotImplemented = errors.New("RequirementService application method requires implementation")

type RequirementService interface {
}
