// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrSettingNotImplemented = errors.New("SettingService application method requires implementation")

type SettingService interface {
}
