// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrTodoNotImplemented = errors.New("TodoService application method requires implementation")

type TodoService interface {
}
