// Code generated by dddgen. DO NOT EDIT.
package auth

import (
	kratoshttp "github.com/go-kratos/kratos/v3/transport/http"
	authv1 "github.com/multica-ai/multica/server/gen/go/auth/v1"
	"github.com/multica-ai/multica/server/internal/modules/auth/contract"
	"github.com/multica-ai/multica/server/internal/modules/auth/internal/application"
	grpcadapter "github.com/multica-ai/multica/server/internal/modules/auth/internal/interfaces/grpc"
	"github.com/multica-ai/multica/server/internal/modules/auth/internal/interfaces/local"
	protoadapter "github.com/multica-ai/multica/server/internal/modules/auth/internal/interfaces/proto"
	platformmodule "github.com/multica-ai/multica/server/internal/platform/module"
	stdgrpc "google.golang.org/grpc"
)

type AgentExtension struct {
	local  contract.AgentService
	server *protoadapter.AgentServer
}

func NewAgentExtension() *AgentExtension {
	client := local.NewAgent(application.NewAgentService())
	return &AgentExtension{local: client, server: protoadapter.NewAgentServer(client)}
}

func init()                                               { RegisterExtension(func() platformmodule.Extension { return NewAgentExtension() }) }
func (e *AgentExtension) RegisterHTTP(*kratoshttp.Server) {}
func (e *AgentExtension) RegisterGRPC(registrar stdgrpc.ServiceRegistrar) {
	authv1.RegisterAgentServiceServer(registrar, e.server)
}
func (e *AgentExtension) Local() contract.AgentService { return e.local }
func (m *Module) AgentLocal() contract.AgentService {
	for _, extension := range m.extensions {
		if typed, ok := extension.(*AgentExtension); ok {
			return typed.Local()
		}
	}
	panic("Agent extension is not registered")
}
func NewAgentGRPCClient(connection stdgrpc.ClientConnInterface) contract.AgentService {
	return grpcadapter.NewAgent(authv1.NewAgentServiceClient(connection))
}
