// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	authv1 "github.com/multica-ai/multica/server/gen/go/auth/v1"
	"github.com/multica-ai/multica/server/internal/modules/auth/contract"
)

type AgentServer struct {
	authv1.UnimplementedAgentServiceServer
	service contract.AgentService
}

func NewAgentServer(service contract.AgentService) *AgentServer {
	return &AgentServer{service: service}
}
