// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/space/contract"
	spacev1 "github.com/hvritual/workspace/rpc/pb/space/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type AssetClient struct{ client spacev1.AssetServiceClient }

func NewAsset(client spacev1.AssetServiceClient) *AssetClient { return &AssetClient{client: client} }

func (c *AssetClient) UploadAsset(ctx context.Context, request contract.UploadAssetRequest) (contract.UploadAssetResponse, error) {
	protoRequest := &spacev1.UploadAssetRequest{}
	if err := encodeAssetContract(request, protoRequest); err != nil {
		return contract.UploadAssetResponse{}, err
	}
	response, err := c.client.UploadAsset(ctx, protoRequest)
	if err != nil {
		return contract.UploadAssetResponse{}, err
	}
	var result contract.UploadAssetResponse
	if err := decodeAssetProto(response, &result); err != nil {
		return contract.UploadAssetResponse{}, err
	}
	return result, nil
}

func (c *AssetClient) CreateAssetVersion(ctx context.Context, request contract.CreateAssetVersionRequest) (contract.CreateAssetVersionResponse, error) {
	protoRequest := &spacev1.CreateAssetVersionRequest{}
	if err := encodeAssetContract(request, protoRequest); err != nil {
		return contract.CreateAssetVersionResponse{}, err
	}
	response, err := c.client.CreateAssetVersion(ctx, protoRequest)
	if err != nil {
		return contract.CreateAssetVersionResponse{}, err
	}
	var result contract.CreateAssetVersionResponse
	if err := decodeAssetProto(response, &result); err != nil {
		return contract.CreateAssetVersionResponse{}, err
	}
	return result, nil
}

func (c *AssetClient) GetAsset(ctx context.Context, request contract.GetAssetRequest) (contract.GetAssetResponse, error) {
	protoRequest := &spacev1.GetAssetRequest{}
	if err := encodeAssetContract(request, protoRequest); err != nil {
		return contract.GetAssetResponse{}, err
	}
	response, err := c.client.GetAsset(ctx, protoRequest)
	if err != nil {
		return contract.GetAssetResponse{}, err
	}
	var result contract.GetAssetResponse
	if err := decodeAssetProto(response, &result); err != nil {
		return contract.GetAssetResponse{}, err
	}
	return result, nil
}

func decodeAssetProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeAssetContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.AssetService = (*AssetClient)(nil)
