// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/space/contract"
)

type AssetClient struct{ service contract.AssetService }

func NewAsset(service contract.AssetService) *AssetClient { return &AssetClient{service: service} }

func (c *AssetClient) UploadAsset(ctx context.Context, request contract.UploadAssetRequest) (contract.UploadAssetResponse, error) {
	return c.service.UploadAsset(ctx, request)
}

func (c *AssetClient) CreateAssetVersion(ctx context.Context, request contract.CreateAssetVersionRequest) (contract.CreateAssetVersionResponse, error) {
	return c.service.CreateAssetVersion(ctx, request)
}

func (c *AssetClient) GetAsset(ctx context.Context, request contract.GetAssetRequest) (contract.GetAssetResponse, error) {
	return c.service.GetAsset(ctx, request)
}

var _ contract.AssetService = (*AssetClient)(nil)
