// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type IssueClient struct {
	client workspacev1.IssueServiceClient
}

func NewIssue(client workspacev1.IssueServiceClient) *IssueClient {
	return &IssueClient{client: client}
}

func (c *IssueClient) UpdateIssueStatus(ctx context.Context, request contract.Issue_UpdateIssueStatusRequest) (contract.Issue_Issue, error) {
	protoRequest := &workspacev1.UpdateIssueStatusRequest{}
	if err := encodeIssueContract(request, protoRequest); err != nil {
		return contract.Issue_Issue{}, err
	}
	response, err := c.client.UpdateIssueStatus(ctx, protoRequest)
	if err != nil {
		return contract.Issue_Issue{}, err
	}
	var result contract.Issue_Issue
	if err := decodeIssueProto(response, &result); err != nil {
		return contract.Issue_Issue{}, err
	}
	return result, nil
}

func decodeIssueProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeIssueContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.IssueService = (*IssueClient)(nil)
