// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type KnowledgeClient struct {
	client workspacev1.KnowledgeServiceClient
}

func NewKnowledge(client workspacev1.KnowledgeServiceClient) *KnowledgeClient {
	return &KnowledgeClient{client: client}
}

var _ contract.KnowledgeService = (*KnowledgeClient)(nil)
