// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type ProjectClient struct {
	client workspacev1.ProjectServiceClient
}

func NewProject(client workspacev1.ProjectServiceClient) *ProjectClient {
	return &ProjectClient{client: client}
}

var _ contract.ProjectService = (*ProjectClient)(nil)
