// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type RelationshipClient struct {
	client workspacev1.RelationshipServiceClient
}

func NewRelationship(client workspacev1.RelationshipServiceClient) *RelationshipClient {
	return &RelationshipClient{client: client}
}

var _ contract.RelationshipService = (*RelationshipClient)(nil)
