// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type RequirementClient struct {
	client workspacev1.RequirementServiceClient
}

func NewRequirement(client workspacev1.RequirementServiceClient) *RequirementClient {
	return &RequirementClient{client: client}
}

var _ contract.RequirementService = (*RequirementClient)(nil)
