// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type SettingClient struct {
	client workspacev1.SettingServiceClient
}

func NewSetting(client workspacev1.SettingServiceClient) *SettingClient {
	return &SettingClient{client: client}
}

var _ contract.SettingService = (*SettingClient)(nil)
