// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type TodoClient struct{ client workspacev1.TodoServiceClient }

func NewTodo(client workspacev1.TodoServiceClient) *TodoClient { return &TodoClient{client: client} }

var _ contract.TodoService = (*TodoClient)(nil)
