// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
)

type IssueClient struct{ service contract.IssueService }

func NewIssue(service contract.IssueService) *IssueClient { return &IssueClient{service: service} }

func (c *IssueClient) CreateIssue(ctx context.Context, request contract.CreateIssueRequest) (contract.CreateIssueResponse, error) {
	return c.service.CreateIssue(ctx, request)
}

func (c *IssueClient) GetIssue(ctx context.Context, request contract.GetIssueRequest) (contract.GetIssueResponse, error) {
	return c.service.GetIssue(ctx, request)
}

func (c *IssueClient) ListIssues(ctx context.Context, request contract.ListIssuesRequest) (contract.ListIssuesResponse, error) {
	return c.service.ListIssues(ctx, request)
}

func (c *IssueClient) UpdateIssue(ctx context.Context, request contract.UpdateIssueRequest) (contract.UpdateIssueResponse, error) {
	return c.service.UpdateIssue(ctx, request)
}

func (c *IssueClient) UpdateIssueStatus(ctx context.Context, request contract.UpdateIssueStatusRequest) (contract.UpdateIssueStatusResponse, error) {
	return c.service.UpdateIssueStatus(ctx, request)
}

var _ contract.IssueService = (*IssueClient)(nil)
