// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
)

type KnowledgeClient struct{ service contract.KnowledgeService }

func NewKnowledge(service contract.KnowledgeService) *KnowledgeClient {
	return &KnowledgeClient{service: service}
}

func (c *KnowledgeClient) CreateKnowledge(ctx context.Context, request contract.CreateKnowledgeRequest) (contract.CreateKnowledgeResponse, error) {
	return c.service.CreateKnowledge(ctx, request)
}

func (c *KnowledgeClient) GetKnowledge(ctx context.Context, request contract.GetKnowledgeRequest) (contract.GetKnowledgeResponse, error) {
	return c.service.GetKnowledge(ctx, request)
}

var _ contract.KnowledgeService = (*KnowledgeClient)(nil)
