// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
)

type ProjectClient struct{ service contract.ProjectService }

func NewProject(service contract.ProjectService) *ProjectClient {
	return &ProjectClient{service: service}
}

func (c *ProjectClient) CreateProject(ctx context.Context, request contract.CreateProjectRequest) (contract.CreateProjectResponse, error) {
	return c.service.CreateProject(ctx, request)
}

func (c *ProjectClient) GetProject(ctx context.Context, request contract.GetProjectRequest) (contract.GetProjectResponse, error) {
	return c.service.GetProject(ctx, request)
}

func (c *ProjectClient) ListProjects(ctx context.Context, request contract.ListProjectsRequest) (contract.ListProjectsResponse, error) {
	return c.service.ListProjects(ctx, request)
}

func (c *ProjectClient) SearchProjects(ctx context.Context, request contract.SearchProjectsRequest) (contract.SearchProjectsResponse, error) {
	return c.service.SearchProjects(ctx, request)
}

func (c *ProjectClient) UpdateProject(ctx context.Context, request contract.UpdateProjectRequest) (contract.UpdateProjectResponse, error) {
	return c.service.UpdateProject(ctx, request)
}

func (c *ProjectClient) DeleteProject(ctx context.Context, request contract.DeleteProjectRequest) (contract.DeleteProjectResponse, error) {
	return c.service.DeleteProject(ctx, request)
}

var _ contract.ProjectService = (*ProjectClient)(nil)
