// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
)

type RelationshipClient struct{ service contract.RelationshipService }

func NewRelationship(service contract.RelationshipService) *RelationshipClient {
	return &RelationshipClient{service: service}
}

func (c *RelationshipClient) PutProjectActorRelation(ctx context.Context, request contract.PutProjectActorRelationRequest) (contract.PutProjectActorRelationResponse, error) {
	return c.service.PutProjectActorRelation(ctx, request)
}

func (c *RelationshipClient) ListProjectActorRelations(ctx context.Context, request contract.ListProjectActorRelationsRequest) (contract.ListProjectActorRelationsResponse, error) {
	return c.service.ListProjectActorRelations(ctx, request)
}

func (c *RelationshipClient) DeleteProjectActorRelation(ctx context.Context, request contract.DeleteProjectActorRelationRequest) (contract.DeleteProjectActorRelationResponse, error) {
	return c.service.DeleteProjectActorRelation(ctx, request)
}

var _ contract.RelationshipService = (*RelationshipClient)(nil)
