// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
)

type RequirementClient struct{ service contract.RequirementService }

func NewRequirement(service contract.RequirementService) *RequirementClient {
	return &RequirementClient{service: service}
}

func (c *RequirementClient) SaveRequirementVersion(ctx context.Context, request contract.SaveRequirementVersionRequest) (contract.SaveRequirementVersionResponse, error) {
	return c.service.SaveRequirementVersion(ctx, request)
}

func (c *RequirementClient) GetRequirement(ctx context.Context, request contract.GetRequirementRequest) (contract.GetRequirementResponse, error) {
	return c.service.GetRequirement(ctx, request)
}

var _ contract.RequirementService = (*RequirementClient)(nil)
