// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
)

type SettingClient struct{ service contract.SettingService }

func NewSetting(service contract.SettingService) *SettingClient {
	return &SettingClient{service: service}
}

func (c *SettingClient) PutWorkspaceSetting(ctx context.Context, request contract.PutWorkspaceSettingRequest) (contract.PutWorkspaceSettingResponse, error) {
	return c.service.PutWorkspaceSetting(ctx, request)
}

func (c *SettingClient) PutWorkspaceSkillBinding(ctx context.Context, request contract.PutWorkspaceSkillBindingRequest) (contract.PutWorkspaceSkillBindingResponse, error) {
	return c.service.PutWorkspaceSkillBinding(ctx, request)
}

var _ contract.SettingService = (*SettingClient)(nil)
