// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: workspace/v1/issue.proto

package workspacev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IssueService_CreateIssue_FullMethodName       = "/workspace.v1.IssueService/CreateIssue"
	IssueService_GetIssue_FullMethodName          = "/workspace.v1.IssueService/GetIssue"
	IssueService_ListIssues_FullMethodName        = "/workspace.v1.IssueService/ListIssues"
	IssueService_UpdateIssue_FullMethodName       = "/workspace.v1.IssueService/UpdateIssue"
	IssueService_UpdateIssueStatus_FullMethodName = "/workspace.v1.IssueService/UpdateIssueStatus"
)

// IssueServiceClient is the client API for IssueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IssueService owns workspace-scoped Issue workflow and business associations.
// Project and Asset references are stored as IDs; their identities and content
// lifecycles remain owned by ProjectService and space.v1.AssetService.
type IssueServiceClient interface {
	CreateIssue(ctx context.Context, in *CreateIssueRequest, opts ...grpc.CallOption) (*CreateIssueResponse, error)
	GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error)
	ListIssues(ctx context.Context, in *ListIssuesRequest, opts ...grpc.CallOption) (*ListIssuesResponse, error)
	UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error)
	UpdateIssueStatus(ctx context.Context, in *UpdateIssueStatusRequest, opts ...grpc.CallOption) (*UpdateIssueStatusResponse, error)
}

type issueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssueServiceClient(cc grpc.ClientConnInterface) IssueServiceClient {
	return &issueServiceClient{cc}
}

func (c *issueServiceClient) CreateIssue(ctx context.Context, in *CreateIssueRequest, opts ...grpc.CallOption) (*CreateIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIssueResponse)
	err := c.cc.Invoke(ctx, IssueService_CreateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueServiceClient) GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIssueResponse)
	err := c.cc.Invoke(ctx, IssueService_GetIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueServiceClient) ListIssues(ctx context.Context, in *ListIssuesRequest, opts ...grpc.CallOption) (*ListIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssuesResponse)
	err := c.cc.Invoke(ctx, IssueService_ListIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueServiceClient) UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIssueResponse)
	err := c.cc.Invoke(ctx, IssueService_UpdateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueServiceClient) UpdateIssueStatus(ctx context.Context, in *UpdateIssueStatusRequest, opts ...grpc.CallOption) (*UpdateIssueStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIssueStatusResponse)
	err := c.cc.Invoke(ctx, IssueService_UpdateIssueStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssueServiceServer is the server API for IssueService service.
// All implementations must embed UnimplementedIssueServiceServer
// for forward compatibility.
//
// IssueService owns workspace-scoped Issue workflow and business associations.
// Project and Asset references are stored as IDs; their identities and content
// lifecycles remain owned by ProjectService and space.v1.AssetService.
type IssueServiceServer interface {
	CreateIssue(context.Context, *CreateIssueRequest) (*CreateIssueResponse, error)
	GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error)
	ListIssues(context.Context, *ListIssuesRequest) (*ListIssuesResponse, error)
	UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error)
	UpdateIssueStatus(context.Context, *UpdateIssueStatusRequest) (*UpdateIssueStatusResponse, error)
	mustEmbedUnimplementedIssueServiceServer()
}

// UnimplementedIssueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssueServiceServer struct{}

func (UnimplementedIssueServiceServer) CreateIssue(context.Context, *CreateIssueRequest) (*CreateIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIssue not implemented")
}
func (UnimplementedIssueServiceServer) GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIssue not implemented")
}
func (UnimplementedIssueServiceServer) ListIssues(context.Context, *ListIssuesRequest) (*ListIssuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIssues not implemented")
}
func (UnimplementedIssueServiceServer) UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIssue not implemented")
}
func (UnimplementedIssueServiceServer) UpdateIssueStatus(context.Context, *UpdateIssueStatusRequest) (*UpdateIssueStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIssueStatus not implemented")
}
func (UnimplementedIssueServiceServer) mustEmbedUnimplementedIssueServiceServer() {}
func (UnimplementedIssueServiceServer) testEmbeddedByValue()                      {}

// UnsafeIssueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssueServiceServer will
// result in compilation errors.
type UnsafeIssueServiceServer interface {
	mustEmbedUnimplementedIssueServiceServer()
}

func RegisterIssueServiceServer(s grpc.ServiceRegistrar, srv IssueServiceServer) {
	// If the following call pancis, it indicates UnimplementedIssueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IssueService_ServiceDesc, srv)
}

func _IssueService_CreateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).CreateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_CreateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).CreateIssue(ctx, req.(*CreateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueService_GetIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).GetIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_GetIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).GetIssue(ctx, req.(*GetIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueService_ListIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).ListIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_ListIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).ListIssues(ctx, req.(*ListIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueService_UpdateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).UpdateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_UpdateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).UpdateIssue(ctx, req.(*UpdateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueService_UpdateIssueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueServiceServer).UpdateIssueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueService_UpdateIssueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueServiceServer).UpdateIssueStatus(ctx, req.(*UpdateIssueStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IssueService_ServiceDesc is the grpc.ServiceDesc for IssueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.v1.IssueService",
	HandlerType: (*IssueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIssue",
			Handler:    _IssueService_CreateIssue_Handler,
		},
		{
			MethodName: "GetIssue",
			Handler:    _IssueService_GetIssue_Handler,
		},
		{
			MethodName: "ListIssues",
			Handler:    _IssueService_ListIssues_Handler,
		},
		{
			MethodName: "UpdateIssue",
			Handler:    _IssueService_UpdateIssue_Handler,
		},
		{
			MethodName: "UpdateIssueStatus",
			Handler:    _IssueService_UpdateIssueStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace/v1/issue.proto",
}

const (
	IssueMetadataService_GetIssueMetadata_FullMethodName       = "/workspace.v1.IssueMetadataService/GetIssueMetadata"
	IssueMetadataService_PutIssueMetadataKey_FullMethodName    = "/workspace.v1.IssueMetadataService/PutIssueMetadataKey"
	IssueMetadataService_DeleteIssueMetadataKey_FullMethodName = "/workspace.v1.IssueMetadataService/DeleteIssueMetadataKey"
)

// IssueMetadataServiceClient is the client API for IssueMetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IssueMetadataServiceClient interface {
	GetIssueMetadata(ctx context.Context, in *GetIssueMetadataRequest, opts ...grpc.CallOption) (*GetIssueMetadataResponse, error)
	PutIssueMetadataKey(ctx context.Context, in *PutIssueMetadataKeyRequest, opts ...grpc.CallOption) (*PutIssueMetadataKeyResponse, error)
	DeleteIssueMetadataKey(ctx context.Context, in *DeleteIssueMetadataKeyRequest, opts ...grpc.CallOption) (*DeleteIssueMetadataKeyResponse, error)
}

type issueMetadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssueMetadataServiceClient(cc grpc.ClientConnInterface) IssueMetadataServiceClient {
	return &issueMetadataServiceClient{cc}
}

func (c *issueMetadataServiceClient) GetIssueMetadata(ctx context.Context, in *GetIssueMetadataRequest, opts ...grpc.CallOption) (*GetIssueMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIssueMetadataResponse)
	err := c.cc.Invoke(ctx, IssueMetadataService_GetIssueMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueMetadataServiceClient) PutIssueMetadataKey(ctx context.Context, in *PutIssueMetadataKeyRequest, opts ...grpc.CallOption) (*PutIssueMetadataKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutIssueMetadataKeyResponse)
	err := c.cc.Invoke(ctx, IssueMetadataService_PutIssueMetadataKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueMetadataServiceClient) DeleteIssueMetadataKey(ctx context.Context, in *DeleteIssueMetadataKeyRequest, opts ...grpc.CallOption) (*DeleteIssueMetadataKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIssueMetadataKeyResponse)
	err := c.cc.Invoke(ctx, IssueMetadataService_DeleteIssueMetadataKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssueMetadataServiceServer is the server API for IssueMetadataService service.
// All implementations must embed UnimplementedIssueMetadataServiceServer
// for forward compatibility.
type IssueMetadataServiceServer interface {
	GetIssueMetadata(context.Context, *GetIssueMetadataRequest) (*GetIssueMetadataResponse, error)
	PutIssueMetadataKey(context.Context, *PutIssueMetadataKeyRequest) (*PutIssueMetadataKeyResponse, error)
	DeleteIssueMetadataKey(context.Context, *DeleteIssueMetadataKeyRequest) (*DeleteIssueMetadataKeyResponse, error)
	mustEmbedUnimplementedIssueMetadataServiceServer()
}

// UnimplementedIssueMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssueMetadataServiceServer struct{}

func (UnimplementedIssueMetadataServiceServer) GetIssueMetadata(context.Context, *GetIssueMetadataRequest) (*GetIssueMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIssueMetadata not implemented")
}
func (UnimplementedIssueMetadataServiceServer) PutIssueMetadataKey(context.Context, *PutIssueMetadataKeyRequest) (*PutIssueMetadataKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutIssueMetadataKey not implemented")
}
func (UnimplementedIssueMetadataServiceServer) DeleteIssueMetadataKey(context.Context, *DeleteIssueMetadataKeyRequest) (*DeleteIssueMetadataKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIssueMetadataKey not implemented")
}
func (UnimplementedIssueMetadataServiceServer) mustEmbedUnimplementedIssueMetadataServiceServer() {}
func (UnimplementedIssueMetadataServiceServer) testEmbeddedByValue()                              {}

// UnsafeIssueMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssueMetadataServiceServer will
// result in compilation errors.
type UnsafeIssueMetadataServiceServer interface {
	mustEmbedUnimplementedIssueMetadataServiceServer()
}

func RegisterIssueMetadataServiceServer(s grpc.ServiceRegistrar, srv IssueMetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedIssueMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IssueMetadataService_ServiceDesc, srv)
}

func _IssueMetadataService_GetIssueMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueMetadataServiceServer).GetIssueMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueMetadataService_GetIssueMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueMetadataServiceServer).GetIssueMetadata(ctx, req.(*GetIssueMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueMetadataService_PutIssueMetadataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutIssueMetadataKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueMetadataServiceServer).PutIssueMetadataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueMetadataService_PutIssueMetadataKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueMetadataServiceServer).PutIssueMetadataKey(ctx, req.(*PutIssueMetadataKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueMetadataService_DeleteIssueMetadataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIssueMetadataKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueMetadataServiceServer).DeleteIssueMetadataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueMetadataService_DeleteIssueMetadataKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueMetadataServiceServer).DeleteIssueMetadataKey(ctx, req.(*DeleteIssueMetadataKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IssueMetadataService_ServiceDesc is the grpc.ServiceDesc for IssueMetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssueMetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.v1.IssueMetadataService",
	HandlerType: (*IssueMetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIssueMetadata",
			Handler:    _IssueMetadataService_GetIssueMetadata_Handler,
		},
		{
			MethodName: "PutIssueMetadataKey",
			Handler:    _IssueMetadataService_PutIssueMetadataKey_Handler,
		},
		{
			MethodName: "DeleteIssueMetadataKey",
			Handler:    _IssueMetadataService_DeleteIssueMetadataKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace/v1/issue.proto",
}
