// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/v1/issue.proto

package workspacev1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueAssetIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueAssetIDs) Reset() {
	*x = IssueAssetIDs{}
	mi := &file_workspace_v1_issue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueAssetIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAssetIDs) ProtoMessage() {}

func (x *IssueAssetIDs) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAssetIDs.ProtoReflect.Descriptor instead.
func (*IssueAssetIDs) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{0}
}

func (x *IssueAssetIDs) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Issue struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Number      int32                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Identifier  string                 `protobuf:"bytes,4,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Title       string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// status and priority remain lowercase strings for JSON compatibility.
	Status       string  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Priority     string  `protobuf:"bytes,8,opt,name=priority,proto3" json:"priority,omitempty"`
	AssigneeType *string `protobuf:"bytes,9,opt,name=assignee_type,json=assigneeType,proto3,oneof" json:"assignee_type,omitempty"`
	// Member and Agent assignee identities are owned by auth.v1.
	AssigneeId    *string          `protobuf:"bytes,10,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	CreatorType   string           `protobuf:"bytes,11,opt,name=creator_type,json=creatorType,proto3" json:"creator_type,omitempty"`
	CreatorId     string           `protobuf:"bytes,12,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentIssueId *string          `protobuf:"bytes,13,opt,name=parent_issue_id,json=parentIssueId,proto3,oneof" json:"parent_issue_id,omitempty"`
	ProjectId     *string          `protobuf:"bytes,14,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	Position      float64          `protobuf:"fixed64,15,opt,name=position,proto3" json:"position,omitempty"`
	Stage         *int32           `protobuf:"varint,16,opt,name=stage,proto3,oneof" json:"stage,omitempty"`
	StartDate     *string          `protobuf:"bytes,17,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	DueDate       *string          `protobuf:"bytes,18,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	CreatedAt     string           `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string           `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      *structpb.Struct `protobuf:"bytes,21,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Properties    *structpb.Struct `protobuf:"bytes,22,opt,name=properties,proto3" json:"properties,omitempty"`
	// Each value is a stable space.v1 Asset ID; Issue owns the association.
	AssetIds      []string `protobuf:"bytes,23,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_workspace_v1_issue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{1}
}

func (x *Issue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Issue) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Issue) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Issue) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Issue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Issue) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Issue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Issue) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Issue) GetAssigneeType() string {
	if x != nil && x.AssigneeType != nil {
		return *x.AssigneeType
	}
	return ""
}

func (x *Issue) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *Issue) GetCreatorType() string {
	if x != nil {
		return x.CreatorType
	}
	return ""
}

func (x *Issue) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Issue) GetParentIssueId() string {
	if x != nil && x.ParentIssueId != nil {
		return *x.ParentIssueId
	}
	return ""
}

func (x *Issue) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *Issue) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Issue) GetStage() int32 {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return 0
}

func (x *Issue) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *Issue) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

func (x *Issue) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Issue) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Issue) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Issue) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Issue) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type CreateIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	AssigneeType  *string                `protobuf:"bytes,6,opt,name=assignee_type,json=assigneeType,proto3,oneof" json:"assignee_type,omitempty"`
	AssigneeId    *string                `protobuf:"bytes,7,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	ParentIssueId *string                `protobuf:"bytes,8,opt,name=parent_issue_id,json=parentIssueId,proto3,oneof" json:"parent_issue_id,omitempty"`
	ProjectId     *string                `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	Position      float64                `protobuf:"fixed64,10,opt,name=position,proto3" json:"position,omitempty"`
	Stage         *int32                 `protobuf:"varint,11,opt,name=stage,proto3,oneof" json:"stage,omitempty"`
	StartDate     *string                `protobuf:"bytes,12,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	DueDate       *string                `protobuf:"bytes,13,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	AssetIds      []string               `protobuf:"bytes,14,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueRequest) Reset() {
	*x = CreateIssueRequest{}
	mi := &file_workspace_v1_issue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueRequest) ProtoMessage() {}

func (x *CreateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueRequest.ProtoReflect.Descriptor instead.
func (*CreateIssueRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIssueRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateIssueRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIssueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateIssueRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateIssueRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateIssueRequest) GetAssigneeType() string {
	if x != nil && x.AssigneeType != nil {
		return *x.AssigneeType
	}
	return ""
}

func (x *CreateIssueRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *CreateIssueRequest) GetParentIssueId() string {
	if x != nil && x.ParentIssueId != nil {
		return *x.ParentIssueId
	}
	return ""
}

func (x *CreateIssueRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *CreateIssueRequest) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateIssueRequest) GetStage() int32 {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return 0
}

func (x *CreateIssueRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *CreateIssueRequest) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

func (x *CreateIssueRequest) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type CreateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIssueResponse) Reset() {
	*x = CreateIssueResponse{}
	mi := &file_workspace_v1_issue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIssueResponse) ProtoMessage() {}

func (x *CreateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIssueResponse.ProtoReflect.Descriptor instead.
func (*CreateIssueResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{3}
}

func (x *CreateIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type GetIssueRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// issue_id accepts either an Issue UUID or workspace-scoped identifier.
	IssueId       string `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueRequest) Reset() {
	*x = GetIssueRequest{}
	mi := &file_workspace_v1_issue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueRequest) ProtoMessage() {}

func (x *GetIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueRequest.ProtoReflect.Descriptor instead.
func (*GetIssueRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{4}
}

func (x *GetIssueRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type GetIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueResponse) Reset() {
	*x = GetIssueResponse{}
	mi := &file_workspace_v1_issue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueResponse) ProtoMessage() {}

func (x *GetIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueResponse.ProtoReflect.Descriptor instead.
func (*GetIssueResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{5}
}

func (x *GetIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type ListIssuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	ParentIssueId *string                `protobuf:"bytes,3,opt,name=parent_issue_id,json=parentIssueId,proto3,oneof" json:"parent_issue_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	AssigneeType  *string                `protobuf:"bytes,6,opt,name=assignee_type,json=assigneeType,proto3,oneof" json:"assignee_type,omitempty"`
	AssigneeId    *string                `protobuf:"bytes,7,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	CreatorType   *string                `protobuf:"bytes,8,opt,name=creator_type,json=creatorType,proto3,oneof" json:"creator_type,omitempty"`
	CreatorId     *string                `protobuf:"bytes,9,opt,name=creator_id,json=creatorId,proto3,oneof" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesRequest) Reset() {
	*x = ListIssuesRequest{}
	mi := &file_workspace_v1_issue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesRequest) ProtoMessage() {}

func (x *ListIssuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesRequest.ProtoReflect.Descriptor instead.
func (*ListIssuesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{6}
}

func (x *ListIssuesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListIssuesRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *ListIssuesRequest) GetParentIssueId() string {
	if x != nil && x.ParentIssueId != nil {
		return *x.ParentIssueId
	}
	return ""
}

func (x *ListIssuesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListIssuesRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *ListIssuesRequest) GetAssigneeType() string {
	if x != nil && x.AssigneeType != nil {
		return *x.AssigneeType
	}
	return ""
}

func (x *ListIssuesRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *ListIssuesRequest) GetCreatorType() string {
	if x != nil && x.CreatorType != nil {
		return *x.CreatorType
	}
	return ""
}

func (x *ListIssuesRequest) GetCreatorId() string {
	if x != nil && x.CreatorId != nil {
		return *x.CreatorId
	}
	return ""
}

type ListIssuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuesResponse) Reset() {
	*x = ListIssuesResponse{}
	mi := &file_workspace_v1_issue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuesResponse) ProtoMessage() {}

func (x *ListIssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuesResponse.ProtoReflect.Descriptor instead.
func (*ListIssuesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{7}
}

func (x *ListIssuesResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ListIssuesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateIssueRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// issue_id accepts either an Issue UUID or workspace-scoped identifier.
	IssueId       string   `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Title         *string  `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string  `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *string  `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Priority      *string  `protobuf:"bytes,6,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	AssigneeType  *string  `protobuf:"bytes,7,opt,name=assignee_type,json=assigneeType,proto3,oneof" json:"assignee_type,omitempty"`
	AssigneeId    *string  `protobuf:"bytes,8,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	ParentIssueId *string  `protobuf:"bytes,9,opt,name=parent_issue_id,json=parentIssueId,proto3,oneof" json:"parent_issue_id,omitempty"`
	ProjectId     *string  `protobuf:"bytes,10,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	Position      *float64 `protobuf:"fixed64,11,opt,name=position,proto3,oneof" json:"position,omitempty"`
	// Zero clears an existing stage; positive stages start at one.
	Stage     *int32  `protobuf:"varint,12,opt,name=stage,proto3,oneof" json:"stage,omitempty"`
	StartDate *string `protobuf:"bytes,13,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	DueDate   *string `protobuf:"bytes,14,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	// Message presence distinguishes omission from clearing all associations.
	AssetIds      *IssueAssetIDs `protobuf:"bytes,15,opt,name=asset_ids,json=assetIds,proto3,oneof" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueRequest) Reset() {
	*x = UpdateIssueRequest{}
	mi := &file_workspace_v1_issue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueRequest) ProtoMessage() {}

func (x *UpdateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateIssueRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateIssueRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateIssueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateIssueRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateIssueRequest) GetPriority() string {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return ""
}

func (x *UpdateIssueRequest) GetAssigneeType() string {
	if x != nil && x.AssigneeType != nil {
		return *x.AssigneeType
	}
	return ""
}

func (x *UpdateIssueRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *UpdateIssueRequest) GetParentIssueId() string {
	if x != nil && x.ParentIssueId != nil {
		return *x.ParentIssueId
	}
	return ""
}

func (x *UpdateIssueRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *UpdateIssueRequest) GetPosition() float64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *UpdateIssueRequest) GetStage() int32 {
	if x != nil && x.Stage != nil {
		return *x.Stage
	}
	return 0
}

func (x *UpdateIssueRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *UpdateIssueRequest) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

func (x *UpdateIssueRequest) GetAssetIds() *IssueAssetIDs {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type UpdateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueResponse) Reset() {
	*x = UpdateIssueResponse{}
	mi := &file_workspace_v1_issue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueResponse) ProtoMessage() {}

func (x *UpdateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

type UpdateIssueStatusRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// issue_id accepts either an Issue UUID or workspace-scoped identifier.
	IssueId       string `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueStatusRequest) Reset() {
	*x = UpdateIssueStatusRequest{}
	mi := &file_workspace_v1_issue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueStatusRequest) ProtoMessage() {}

func (x *UpdateIssueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueStatusRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateIssueStatusRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateIssueStatusRequest) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *UpdateIssueStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateIssueStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueStatusResponse) Reset() {
	*x = UpdateIssueStatusResponse{}
	mi := &file_workspace_v1_issue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueStatusResponse) ProtoMessage() {}

func (x *UpdateIssueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_issue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueStatusResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_issue_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateIssueStatusResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

var File_workspace_v1_issue_proto protoreflect.FileDescriptor

const file_workspace_v1_issue_proto_rawDesc = "" +
	"\n" +
	"\x18workspace/v1/issue.proto\x12\fworkspace.v1\x1a\x1bannotations/v1/access.proto\x1a\x1cgoogle/protobuf/struct.proto\"'\n" +
	"\rIssueAssetIDs\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x85\a\n" +
	"\x05Issue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x05R\x06number\x12\x1e\n" +
	"\n" +
	"identifier\x18\x04 \x01(\tR\n" +
	"identifier\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\b \x01(\tR\bpriority\x12(\n" +
	"\rassignee_type\x18\t \x01(\tH\x01R\fassigneeType\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\n" +
	" \x01(\tH\x02R\n" +
	"assigneeId\x88\x01\x01\x12!\n" +
	"\fcreator_type\x18\v \x01(\tR\vcreatorType\x12\x1d\n" +
	"\n" +
	"creator_id\x18\f \x01(\tR\tcreatorId\x12+\n" +
	"\x0fparent_issue_id\x18\r \x01(\tH\x03R\rparentIssueId\x88\x01\x01\x12\"\n" +
	"\n" +
	"project_id\x18\x0e \x01(\tH\x04R\tprojectId\x88\x01\x01\x12\x1a\n" +
	"\bposition\x18\x0f \x01(\x01R\bposition\x12\x19\n" +
	"\x05stage\x18\x10 \x01(\x05H\x05R\x05stage\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\x11 \x01(\tH\x06R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\x12 \x01(\tH\aR\adueDate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\tR\tupdatedAt\x123\n" +
	"\bmetadata\x18\x15 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x127\n" +
	"\n" +
	"properties\x18\x16 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12\x1b\n" +
	"\tasset_ids\x18\x17 \x03(\tR\bassetIdsB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_assignee_typeB\x0e\n" +
	"\f_assignee_idB\x12\n" +
	"\x10_parent_issue_idB\r\n" +
	"\v_project_idB\b\n" +
	"\x06_stageB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_due_date\"\xdc\x04\n" +
	"\x12CreateIssueRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12(\n" +
	"\rassignee_type\x18\x06 \x01(\tH\x01R\fassigneeType\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\a \x01(\tH\x02R\n" +
	"assigneeId\x88\x01\x01\x12+\n" +
	"\x0fparent_issue_id\x18\b \x01(\tH\x03R\rparentIssueId\x88\x01\x01\x12\"\n" +
	"\n" +
	"project_id\x18\t \x01(\tH\x04R\tprojectId\x88\x01\x01\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\x01R\bposition\x12\x19\n" +
	"\x05stage\x18\v \x01(\x05H\x05R\x05stage\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\f \x01(\tH\x06R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\r \x01(\tH\aR\adueDate\x88\x01\x01\x12\x1b\n" +
	"\tasset_ids\x18\x0e \x03(\tR\bassetIdsB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_assignee_typeB\x0e\n" +
	"\f_assignee_idB\x12\n" +
	"\x10_parent_issue_idB\r\n" +
	"\v_project_idB\b\n" +
	"\x06_stageB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_due_date\"@\n" +
	"\x13CreateIssueResponse\x12)\n" +
	"\x05issue\x18\x01 \x01(\v2\x13.workspace.v1.IssueR\x05issue\"O\n" +
	"\x0fGetIssueRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"=\n" +
	"\x10GetIssueResponse\x12)\n" +
	"\x05issue\x18\x01 \x01(\v2\x13.workspace.v1.IssueR\x05issue\"\xbc\x03\n" +
	"\x11ListIssuesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12+\n" +
	"\x0fparent_issue_id\x18\x03 \x01(\tH\x01R\rparentIssueId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12(\n" +
	"\rassignee_type\x18\x06 \x01(\tH\x02R\fassigneeType\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\a \x01(\tH\x03R\n" +
	"assigneeId\x88\x01\x01\x12&\n" +
	"\fcreator_type\x18\b \x01(\tH\x04R\vcreatorType\x88\x01\x01\x12\"\n" +
	"\n" +
	"creator_id\x18\t \x01(\tH\x05R\tcreatorId\x88\x01\x01B\r\n" +
	"\v_project_idB\x12\n" +
	"\x10_parent_issue_idB\x10\n" +
	"\x0e_assignee_typeB\x0e\n" +
	"\f_assignee_idB\x0f\n" +
	"\r_creator_typeB\r\n" +
	"\v_creator_id\"W\n" +
	"\x12ListIssuesResponse\x12+\n" +
	"\x06issues\x18\x01 \x03(\v2\x13.workspace.v1.IssueR\x06issues\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xea\x05\n" +
	"\x12UpdateIssueRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x02R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x06 \x01(\tH\x03R\bpriority\x88\x01\x01\x12(\n" +
	"\rassignee_type\x18\a \x01(\tH\x04R\fassigneeType\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\b \x01(\tH\x05R\n" +
	"assigneeId\x88\x01\x01\x12+\n" +
	"\x0fparent_issue_id\x18\t \x01(\tH\x06R\rparentIssueId\x88\x01\x01\x12\"\n" +
	"\n" +
	"project_id\x18\n" +
	" \x01(\tH\aR\tprojectId\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\v \x01(\x01H\bR\bposition\x88\x01\x01\x12\x19\n" +
	"\x05stage\x18\f \x01(\x05H\tR\x05stage\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\r \x01(\tH\n" +
	"R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\x0e \x01(\tH\vR\adueDate\x88\x01\x01\x12=\n" +
	"\tasset_ids\x18\x0f \x01(\v2\x1b.workspace.v1.IssueAssetIDsH\fR\bassetIds\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_statusB\v\n" +
	"\t_priorityB\x10\n" +
	"\x0e_assignee_typeB\x0e\n" +
	"\f_assignee_idB\x12\n" +
	"\x10_parent_issue_idB\r\n" +
	"\v_project_idB\v\n" +
	"\t_positionB\b\n" +
	"\x06_stageB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_due_dateB\f\n" +
	"\n" +
	"_asset_ids\"@\n" +
	"\x13UpdateIssueResponse\x12)\n" +
	"\x05issue\x18\x01 \x01(\v2\x13.workspace.v1.IssueR\x05issue\"p\n" +
	"\x18UpdateIssueStatusRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"F\n" +
	"\x19UpdateIssueStatusResponse\x12)\n" +
	"\x05issue\x18\x01 \x01(\v2\x13.workspace.v1.IssueR\x05issue2\xc3\x06\n" +
	"\fIssueService\x12\x99\x01\n" +
	"\vCreateIssue\x12 .workspace.v1.CreateIssueRequest\x1a!.workspace.v1.CreateIssueResponse\"E\xd2\xf3\x18A\n" +
	"\x16workspace.issue.create\x12\fCreate issue\x1a\x0fworkspace.issue\"\x06create@\x01\x12\x85\x01\n" +
	"\bGetIssue\x12\x1d.workspace.v1.GetIssueRequest\x1a\x1e.workspace.v1.GetIssueResponse\":\xd2\xf3\x186\n" +
	"\x13workspace.issue.get\x12\tGet issue\x1a\x0fworkspace.issue\"\x03get\x12\x8f\x01\n" +
	"\n" +
	"ListIssues\x12\x1f.workspace.v1.ListIssuesRequest\x1a .workspace.v1.ListIssuesResponse\">\xd2\xf3\x18:\n" +
	"\x14workspace.issue.list\x12\vList issues\x1a\x0fworkspace.issue\"\x04list\x12\x99\x01\n" +
	"\vUpdateIssue\x12 .workspace.v1.UpdateIssueRequest\x1a!.workspace.v1.UpdateIssueResponse\"E\xd2\xf3\x18A\n" +
	"\x16workspace.issue.update\x12\fUpdate issue\x1a\x0fworkspace.issue\"\x06update@\x01\x12\xc0\x01\n" +
	"\x11UpdateIssueStatus\x12&.workspace.v1.UpdateIssueStatusRequest\x1a'.workspace.v1.UpdateIssueStatusResponse\"Z\xd2\xf3\x18V\n" +
	"\x1dworkspace.issue.update_status\x12\x13Update issue status\x1a\x0fworkspace.issue\"\rupdate_status@\x01\x1a\x1e\xca\xf3\x18\x1a\n" +
	"\tworkspace\x12\tWorkspace\x1a\x02v1B?Z=github.com/hvritual/workspace/rpc/pb/workspace/v1;workspacev1b\x06proto3"

var (
	file_workspace_v1_issue_proto_rawDescOnce sync.Once
	file_workspace_v1_issue_proto_rawDescData []byte
)

func file_workspace_v1_issue_proto_rawDescGZIP() []byte {
	file_workspace_v1_issue_proto_rawDescOnce.Do(func() {
		file_workspace_v1_issue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_issue_proto_rawDesc), len(file_workspace_v1_issue_proto_rawDesc)))
	})
	return file_workspace_v1_issue_proto_rawDescData
}

var file_workspace_v1_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_workspace_v1_issue_proto_goTypes = []any{
	(*IssueAssetIDs)(nil),             // 0: workspace.v1.IssueAssetIDs
	(*Issue)(nil),                     // 1: workspace.v1.Issue
	(*CreateIssueRequest)(nil),        // 2: workspace.v1.CreateIssueRequest
	(*CreateIssueResponse)(nil),       // 3: workspace.v1.CreateIssueResponse
	(*GetIssueRequest)(nil),           // 4: workspace.v1.GetIssueRequest
	(*GetIssueResponse)(nil),          // 5: workspace.v1.GetIssueResponse
	(*ListIssuesRequest)(nil),         // 6: workspace.v1.ListIssuesRequest
	(*ListIssuesResponse)(nil),        // 7: workspace.v1.ListIssuesResponse
	(*UpdateIssueRequest)(nil),        // 8: workspace.v1.UpdateIssueRequest
	(*UpdateIssueResponse)(nil),       // 9: workspace.v1.UpdateIssueResponse
	(*UpdateIssueStatusRequest)(nil),  // 10: workspace.v1.UpdateIssueStatusRequest
	(*UpdateIssueStatusResponse)(nil), // 11: workspace.v1.UpdateIssueStatusResponse
	(*structpb.Struct)(nil),           // 12: google.protobuf.Struct
}
var file_workspace_v1_issue_proto_depIdxs = []int32{
	12, // 0: workspace.v1.Issue.metadata:type_name -> google.protobuf.Struct
	12, // 1: workspace.v1.Issue.properties:type_name -> google.protobuf.Struct
	1,  // 2: workspace.v1.CreateIssueResponse.issue:type_name -> workspace.v1.Issue
	1,  // 3: workspace.v1.GetIssueResponse.issue:type_name -> workspace.v1.Issue
	1,  // 4: workspace.v1.ListIssuesResponse.issues:type_name -> workspace.v1.Issue
	0,  // 5: workspace.v1.UpdateIssueRequest.asset_ids:type_name -> workspace.v1.IssueAssetIDs
	1,  // 6: workspace.v1.UpdateIssueResponse.issue:type_name -> workspace.v1.Issue
	1,  // 7: workspace.v1.UpdateIssueStatusResponse.issue:type_name -> workspace.v1.Issue
	2,  // 8: workspace.v1.IssueService.CreateIssue:input_type -> workspace.v1.CreateIssueRequest
	4,  // 9: workspace.v1.IssueService.GetIssue:input_type -> workspace.v1.GetIssueRequest
	6,  // 10: workspace.v1.IssueService.ListIssues:input_type -> workspace.v1.ListIssuesRequest
	8,  // 11: workspace.v1.IssueService.UpdateIssue:input_type -> workspace.v1.UpdateIssueRequest
	10, // 12: workspace.v1.IssueService.UpdateIssueStatus:input_type -> workspace.v1.UpdateIssueStatusRequest
	3,  // 13: workspace.v1.IssueService.CreateIssue:output_type -> workspace.v1.CreateIssueResponse
	5,  // 14: workspace.v1.IssueService.GetIssue:output_type -> workspace.v1.GetIssueResponse
	7,  // 15: workspace.v1.IssueService.ListIssues:output_type -> workspace.v1.ListIssuesResponse
	9,  // 16: workspace.v1.IssueService.UpdateIssue:output_type -> workspace.v1.UpdateIssueResponse
	11, // 17: workspace.v1.IssueService.UpdateIssueStatus:output_type -> workspace.v1.UpdateIssueStatusResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_workspace_v1_issue_proto_init() }
func file_workspace_v1_issue_proto_init() {
	if File_workspace_v1_issue_proto != nil {
		return
	}
	file_workspace_v1_issue_proto_msgTypes[1].OneofWrappers = []any{}
	file_workspace_v1_issue_proto_msgTypes[2].OneofWrappers = []any{}
	file_workspace_v1_issue_proto_msgTypes[6].OneofWrappers = []any{}
	file_workspace_v1_issue_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_issue_proto_rawDesc), len(file_workspace_v1_issue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_issue_proto_goTypes,
		DependencyIndexes: file_workspace_v1_issue_proto_depIdxs,
		MessageInfos:      file_workspace_v1_issue_proto_msgTypes,
	}.Build()
	File_workspace_v1_issue_proto = out.File
	file_workspace_v1_issue_proto_goTypes = nil
	file_workspace_v1_issue_proto_depIdxs = nil
}
