// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/v1/knowledge.proto

package workspacev1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Knowledge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AssetIds      []string               `protobuf:"bytes,6,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Knowledge) Reset() {
	*x = Knowledge{}
	mi := &file_workspace_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Knowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Knowledge) ProtoMessage() {}

func (x *Knowledge) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Knowledge.ProtoReflect.Descriptor instead.
func (*Knowledge) Descriptor() ([]byte, []int) {
	return file_workspace_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *Knowledge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Knowledge) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Knowledge) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Knowledge) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Knowledge) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Knowledge) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

func (x *Knowledge) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Knowledge) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	AssetIds      []string               `protobuf:"bytes,4,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeRequest) Reset() {
	*x = CreateKnowledgeRequest{}
	mi := &file_workspace_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeRequest) ProtoMessage() {}

func (x *CreateKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKnowledgeRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateKnowledgeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateKnowledgeRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateKnowledgeRequest) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type CreateKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Knowledge     *Knowledge             `protobuf:"bytes,1,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeResponse) Reset() {
	*x = CreateKnowledgeResponse{}
	mi := &file_workspace_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeResponse) ProtoMessage() {}

func (x *CreateKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKnowledgeResponse) GetKnowledge() *Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

type GetKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	KnowledgeId   string                 `protobuf:"bytes,2,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeRequest) Reset() {
	*x = GetKnowledgeRequest{}
	mi := &file_workspace_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeRequest) ProtoMessage() {}

func (x *GetKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *GetKnowledgeRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetKnowledgeRequest) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

type GetKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Knowledge     *Knowledge             `protobuf:"bytes,1,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeResponse) Reset() {
	*x = GetKnowledgeResponse{}
	mi := &file_workspace_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeResponse) ProtoMessage() {}

func (x *GetKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *GetKnowledgeResponse) GetKnowledge() *Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

var File_workspace_v1_knowledge_proto protoreflect.FileDescriptor

const file_workspace_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1cworkspace/v1/knowledge.proto\x12\fworkspace.v1\x1a\x1bannotations/v1/access.proto\"\xe1\x01\n" +
	"\tKnowledge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tasset_ids\x18\x06 \x03(\tR\bassetIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x88\x01\n" +
	"\x16CreateKnowledgeRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1b\n" +
	"\tasset_ids\x18\x04 \x03(\tR\bassetIds\"P\n" +
	"\x17CreateKnowledgeResponse\x125\n" +
	"\tknowledge\x18\x01 \x01(\v2\x17.workspace.v1.KnowledgeR\tknowledge\"[\n" +
	"\x13GetKnowledgeRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12!\n" +
	"\fknowledge_id\x18\x02 \x01(\tR\vknowledgeId\"M\n" +
	"\x14GetKnowledgeResponse\x125\n" +
	"\tknowledge\x18\x01 \x01(\v2\x17.workspace.v1.KnowledgeR\tknowledge2\x86\x03\n" +
	"\x10KnowledgeService\x12\xb1\x01\n" +
	"\x0fCreateKnowledge\x12$.workspace.v1.CreateKnowledgeRequest\x1a%.workspace.v1.CreateKnowledgeResponse\"Q\xd2\xf3\x18M\n" +
	"\x1aworkspace.knowledge.create\x12\x10Create knowledge\x1a\x13workspace.knowledge\"\x06create@\x01\x12\x9d\x01\n" +
	"\fGetKnowledge\x12!.workspace.v1.GetKnowledgeRequest\x1a\".workspace.v1.GetKnowledgeResponse\"F\xd2\xf3\x18B\n" +
	"\x17workspace.knowledge.get\x12\rGet knowledge\x1a\x13workspace.knowledge\"\x03get\x1a\x1e\xca\xf3\x18\x1a\n" +
	"\tworkspace\x12\tWorkspace\x1a\x02v1B?Z=github.com/hvritual/workspace/rpc/pb/workspace/v1;workspacev1b\x06proto3"

var (
	file_workspace_v1_knowledge_proto_rawDescOnce sync.Once
	file_workspace_v1_knowledge_proto_rawDescData []byte
)

func file_workspace_v1_knowledge_proto_rawDescGZIP() []byte {
	file_workspace_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_workspace_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_knowledge_proto_rawDesc), len(file_workspace_v1_knowledge_proto_rawDesc)))
	})
	return file_workspace_v1_knowledge_proto_rawDescData
}

var file_workspace_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_workspace_v1_knowledge_proto_goTypes = []any{
	(*Knowledge)(nil),               // 0: workspace.v1.Knowledge
	(*CreateKnowledgeRequest)(nil),  // 1: workspace.v1.CreateKnowledgeRequest
	(*CreateKnowledgeResponse)(nil), // 2: workspace.v1.CreateKnowledgeResponse
	(*GetKnowledgeRequest)(nil),     // 3: workspace.v1.GetKnowledgeRequest
	(*GetKnowledgeResponse)(nil),    // 4: workspace.v1.GetKnowledgeResponse
}
var file_workspace_v1_knowledge_proto_depIdxs = []int32{
	0, // 0: workspace.v1.CreateKnowledgeResponse.knowledge:type_name -> workspace.v1.Knowledge
	0, // 1: workspace.v1.GetKnowledgeResponse.knowledge:type_name -> workspace.v1.Knowledge
	1, // 2: workspace.v1.KnowledgeService.CreateKnowledge:input_type -> workspace.v1.CreateKnowledgeRequest
	3, // 3: workspace.v1.KnowledgeService.GetKnowledge:input_type -> workspace.v1.GetKnowledgeRequest
	2, // 4: workspace.v1.KnowledgeService.CreateKnowledge:output_type -> workspace.v1.CreateKnowledgeResponse
	4, // 5: workspace.v1.KnowledgeService.GetKnowledge:output_type -> workspace.v1.GetKnowledgeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workspace_v1_knowledge_proto_init() }
func file_workspace_v1_knowledge_proto_init() {
	if File_workspace_v1_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_knowledge_proto_rawDesc), len(file_workspace_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_workspace_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_workspace_v1_knowledge_proto_msgTypes,
	}.Build()
	File_workspace_v1_knowledge_proto = out.File
	file_workspace_v1_knowledge_proto_goTypes = nil
	file_workspace_v1_knowledge_proto_depIdxs = nil
}
