// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/v1/project.proto

package workspacev1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// status remains a lowercase string for existing JSON compatibility.
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Each value is a stable space.v1 Asset ID; Workspace owns the association.
	AssetIds      []string `protobuf:"bytes,6,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	CreatedAt     string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string   `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_workspace_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Project) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AssetIds      []string               `protobuf:"bytes,5,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_workspace_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateProjectRequest) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_workspace_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_workspace_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectResponse) Reset() {
	*x = GetProjectResponse{}
	mi := &file_workspace_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectResponse) ProtoMessage() {}

func (x *GetProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectResponse.ProtoReflect.Descriptor instead.
func (*GetProjectResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *GetProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type ListProjectsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Empty status lists every Project; otherwise the accepted lowercase status
	// vocabulary applies.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_workspace_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListProjectsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_workspace_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	IncludeClosed bool                   `protobuf:"varint,3,opt,name=include_closed,json=includeClosed,proto3" json:"include_closed,omitempty"`
	// Zero selects the default limit. Values above 50 are capped.
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProjectsRequest) Reset() {
	*x = SearchProjectsRequest{}
	mi := &file_workspace_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectsRequest) ProtoMessage() {}

func (x *SearchProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectsRequest.ProtoReflect.Descriptor instead.
func (*SearchProjectsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *SearchProjectsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SearchProjectsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProjectsRequest) GetIncludeClosed() bool {
	if x != nil {
		return x.IncludeClosed
	}
	return false
}

func (x *SearchProjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProjectsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ProjectSearchHit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Project        *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	MatchSource    string                 `protobuf:"bytes,2,opt,name=match_source,json=matchSource,proto3" json:"match_source,omitempty"`
	MatchedSnippet *string                `protobuf:"bytes,3,opt,name=matched_snippet,json=matchedSnippet,proto3,oneof" json:"matched_snippet,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectSearchHit) Reset() {
	*x = ProjectSearchHit{}
	mi := &file_workspace_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSearchHit) ProtoMessage() {}

func (x *ProjectSearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSearchHit.ProtoReflect.Descriptor instead.
func (*ProjectSearchHit) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectSearchHit) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectSearchHit) GetMatchSource() string {
	if x != nil {
		return x.MatchSource
	}
	return ""
}

func (x *ProjectSearchHit) GetMatchedSnippet() string {
	if x != nil && x.MatchedSnippet != nil {
		return *x.MatchedSnippet
	}
	return ""
}

type SearchProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*ProjectSearchHit    `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProjectsResponse) Reset() {
	*x = SearchProjectsResponse{}
	mi := &file_workspace_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProjectsResponse) ProtoMessage() {}

func (x *SearchProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProjectsResponse.ProtoReflect.Descriptor instead.
func (*SearchProjectsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *SearchProjectsResponse) GetHits() []*ProjectSearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchProjectsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_workspace_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProjectRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProjectRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type UpdateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectResponse) Reset() {
	*x = UpdateProjectResponse{}
	mi := &file_workspace_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectResponse) ProtoMessage() {}

func (x *UpdateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectResponse.ProtoReflect.Descriptor instead.
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_workspace_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProjectRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type DeleteProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_workspace_v1_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_project_proto_rawDescGZIP(), []int{13}
}

var File_workspace_v1_project_proto protoreflect.FileDescriptor

const file_workspace_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x1aworkspace/v1/project.proto\x12\fworkspace.v1\x1a\x1bannotations/v1/access.proto\"\xe5\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tasset_ids\x18\x06 \x03(\tR\bassetIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xa4\x01\n" +
	"\x14CreateProjectRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tasset_ids\x18\x05 \x03(\tR\bassetIds\"H\n" +
	"\x15CreateProjectResponse\x12/\n" +
	"\aproject\x18\x01 \x01(\v2\x15.workspace.v1.ProjectR\aproject\"U\n" +
	"\x11GetProjectRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"E\n" +
	"\x12GetProjectResponse\x12/\n" +
	"\aproject\x18\x01 \x01(\v2\x15.workspace.v1.ProjectR\aproject\"P\n" +
	"\x13ListProjectsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"_\n" +
	"\x14ListProjectsResponse\x121\n" +
	"\bprojects\x18\x01 \x03(\v2\x15.workspace.v1.ProjectR\bprojects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa5\x01\n" +
	"\x15SearchProjectsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12%\n" +
	"\x0einclude_closed\x18\x03 \x01(\bR\rincludeClosed\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"\xa8\x01\n" +
	"\x10ProjectSearchHit\x12/\n" +
	"\aproject\x18\x01 \x01(\v2\x15.workspace.v1.ProjectR\aproject\x12!\n" +
	"\fmatch_source\x18\x02 \x01(\tR\vmatchSource\x12,\n" +
	"\x0fmatched_snippet\x18\x03 \x01(\tH\x00R\x0ematchedSnippet\x88\x01\x01B\x12\n" +
	"\x10_matched_snippet\"b\n" +
	"\x16SearchProjectsResponse\x122\n" +
	"\x04hits\x18\x01 \x03(\v2\x1e.workspace.v1.ProjectSearchHitR\x04hits\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd9\x01\n" +
	"\x14UpdateProjectRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"H\n" +
	"\x15UpdateProjectResponse\x12/\n" +
	"\aproject\x18\x01 \x01(\v2\x15.workspace.v1.ProjectR\aproject\"X\n" +
	"\x14DeleteProjectRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\x17\n" +
	"\x15DeleteProjectResponse2\x84\b\n" +
	"\x0eProjectService\x12\xa5\x01\n" +
	"\rCreateProject\x12\".workspace.v1.CreateProjectRequest\x1a#.workspace.v1.CreateProjectResponse\"K\xd2\xf3\x18G\n" +
	"\x18workspace.project.create\x12\x0eCreate project\x1a\x11workspace.project\"\x06create@\x01\x12\x91\x01\n" +
	"\n" +
	"GetProject\x12\x1f.workspace.v1.GetProjectRequest\x1a .workspace.v1.GetProjectResponse\"@\xd2\xf3\x18<\n" +
	"\x15workspace.project.get\x12\vGet project\x1a\x11workspace.project\"\x03get\x12\x9b\x01\n" +
	"\fListProjects\x12!.workspace.v1.ListProjectsRequest\x1a\".workspace.v1.ListProjectsResponse\"D\xd2\xf3\x18@\n" +
	"\x16workspace.project.list\x12\rList projects\x1a\x11workspace.project\"\x04list\x12\xa7\x01\n" +
	"\x0eSearchProjects\x12#.workspace.v1.SearchProjectsRequest\x1a$.workspace.v1.SearchProjectsResponse\"J\xd2\xf3\x18F\n" +
	"\x18workspace.project.search\x12\x0fSearch projects\x1a\x11workspace.project\"\x06search\x12\xa5\x01\n" +
	"\rUpdateProject\x12\".workspace.v1.UpdateProjectRequest\x1a#.workspace.v1.UpdateProjectResponse\"K\xd2\xf3\x18G\n" +
	"\x18workspace.project.update\x12\x0eUpdate project\x1a\x11workspace.project\"\x06update@\x01\x12\xa5\x01\n" +
	"\rDeleteProject\x12\".workspace.v1.DeleteProjectRequest\x1a#.workspace.v1.DeleteProjectResponse\"K\xd2\xf3\x18G\n" +
	"\x18workspace.project.delete\x12\x0eDelete project\x1a\x11workspace.project\"\x06delete@\x01\x1a\x1e\xca\xf3\x18\x1a\n" +
	"\tworkspace\x12\tWorkspace\x1a\x02v1B?Z=github.com/hvritual/workspace/rpc/pb/workspace/v1;workspacev1b\x06proto3"

var (
	file_workspace_v1_project_proto_rawDescOnce sync.Once
	file_workspace_v1_project_proto_rawDescData []byte
)

func file_workspace_v1_project_proto_rawDescGZIP() []byte {
	file_workspace_v1_project_proto_rawDescOnce.Do(func() {
		file_workspace_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_project_proto_rawDesc), len(file_workspace_v1_project_proto_rawDesc)))
	})
	return file_workspace_v1_project_proto_rawDescData
}

var file_workspace_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_workspace_v1_project_proto_goTypes = []any{
	(*Project)(nil),                // 0: workspace.v1.Project
	(*CreateProjectRequest)(nil),   // 1: workspace.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),  // 2: workspace.v1.CreateProjectResponse
	(*GetProjectRequest)(nil),      // 3: workspace.v1.GetProjectRequest
	(*GetProjectResponse)(nil),     // 4: workspace.v1.GetProjectResponse
	(*ListProjectsRequest)(nil),    // 5: workspace.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),   // 6: workspace.v1.ListProjectsResponse
	(*SearchProjectsRequest)(nil),  // 7: workspace.v1.SearchProjectsRequest
	(*ProjectSearchHit)(nil),       // 8: workspace.v1.ProjectSearchHit
	(*SearchProjectsResponse)(nil), // 9: workspace.v1.SearchProjectsResponse
	(*UpdateProjectRequest)(nil),   // 10: workspace.v1.UpdateProjectRequest
	(*UpdateProjectResponse)(nil),  // 11: workspace.v1.UpdateProjectResponse
	(*DeleteProjectRequest)(nil),   // 12: workspace.v1.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),  // 13: workspace.v1.DeleteProjectResponse
}
var file_workspace_v1_project_proto_depIdxs = []int32{
	0,  // 0: workspace.v1.CreateProjectResponse.project:type_name -> workspace.v1.Project
	0,  // 1: workspace.v1.GetProjectResponse.project:type_name -> workspace.v1.Project
	0,  // 2: workspace.v1.ListProjectsResponse.projects:type_name -> workspace.v1.Project
	0,  // 3: workspace.v1.ProjectSearchHit.project:type_name -> workspace.v1.Project
	8,  // 4: workspace.v1.SearchProjectsResponse.hits:type_name -> workspace.v1.ProjectSearchHit
	0,  // 5: workspace.v1.UpdateProjectResponse.project:type_name -> workspace.v1.Project
	1,  // 6: workspace.v1.ProjectService.CreateProject:input_type -> workspace.v1.CreateProjectRequest
	3,  // 7: workspace.v1.ProjectService.GetProject:input_type -> workspace.v1.GetProjectRequest
	5,  // 8: workspace.v1.ProjectService.ListProjects:input_type -> workspace.v1.ListProjectsRequest
	7,  // 9: workspace.v1.ProjectService.SearchProjects:input_type -> workspace.v1.SearchProjectsRequest
	10, // 10: workspace.v1.ProjectService.UpdateProject:input_type -> workspace.v1.UpdateProjectRequest
	12, // 11: workspace.v1.ProjectService.DeleteProject:input_type -> workspace.v1.DeleteProjectRequest
	2,  // 12: workspace.v1.ProjectService.CreateProject:output_type -> workspace.v1.CreateProjectResponse
	4,  // 13: workspace.v1.ProjectService.GetProject:output_type -> workspace.v1.GetProjectResponse
	6,  // 14: workspace.v1.ProjectService.ListProjects:output_type -> workspace.v1.ListProjectsResponse
	9,  // 15: workspace.v1.ProjectService.SearchProjects:output_type -> workspace.v1.SearchProjectsResponse
	11, // 16: workspace.v1.ProjectService.UpdateProject:output_type -> workspace.v1.UpdateProjectResponse
	13, // 17: workspace.v1.ProjectService.DeleteProject:output_type -> workspace.v1.DeleteProjectResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_workspace_v1_project_proto_init() }
func file_workspace_v1_project_proto_init() {
	if File_workspace_v1_project_proto != nil {
		return
	}
	file_workspace_v1_project_proto_msgTypes[8].OneofWrappers = []any{}
	file_workspace_v1_project_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_project_proto_rawDesc), len(file_workspace_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_project_proto_goTypes,
		DependencyIndexes: file_workspace_v1_project_proto_depIdxs,
		MessageInfos:      file_workspace_v1_project_proto_msgTypes,
	}.Build()
	File_workspace_v1_project_proto = out.File
	file_workspace_v1_project_proto_goTypes = nil
	file_workspace_v1_project_proto_depIdxs = nil
}
