// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/v1/relationship.proto

package workspacev1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectActorRelation struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId   string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// actor_type remains member or agent; auth.v1 owns the referenced identity.
	ActorType string `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId   string `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// role remains lead, member, or agent for existing JSON compatibility.
	Role          string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectActorRelation) Reset() {
	*x = ProjectActorRelation{}
	mi := &file_workspace_v1_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectActorRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectActorRelation) ProtoMessage() {}

func (x *ProjectActorRelation) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectActorRelation.ProtoReflect.Descriptor instead.
func (*ProjectActorRelation) Descriptor() ([]byte, []int) {
	return file_workspace_v1_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectActorRelation) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ProjectActorRelation) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectActorRelation) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *ProjectActorRelation) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ProjectActorRelation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type PutProjectActorRelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *ProjectActorRelation  `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProjectActorRelationRequest) Reset() {
	*x = PutProjectActorRelationRequest{}
	mi := &file_workspace_v1_relationship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProjectActorRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProjectActorRelationRequest) ProtoMessage() {}

func (x *PutProjectActorRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_relationship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProjectActorRelationRequest.ProtoReflect.Descriptor instead.
func (*PutProjectActorRelationRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_relationship_proto_rawDescGZIP(), []int{1}
}

func (x *PutProjectActorRelationRequest) GetRelation() *ProjectActorRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type PutProjectActorRelationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *ProjectActorRelation  `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProjectActorRelationResponse) Reset() {
	*x = PutProjectActorRelationResponse{}
	mi := &file_workspace_v1_relationship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProjectActorRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProjectActorRelationResponse) ProtoMessage() {}

func (x *PutProjectActorRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_relationship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProjectActorRelationResponse.ProtoReflect.Descriptor instead.
func (*PutProjectActorRelationResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_relationship_proto_rawDescGZIP(), []int{2}
}

func (x *PutProjectActorRelationResponse) GetRelation() *ProjectActorRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type ListProjectActorRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectActorRelationsRequest) Reset() {
	*x = ListProjectActorRelationsRequest{}
	mi := &file_workspace_v1_relationship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectActorRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectActorRelationsRequest) ProtoMessage() {}

func (x *ListProjectActorRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_relationship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectActorRelationsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectActorRelationsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_relationship_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectActorRelationsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListProjectActorRelationsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectActorRelationsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Relations     []*ProjectActorRelation `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectActorRelationsResponse) Reset() {
	*x = ListProjectActorRelationsResponse{}
	mi := &file_workspace_v1_relationship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectActorRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectActorRelationsResponse) ProtoMessage() {}

func (x *ListProjectActorRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_relationship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectActorRelationsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectActorRelationsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_relationship_proto_rawDescGZIP(), []int{4}
}

func (x *ListProjectActorRelationsResponse) GetRelations() []*ProjectActorRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type DeleteProjectActorRelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ActorType     string                 `protobuf:"bytes,3,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectActorRelationRequest) Reset() {
	*x = DeleteProjectActorRelationRequest{}
	mi := &file_workspace_v1_relationship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectActorRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectActorRelationRequest) ProtoMessage() {}

func (x *DeleteProjectActorRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_relationship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectActorRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectActorRelationRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_relationship_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProjectActorRelationRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteProjectActorRelationRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteProjectActorRelationRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *DeleteProjectActorRelationRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type DeleteProjectActorRelationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectActorRelationResponse) Reset() {
	*x = DeleteProjectActorRelationResponse{}
	mi := &file_workspace_v1_relationship_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectActorRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectActorRelationResponse) ProtoMessage() {}

func (x *DeleteProjectActorRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_relationship_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectActorRelationResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectActorRelationResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_relationship_proto_rawDescGZIP(), []int{6}
}

var File_workspace_v1_relationship_proto protoreflect.FileDescriptor

const file_workspace_v1_relationship_proto_rawDesc = "" +
	"\n" +
	"\x1fworkspace/v1/relationship.proto\x12\fworkspace.v1\x1a\x1bannotations/v1/access.proto\"\xa6\x01\n" +
	"\x14ProjectActorRelation\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"`\n" +
	"\x1ePutProjectActorRelationRequest\x12>\n" +
	"\brelation\x18\x01 \x01(\v2\".workspace.v1.ProjectActorRelationR\brelation\"a\n" +
	"\x1fPutProjectActorRelationResponse\x12>\n" +
	"\brelation\x18\x01 \x01(\v2\".workspace.v1.ProjectActorRelationR\brelation\"d\n" +
	" ListProjectActorRelationsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"e\n" +
	"!ListProjectActorRelationsResponse\x12@\n" +
	"\trelations\x18\x01 \x03(\v2\".workspace.v1.ProjectActorRelationR\trelations\"\x9f\x01\n" +
	"!DeleteProjectActorRelationRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\"$\n" +
	"\"DeleteProjectActorRelationResponse2\xd1\x05\n" +
	"\x13RelationshipService\x12\xd3\x01\n" +
	"\x17PutProjectActorRelation\x12,.workspace.v1.PutProjectActorRelationRequest\x1a-.workspace.v1.PutProjectActorRelationResponse\"[\xd2\xf3\x18W\n" +
	"\x1aworkspace.relationship.put\x12\x1aPut project actor relation\x1a\x16workspace.relationship\"\x03put@\x01\x12\xdb\x01\n" +
	"\x19ListProjectActorRelations\x12..workspace.v1.ListProjectActorRelationsRequest\x1a/.workspace.v1.ListProjectActorRelationsResponse\"]\xd2\xf3\x18Y\n" +
	"\x1bworkspace.relationship.list\x12\x1cList project actor relations\x1a\x16workspace.relationship\"\x04list\x12\xe5\x01\n" +
	"\x1aDeleteProjectActorRelation\x12/.workspace.v1.DeleteProjectActorRelationRequest\x1a0.workspace.v1.DeleteProjectActorRelationResponse\"d\xd2\xf3\x18`\n" +
	"\x1dworkspace.relationship.delete\x12\x1dDelete project actor relation\x1a\x16workspace.relationship\"\x06delete@\x01\x1a\x1e\xca\xf3\x18\x1a\n" +
	"\tworkspace\x12\tWorkspace\x1a\x02v1B?Z=github.com/hvritual/workspace/rpc/pb/workspace/v1;workspacev1b\x06proto3"

var (
	file_workspace_v1_relationship_proto_rawDescOnce sync.Once
	file_workspace_v1_relationship_proto_rawDescData []byte
)

func file_workspace_v1_relationship_proto_rawDescGZIP() []byte {
	file_workspace_v1_relationship_proto_rawDescOnce.Do(func() {
		file_workspace_v1_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_relationship_proto_rawDesc), len(file_workspace_v1_relationship_proto_rawDesc)))
	})
	return file_workspace_v1_relationship_proto_rawDescData
}

var file_workspace_v1_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_workspace_v1_relationship_proto_goTypes = []any{
	(*ProjectActorRelation)(nil),               // 0: workspace.v1.ProjectActorRelation
	(*PutProjectActorRelationRequest)(nil),     // 1: workspace.v1.PutProjectActorRelationRequest
	(*PutProjectActorRelationResponse)(nil),    // 2: workspace.v1.PutProjectActorRelationResponse
	(*ListProjectActorRelationsRequest)(nil),   // 3: workspace.v1.ListProjectActorRelationsRequest
	(*ListProjectActorRelationsResponse)(nil),  // 4: workspace.v1.ListProjectActorRelationsResponse
	(*DeleteProjectActorRelationRequest)(nil),  // 5: workspace.v1.DeleteProjectActorRelationRequest
	(*DeleteProjectActorRelationResponse)(nil), // 6: workspace.v1.DeleteProjectActorRelationResponse
}
var file_workspace_v1_relationship_proto_depIdxs = []int32{
	0, // 0: workspace.v1.PutProjectActorRelationRequest.relation:type_name -> workspace.v1.ProjectActorRelation
	0, // 1: workspace.v1.PutProjectActorRelationResponse.relation:type_name -> workspace.v1.ProjectActorRelation
	0, // 2: workspace.v1.ListProjectActorRelationsResponse.relations:type_name -> workspace.v1.ProjectActorRelation
	1, // 3: workspace.v1.RelationshipService.PutProjectActorRelation:input_type -> workspace.v1.PutProjectActorRelationRequest
	3, // 4: workspace.v1.RelationshipService.ListProjectActorRelations:input_type -> workspace.v1.ListProjectActorRelationsRequest
	5, // 5: workspace.v1.RelationshipService.DeleteProjectActorRelation:input_type -> workspace.v1.DeleteProjectActorRelationRequest
	2, // 6: workspace.v1.RelationshipService.PutProjectActorRelation:output_type -> workspace.v1.PutProjectActorRelationResponse
	4, // 7: workspace.v1.RelationshipService.ListProjectActorRelations:output_type -> workspace.v1.ListProjectActorRelationsResponse
	6, // 8: workspace.v1.RelationshipService.DeleteProjectActorRelation:output_type -> workspace.v1.DeleteProjectActorRelationResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_workspace_v1_relationship_proto_init() }
func file_workspace_v1_relationship_proto_init() {
	if File_workspace_v1_relationship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_relationship_proto_rawDesc), len(file_workspace_v1_relationship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_relationship_proto_goTypes,
		DependencyIndexes: file_workspace_v1_relationship_proto_depIdxs,
		MessageInfos:      file_workspace_v1_relationship_proto_msgTypes,
	}.Build()
	File_workspace_v1_relationship_proto = out.File
	file_workspace_v1_relationship_proto_goTypes = nil
	file_workspace_v1_relationship_proto_depIdxs = nil
}
