// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: workspace/v1/requirement.proto

package workspacev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequirementService_SaveRequirementVersion_FullMethodName = "/workspace.v1.RequirementService/SaveRequirementVersion"
	RequirementService_GetRequirement_FullMethodName         = "/workspace.v1.RequirementService/GetRequirement"
)

// RequirementServiceClient is the client API for RequirementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RequirementService owns versioned Project requirements, approval state,
// coverage, and Requirement-to-Issue traceability. Referenced Projects and
// Issues remain owned by their respective Workspace services.
type RequirementServiceClient interface {
	SaveRequirementVersion(ctx context.Context, in *SaveRequirementVersionRequest, opts ...grpc.CallOption) (*SaveRequirementVersionResponse, error)
	GetRequirement(ctx context.Context, in *GetRequirementRequest, opts ...grpc.CallOption) (*GetRequirementResponse, error)
}

type requirementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequirementServiceClient(cc grpc.ClientConnInterface) RequirementServiceClient {
	return &requirementServiceClient{cc}
}

func (c *requirementServiceClient) SaveRequirementVersion(ctx context.Context, in *SaveRequirementVersionRequest, opts ...grpc.CallOption) (*SaveRequirementVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRequirementVersionResponse)
	err := c.cc.Invoke(ctx, RequirementService_SaveRequirementVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementServiceClient) GetRequirement(ctx context.Context, in *GetRequirementRequest, opts ...grpc.CallOption) (*GetRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequirementResponse)
	err := c.cc.Invoke(ctx, RequirementService_GetRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequirementServiceServer is the server API for RequirementService service.
// All implementations must embed UnimplementedRequirementServiceServer
// for forward compatibility.
//
// RequirementService owns versioned Project requirements, approval state,
// coverage, and Requirement-to-Issue traceability. Referenced Projects and
// Issues remain owned by their respective Workspace services.
type RequirementServiceServer interface {
	SaveRequirementVersion(context.Context, *SaveRequirementVersionRequest) (*SaveRequirementVersionResponse, error)
	GetRequirement(context.Context, *GetRequirementRequest) (*GetRequirementResponse, error)
	mustEmbedUnimplementedRequirementServiceServer()
}

// UnimplementedRequirementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequirementServiceServer struct{}

func (UnimplementedRequirementServiceServer) SaveRequirementVersion(context.Context, *SaveRequirementVersionRequest) (*SaveRequirementVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRequirementVersion not implemented")
}
func (UnimplementedRequirementServiceServer) GetRequirement(context.Context, *GetRequirementRequest) (*GetRequirementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequirement not implemented")
}
func (UnimplementedRequirementServiceServer) mustEmbedUnimplementedRequirementServiceServer() {}
func (UnimplementedRequirementServiceServer) testEmbeddedByValue()                            {}

// UnsafeRequirementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequirementServiceServer will
// result in compilation errors.
type UnsafeRequirementServiceServer interface {
	mustEmbedUnimplementedRequirementServiceServer()
}

func RegisterRequirementServiceServer(s grpc.ServiceRegistrar, srv RequirementServiceServer) {
	// If the following call pancis, it indicates UnimplementedRequirementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequirementService_ServiceDesc, srv)
}

func _RequirementService_SaveRequirementVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequirementVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).SaveRequirementVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_SaveRequirementVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).SaveRequirementVersion(ctx, req.(*SaveRequirementVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementService_GetRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementServiceServer).GetRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementService_GetRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementServiceServer).GetRequirement(ctx, req.(*GetRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequirementService_ServiceDesc is the grpc.ServiceDesc for RequirementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequirementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workspace.v1.RequirementService",
	HandlerType: (*RequirementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveRequirementVersion",
			Handler:    _RequirementService_SaveRequirementVersion_Handler,
		},
		{
			MethodName: "GetRequirement",
			Handler:    _RequirementService_GetRequirement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workspace/v1/requirement.proto",
}
