// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/v1/requirement.proto

package workspacev1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Requirement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	CurrentVersion int32                  `protobuf:"varint,5,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	ApprovalStatus string                 `protobuf:"bytes,6,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	CoverageStatus string                 `protobuf:"bytes,7,opt,name=coverage_status,json=coverageStatus,proto3" json:"coverage_status,omitempty"`
	IssueIds       []string               `protobuf:"bytes,8,rep,name=issue_ids,json=issueIds,proto3" json:"issue_ids,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_workspace_v1_requirement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_requirement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_workspace_v1_requirement_proto_rawDescGZIP(), []int{0}
}

func (x *Requirement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Requirement) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Requirement) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Requirement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Requirement) GetCurrentVersion() int32 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *Requirement) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *Requirement) GetCoverageStatus() string {
	if x != nil {
		return x.CoverageStatus
	}
	return ""
}

func (x *Requirement) GetIssueIds() []string {
	if x != nil {
		return x.IssueIds
	}
	return nil
}

func (x *Requirement) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Requirement) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RequirementVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequirementId string                 `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequirementVersion) Reset() {
	*x = RequirementVersion{}
	mi := &file_workspace_v1_requirement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequirementVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequirementVersion) ProtoMessage() {}

func (x *RequirementVersion) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_requirement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequirementVersion.ProtoReflect.Descriptor instead.
func (*RequirementVersion) Descriptor() ([]byte, []int) {
	return file_workspace_v1_requirement_proto_rawDescGZIP(), []int{1}
}

func (x *RequirementVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequirementVersion) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

func (x *RequirementVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RequirementVersion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RequirementVersion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SaveRequirementVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RequirementId *string                `protobuf:"bytes,3,opt,name=requirement_id,json=requirementId,proto3,oneof" json:"requirement_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	IssueIds      []string               `protobuf:"bytes,6,rep,name=issue_ids,json=issueIds,proto3" json:"issue_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequirementVersionRequest) Reset() {
	*x = SaveRequirementVersionRequest{}
	mi := &file_workspace_v1_requirement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequirementVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequirementVersionRequest) ProtoMessage() {}

func (x *SaveRequirementVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_requirement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequirementVersionRequest.ProtoReflect.Descriptor instead.
func (*SaveRequirementVersionRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_requirement_proto_rawDescGZIP(), []int{2}
}

func (x *SaveRequirementVersionRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SaveRequirementVersionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SaveRequirementVersionRequest) GetRequirementId() string {
	if x != nil && x.RequirementId != nil {
		return *x.RequirementId
	}
	return ""
}

func (x *SaveRequirementVersionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaveRequirementVersionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveRequirementVersionRequest) GetIssueIds() []string {
	if x != nil {
		return x.IssueIds
	}
	return nil
}

type SaveRequirementVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirement   *Requirement           `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	Version       *RequirementVersion    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequirementVersionResponse) Reset() {
	*x = SaveRequirementVersionResponse{}
	mi := &file_workspace_v1_requirement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequirementVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequirementVersionResponse) ProtoMessage() {}

func (x *SaveRequirementVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_requirement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequirementVersionResponse.ProtoReflect.Descriptor instead.
func (*SaveRequirementVersionResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_requirement_proto_rawDescGZIP(), []int{3}
}

func (x *SaveRequirementVersionResponse) GetRequirement() *Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *SaveRequirementVersionResponse) GetVersion() *RequirementVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetRequirementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RequirementId string                 `protobuf:"bytes,2,opt,name=requirement_id,json=requirementId,proto3" json:"requirement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequirementRequest) Reset() {
	*x = GetRequirementRequest{}
	mi := &file_workspace_v1_requirement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequirementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequirementRequest) ProtoMessage() {}

func (x *GetRequirementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_requirement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequirementRequest.ProtoReflect.Descriptor instead.
func (*GetRequirementRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_requirement_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequirementRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetRequirementRequest) GetRequirementId() string {
	if x != nil {
		return x.RequirementId
	}
	return ""
}

type GetRequirementResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requirement    *Requirement           `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	CurrentVersion *RequirementVersion    `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequirementResponse) Reset() {
	*x = GetRequirementResponse{}
	mi := &file_workspace_v1_requirement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequirementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequirementResponse) ProtoMessage() {}

func (x *GetRequirementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_requirement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequirementResponse.ProtoReflect.Descriptor instead.
func (*GetRequirementResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_requirement_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequirementResponse) GetRequirement() *Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *GetRequirementResponse) GetCurrentVersion() *RequirementVersion {
	if x != nil {
		return x.CurrentVersion
	}
	return nil
}

var File_workspace_v1_requirement_proto protoreflect.FileDescriptor

const file_workspace_v1_requirement_proto_rawDesc = "" +
	"\n" +
	"\x1eworkspace/v1/requirement.proto\x12\fworkspace.v1\x1a\x1bannotations/v1/access.proto\"\xcb\x02\n" +
	"\vRequirement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12'\n" +
	"\x0fcurrent_version\x18\x05 \x01(\x05R\x0ecurrentVersion\x12'\n" +
	"\x0fapproval_status\x18\x06 \x01(\tR\x0eapprovalStatus\x12'\n" +
	"\x0fcoverage_status\x18\a \x01(\tR\x0ecoverageStatus\x12\x1b\n" +
	"\tissue_ids\x18\b \x03(\tR\bissueIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x9e\x01\n" +
	"\x12RequirementVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0erequirement_id\x18\x02 \x01(\tR\rrequirementId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xed\x01\n" +
	"\x1dSaveRequirementVersionRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12*\n" +
	"\x0erequirement_id\x18\x03 \x01(\tH\x00R\rrequirementId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tissue_ids\x18\x06 \x03(\tR\bissueIdsB\x11\n" +
	"\x0f_requirement_id\"\x99\x01\n" +
	"\x1eSaveRequirementVersionResponse\x12;\n" +
	"\vrequirement\x18\x01 \x01(\v2\x19.workspace.v1.RequirementR\vrequirement\x12:\n" +
	"\aversion\x18\x02 \x01(\v2 .workspace.v1.RequirementVersionR\aversion\"a\n" +
	"\x15GetRequirementRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12%\n" +
	"\x0erequirement_id\x18\x02 \x01(\tR\rrequirementId\"\xa0\x01\n" +
	"\x16GetRequirementResponse\x12;\n" +
	"\vrequirement\x18\x01 \x01(\v2\x19.workspace.v1.RequirementR\vrequirement\x12I\n" +
	"\x0fcurrent_version\x18\x02 \x01(\v2 .workspace.v1.RequirementVersionR\x0ecurrentVersion2\xc1\x03\n" +
	"\x12RequirementService\x12\xde\x01\n" +
	"\x16SaveRequirementVersion\x12+.workspace.v1.SaveRequirementVersionRequest\x1a,.workspace.v1.SaveRequirementVersionResponse\"i\xd2\xf3\x18e\n" +
	"\"workspace.requirement.save_version\x12\x18Save requirement version\x1a\x15workspace.requirement\"\fsave_version@\x01\x12\xa9\x01\n" +
	"\x0eGetRequirement\x12#.workspace.v1.GetRequirementRequest\x1a$.workspace.v1.GetRequirementResponse\"L\xd2\xf3\x18H\n" +
	"\x19workspace.requirement.get\x12\x0fGet requirement\x1a\x15workspace.requirement\"\x03get\x1a\x1e\xca\xf3\x18\x1a\n" +
	"\tworkspace\x12\tWorkspace\x1a\x02v1B?Z=github.com/hvritual/workspace/rpc/pb/workspace/v1;workspacev1b\x06proto3"

var (
	file_workspace_v1_requirement_proto_rawDescOnce sync.Once
	file_workspace_v1_requirement_proto_rawDescData []byte
)

func file_workspace_v1_requirement_proto_rawDescGZIP() []byte {
	file_workspace_v1_requirement_proto_rawDescOnce.Do(func() {
		file_workspace_v1_requirement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_requirement_proto_rawDesc), len(file_workspace_v1_requirement_proto_rawDesc)))
	})
	return file_workspace_v1_requirement_proto_rawDescData
}

var file_workspace_v1_requirement_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_workspace_v1_requirement_proto_goTypes = []any{
	(*Requirement)(nil),                    // 0: workspace.v1.Requirement
	(*RequirementVersion)(nil),             // 1: workspace.v1.RequirementVersion
	(*SaveRequirementVersionRequest)(nil),  // 2: workspace.v1.SaveRequirementVersionRequest
	(*SaveRequirementVersionResponse)(nil), // 3: workspace.v1.SaveRequirementVersionResponse
	(*GetRequirementRequest)(nil),          // 4: workspace.v1.GetRequirementRequest
	(*GetRequirementResponse)(nil),         // 5: workspace.v1.GetRequirementResponse
}
var file_workspace_v1_requirement_proto_depIdxs = []int32{
	0, // 0: workspace.v1.SaveRequirementVersionResponse.requirement:type_name -> workspace.v1.Requirement
	1, // 1: workspace.v1.SaveRequirementVersionResponse.version:type_name -> workspace.v1.RequirementVersion
	0, // 2: workspace.v1.GetRequirementResponse.requirement:type_name -> workspace.v1.Requirement
	1, // 3: workspace.v1.GetRequirementResponse.current_version:type_name -> workspace.v1.RequirementVersion
	2, // 4: workspace.v1.RequirementService.SaveRequirementVersion:input_type -> workspace.v1.SaveRequirementVersionRequest
	4, // 5: workspace.v1.RequirementService.GetRequirement:input_type -> workspace.v1.GetRequirementRequest
	3, // 6: workspace.v1.RequirementService.SaveRequirementVersion:output_type -> workspace.v1.SaveRequirementVersionResponse
	5, // 7: workspace.v1.RequirementService.GetRequirement:output_type -> workspace.v1.GetRequirementResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_workspace_v1_requirement_proto_init() }
func file_workspace_v1_requirement_proto_init() {
	if File_workspace_v1_requirement_proto != nil {
		return
	}
	file_workspace_v1_requirement_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_requirement_proto_rawDesc), len(file_workspace_v1_requirement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_requirement_proto_goTypes,
		DependencyIndexes: file_workspace_v1_requirement_proto_depIdxs,
		MessageInfos:      file_workspace_v1_requirement_proto_msgTypes,
	}.Build()
	File_workspace_v1_requirement_proto = out.File
	file_workspace_v1_requirement_proto_goTypes = nil
	file_workspace_v1_requirement_proto_depIdxs = nil
}
