// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/v1/todo.proto

package workspacev1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Todo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Title       string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// status remains a lowercase string for existing JSON compatibility.
	Status    string  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ProjectId *string `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	IssueId   *string `protobuf:"bytes,7,opt,name=issue_id,json=issueId,proto3,oneof" json:"issue_id,omitempty"`
	// assignee_type remains member or agent; the identity is owned by auth.v1.
	AssigneeType *string `protobuf:"bytes,8,opt,name=assignee_type,json=assigneeType,proto3,oneof" json:"assignee_type,omitempty"`
	AssigneeId   *string `protobuf:"bytes,9,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	CreatedAt    string  `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string  `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// priority remains urgent, high, medium, low, or none for JSON compatibility.
	Priority      string  `protobuf:"bytes,12,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatorType   string  `protobuf:"bytes,13,opt,name=creator_type,json=creatorType,proto3" json:"creator_type,omitempty"`
	CreatorId     string  `protobuf:"bytes,14,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Position      float64 `protobuf:"fixed64,15,opt,name=position,proto3" json:"position,omitempty"`
	StartDate     *string `protobuf:"bytes,16,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	DueDate       *string `protobuf:"bytes,17,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	CompletedAt   *string `protobuf:"bytes,18,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_workspace_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Todo) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *Todo) GetIssueId() string {
	if x != nil && x.IssueId != nil {
		return *x.IssueId
	}
	return ""
}

func (x *Todo) GetAssigneeType() string {
	if x != nil && x.AssigneeType != nil {
		return *x.AssigneeType
	}
	return ""
}

func (x *Todo) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *Todo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Todo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Todo) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Todo) GetCreatorType() string {
	if x != nil {
		return x.CreatorType
	}
	return ""
}

func (x *Todo) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Todo) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Todo) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *Todo) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

func (x *Todo) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProjectId     *string                `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	IssueId       *string                `protobuf:"bytes,5,opt,name=issue_id,json=issueId,proto3,oneof" json:"issue_id,omitempty"`
	AssigneeType  *string                `protobuf:"bytes,6,opt,name=assignee_type,json=assigneeType,proto3,oneof" json:"assignee_type,omitempty"`
	AssigneeId    *string                `protobuf:"bytes,7,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,9,opt,name=priority,proto3" json:"priority,omitempty"`
	Position      float64                `protobuf:"fixed64,10,opt,name=position,proto3" json:"position,omitempty"`
	StartDate     *string                `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	DueDate       *string                `protobuf:"bytes,12,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_workspace_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTodoRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *CreateTodoRequest) GetIssueId() string {
	if x != nil && x.IssueId != nil {
		return *x.IssueId
	}
	return ""
}

func (x *CreateTodoRequest) GetAssigneeType() string {
	if x != nil && x.AssigneeType != nil {
		return *x.AssigneeType
	}
	return ""
}

func (x *CreateTodoRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *CreateTodoRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTodoRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateTodoRequest) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateTodoRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *CreateTodoRequest) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

type CreateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoResponse) Reset() {
	*x = CreateTodoResponse{}
	mi := &file_workspace_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoResponse) ProtoMessage() {}

func (x *CreateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type GetTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TodoId        string                 `protobuf:"bytes,2,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_workspace_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetTodoRequest) GetTodoId() string {
	if x != nil {
		return x.TodoId
	}
	return ""
}

type GetTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoResponse) Reset() {
	*x = GetTodoResponse{}
	mi := &file_workspace_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoResponse) ProtoMessage() {}

func (x *GetTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoResponse.ProtoReflect.Descriptor instead.
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *GetTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type ListTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ProjectId     *string                `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	IssueId       *string                `protobuf:"bytes,3,opt,name=issue_id,json=issueId,proto3,oneof" json:"issue_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_workspace_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *ListTodosRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListTodosRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *ListTodosRequest) GetIssueId() string {
	if x != nil && x.IssueId != nil {
		return *x.IssueId
	}
	return ""
}

func (x *ListTodosRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_workspace_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *ListTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *ListTodosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TodoId        string                 `protobuf:"bytes,2,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	ProjectId     *string                `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	IssueId       *string                `protobuf:"bytes,4,opt,name=issue_id,json=issueId,proto3,oneof" json:"issue_id,omitempty"`
	Title         *string                `protobuf:"bytes,5,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Priority      *string                `protobuf:"bytes,8,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	AssigneeType  *string                `protobuf:"bytes,9,opt,name=assignee_type,json=assigneeType,proto3,oneof" json:"assignee_type,omitempty"`
	AssigneeId    *string                `protobuf:"bytes,10,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id,omitempty"`
	Position      *float64               `protobuf:"fixed64,11,opt,name=position,proto3,oneof" json:"position,omitempty"`
	StartDate     *string                `protobuf:"bytes,12,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	DueDate       *string                `protobuf:"bytes,13,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_workspace_v1_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTodoRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateTodoRequest) GetTodoId() string {
	if x != nil {
		return x.TodoId
	}
	return ""
}

func (x *UpdateTodoRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *UpdateTodoRequest) GetIssueId() string {
	if x != nil && x.IssueId != nil {
		return *x.IssueId
	}
	return ""
}

func (x *UpdateTodoRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateTodoRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTodoRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateTodoRequest) GetPriority() string {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return ""
}

func (x *UpdateTodoRequest) GetAssigneeType() string {
	if x != nil && x.AssigneeType != nil {
		return *x.AssigneeType
	}
	return ""
}

func (x *UpdateTodoRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *UpdateTodoRequest) GetPosition() float64 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *UpdateTodoRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *UpdateTodoRequest) GetDueDate() string {
	if x != nil && x.DueDate != nil {
		return *x.DueDate
	}
	return ""
}

type UpdateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoResponse) Reset() {
	*x = UpdateTodoResponse{}
	mi := &file_workspace_v1_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoResponse) ProtoMessage() {}

func (x *UpdateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type UpdateTodoStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TodoId        string                 `protobuf:"bytes,2,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoStatusRequest) Reset() {
	*x = UpdateTodoStatusRequest{}
	mi := &file_workspace_v1_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoStatusRequest) ProtoMessage() {}

func (x *UpdateTodoStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoStatusRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTodoStatusRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateTodoStatusRequest) GetTodoId() string {
	if x != nil {
		return x.TodoId
	}
	return ""
}

func (x *UpdateTodoStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateTodoStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoStatusResponse) Reset() {
	*x = UpdateTodoStatusResponse{}
	mi := &file_workspace_v1_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoStatusResponse) ProtoMessage() {}

func (x *UpdateTodoStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoStatusResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTodoStatusResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TodoId        string                 `protobuf:"bytes,2,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_workspace_v1_todo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTodoRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteTodoRequest) GetTodoId() string {
	if x != nil {
		return x.TodoId
	}
	return ""
}

type DeleteTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoResponse) Reset() {
	*x = DeleteTodoResponse{}
	mi := &file_workspace_v1_todo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoResponse) ProtoMessage() {}

func (x *DeleteTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_todo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoResponse.ProtoReflect.Descriptor instead.
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_todo_proto_rawDescGZIP(), []int{12}
}

var File_workspace_v1_todo_proto protoreflect.FileDescriptor

const file_workspace_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x17workspace/v1/todo.proto\x12\fworkspace.v1\x1a\x1bannotations/v1/access.proto\"\xac\x05\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\"\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12\x1e\n" +
	"\bissue_id\x18\a \x01(\tH\x01R\aissueId\x88\x01\x01\x12(\n" +
	"\rassignee_type\x18\b \x01(\tH\x02R\fassigneeType\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\t \x01(\tH\x03R\n" +
	"assigneeId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1a\n" +
	"\bpriority\x18\f \x01(\tR\bpriority\x12!\n" +
	"\fcreator_type\x18\r \x01(\tR\vcreatorType\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x0e \x01(\tR\tcreatorId\x12\x1a\n" +
	"\bposition\x18\x0f \x01(\x01R\bposition\x12\"\n" +
	"\n" +
	"start_date\x18\x10 \x01(\tH\x04R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\x11 \x01(\tH\x05R\adueDate\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\x12 \x01(\tH\x06R\vcompletedAt\x88\x01\x01B\r\n" +
	"\v_project_idB\v\n" +
	"\t_issue_idB\x10\n" +
	"\x0e_assignee_typeB\x0e\n" +
	"\f_assignee_idB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_due_dateB\x0f\n" +
	"\r_completed_at\"\xf0\x03\n" +
	"\x11CreateTodoRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12\x1e\n" +
	"\bissue_id\x18\x05 \x01(\tH\x01R\aissueId\x88\x01\x01\x12(\n" +
	"\rassignee_type\x18\x06 \x01(\tH\x02R\fassigneeType\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\a \x01(\tH\x03R\n" +
	"assigneeId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\t \x01(\tR\bpriority\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\x01R\bposition\x12\"\n" +
	"\n" +
	"start_date\x18\v \x01(\tH\x04R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\f \x01(\tH\x05R\adueDate\x88\x01\x01B\r\n" +
	"\v_project_idB\v\n" +
	"\t_issue_idB\x10\n" +
	"\x0e_assignee_typeB\x0e\n" +
	"\f_assignee_idB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_due_date\"<\n" +
	"\x12CreateTodoResponse\x12&\n" +
	"\x04todo\x18\x01 \x01(\v2\x12.workspace.v1.TodoR\x04todo\"L\n" +
	"\x0eGetTodoRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atodo_id\x18\x02 \x01(\tR\x06todoId\"9\n" +
	"\x0fGetTodoResponse\x12&\n" +
	"\x04todo\x18\x01 \x01(\v2\x12.workspace.v1.TodoR\x04todo\"\xad\x01\n" +
	"\x10ListTodosRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\"\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12\x1e\n" +
	"\bissue_id\x18\x03 \x01(\tH\x01R\aissueId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06statusB\r\n" +
	"\v_project_idB\v\n" +
	"\t_issue_id\"S\n" +
	"\x11ListTodosResponse\x12(\n" +
	"\x05todos\x18\x01 \x03(\v2\x12.workspace.v1.TodoR\x05todos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe1\x04\n" +
	"\x11UpdateTodoRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atodo_id\x18\x02 \x01(\tR\x06todoId\x12\"\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12\x1e\n" +
	"\bissue_id\x18\x04 \x01(\tH\x01R\aissueId\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tH\x02R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x04R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\b \x01(\tH\x05R\bpriority\x88\x01\x01\x12(\n" +
	"\rassignee_type\x18\t \x01(\tH\x06R\fassigneeType\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\n" +
	" \x01(\tH\aR\n" +
	"assigneeId\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\v \x01(\x01H\bR\bposition\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\f \x01(\tH\tR\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bdue_date\x18\r \x01(\tH\n" +
	"R\adueDate\x88\x01\x01B\r\n" +
	"\v_project_idB\v\n" +
	"\t_issue_idB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_statusB\v\n" +
	"\t_priorityB\x10\n" +
	"\x0e_assignee_typeB\x0e\n" +
	"\f_assignee_idB\v\n" +
	"\t_positionB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_due_date\"<\n" +
	"\x12UpdateTodoResponse\x12&\n" +
	"\x04todo\x18\x01 \x01(\v2\x12.workspace.v1.TodoR\x04todo\"m\n" +
	"\x17UpdateTodoStatusRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atodo_id\x18\x02 \x01(\tR\x06todoId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"B\n" +
	"\x18UpdateTodoStatusResponse\x12&\n" +
	"\x04todo\x18\x01 \x01(\v2\x12.workspace.v1.TodoR\x04todo\"O\n" +
	"\x11DeleteTodoRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atodo_id\x18\x02 \x01(\tR\x06todoId\"\x14\n" +
	"\x12DeleteTodoResponse2\xbb\a\n" +
	"\vTodoService\x12\x93\x01\n" +
	"\n" +
	"CreateTodo\x12\x1f.workspace.v1.CreateTodoRequest\x1a .workspace.v1.CreateTodoResponse\"B\xd2\xf3\x18>\n" +
	"\x15workspace.todo.create\x12\vCreate todo\x1a\x0eworkspace.todo\"\x06create@\x01\x12\x7f\n" +
	"\aGetTodo\x12\x1c.workspace.v1.GetTodoRequest\x1a\x1d.workspace.v1.GetTodoResponse\"7\xd2\xf3\x183\n" +
	"\x12workspace.todo.get\x12\bGet todo\x1a\x0eworkspace.todo\"\x03get\x12\x89\x01\n" +
	"\tListTodos\x12\x1e.workspace.v1.ListTodosRequest\x1a\x1f.workspace.v1.ListTodosResponse\";\xd2\xf3\x187\n" +
	"\x13workspace.todo.list\x12\n" +
	"List todos\x1a\x0eworkspace.todo\"\x04list\x12\x93\x01\n" +
	"\n" +
	"UpdateTodo\x12\x1f.workspace.v1.UpdateTodoRequest\x1a .workspace.v1.UpdateTodoResponse\"B\xd2\xf3\x18>\n" +
	"\x15workspace.todo.update\x12\vUpdate todo\x1a\x0eworkspace.todo\"\x06update@\x01\x12\xba\x01\n" +
	"\x10UpdateTodoStatus\x12%.workspace.v1.UpdateTodoStatusRequest\x1a&.workspace.v1.UpdateTodoStatusResponse\"W\xd2\xf3\x18S\n" +
	"\x1cworkspace.todo.update_status\x12\x12Update todo status\x1a\x0eworkspace.todo\"\rupdate_status@\x01\x12\x95\x01\n" +
	"\n" +
	"DeleteTodo\x12\x1f.workspace.v1.DeleteTodoRequest\x1a .workspace.v1.DeleteTodoResponse\"D\xd2\xf3\x18@\n" +
	"\x15workspace.todo.delete\x12\vDelete todo\x1a\x0eworkspace.todo\"\x06delete@\x01H\x01\x1a\x1e\xca\xf3\x18\x1a\n" +
	"\tworkspace\x12\tWorkspace\x1a\x02v1B?Z=github.com/hvritual/workspace/rpc/pb/workspace/v1;workspacev1b\x06proto3"

var (
	file_workspace_v1_todo_proto_rawDescOnce sync.Once
	file_workspace_v1_todo_proto_rawDescData []byte
)

func file_workspace_v1_todo_proto_rawDescGZIP() []byte {
	file_workspace_v1_todo_proto_rawDescOnce.Do(func() {
		file_workspace_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_todo_proto_rawDesc), len(file_workspace_v1_todo_proto_rawDesc)))
	})
	return file_workspace_v1_todo_proto_rawDescData
}

var file_workspace_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_workspace_v1_todo_proto_goTypes = []any{
	(*Todo)(nil),                     // 0: workspace.v1.Todo
	(*CreateTodoRequest)(nil),        // 1: workspace.v1.CreateTodoRequest
	(*CreateTodoResponse)(nil),       // 2: workspace.v1.CreateTodoResponse
	(*GetTodoRequest)(nil),           // 3: workspace.v1.GetTodoRequest
	(*GetTodoResponse)(nil),          // 4: workspace.v1.GetTodoResponse
	(*ListTodosRequest)(nil),         // 5: workspace.v1.ListTodosRequest
	(*ListTodosResponse)(nil),        // 6: workspace.v1.ListTodosResponse
	(*UpdateTodoRequest)(nil),        // 7: workspace.v1.UpdateTodoRequest
	(*UpdateTodoResponse)(nil),       // 8: workspace.v1.UpdateTodoResponse
	(*UpdateTodoStatusRequest)(nil),  // 9: workspace.v1.UpdateTodoStatusRequest
	(*UpdateTodoStatusResponse)(nil), // 10: workspace.v1.UpdateTodoStatusResponse
	(*DeleteTodoRequest)(nil),        // 11: workspace.v1.DeleteTodoRequest
	(*DeleteTodoResponse)(nil),       // 12: workspace.v1.DeleteTodoResponse
}
var file_workspace_v1_todo_proto_depIdxs = []int32{
	0,  // 0: workspace.v1.CreateTodoResponse.todo:type_name -> workspace.v1.Todo
	0,  // 1: workspace.v1.GetTodoResponse.todo:type_name -> workspace.v1.Todo
	0,  // 2: workspace.v1.ListTodosResponse.todos:type_name -> workspace.v1.Todo
	0,  // 3: workspace.v1.UpdateTodoResponse.todo:type_name -> workspace.v1.Todo
	0,  // 4: workspace.v1.UpdateTodoStatusResponse.todo:type_name -> workspace.v1.Todo
	1,  // 5: workspace.v1.TodoService.CreateTodo:input_type -> workspace.v1.CreateTodoRequest
	3,  // 6: workspace.v1.TodoService.GetTodo:input_type -> workspace.v1.GetTodoRequest
	5,  // 7: workspace.v1.TodoService.ListTodos:input_type -> workspace.v1.ListTodosRequest
	7,  // 8: workspace.v1.TodoService.UpdateTodo:input_type -> workspace.v1.UpdateTodoRequest
	9,  // 9: workspace.v1.TodoService.UpdateTodoStatus:input_type -> workspace.v1.UpdateTodoStatusRequest
	11, // 10: workspace.v1.TodoService.DeleteTodo:input_type -> workspace.v1.DeleteTodoRequest
	2,  // 11: workspace.v1.TodoService.CreateTodo:output_type -> workspace.v1.CreateTodoResponse
	4,  // 12: workspace.v1.TodoService.GetTodo:output_type -> workspace.v1.GetTodoResponse
	6,  // 13: workspace.v1.TodoService.ListTodos:output_type -> workspace.v1.ListTodosResponse
	8,  // 14: workspace.v1.TodoService.UpdateTodo:output_type -> workspace.v1.UpdateTodoResponse
	10, // 15: workspace.v1.TodoService.UpdateTodoStatus:output_type -> workspace.v1.UpdateTodoStatusResponse
	12, // 16: workspace.v1.TodoService.DeleteTodo:output_type -> workspace.v1.DeleteTodoResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_workspace_v1_todo_proto_init() }
func file_workspace_v1_todo_proto_init() {
	if File_workspace_v1_todo_proto != nil {
		return
	}
	file_workspace_v1_todo_proto_msgTypes[0].OneofWrappers = []any{}
	file_workspace_v1_todo_proto_msgTypes[1].OneofWrappers = []any{}
	file_workspace_v1_todo_proto_msgTypes[5].OneofWrappers = []any{}
	file_workspace_v1_todo_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_todo_proto_rawDesc), len(file_workspace_v1_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_todo_proto_goTypes,
		DependencyIndexes: file_workspace_v1_todo_proto_depIdxs,
		MessageInfos:      file_workspace_v1_todo_proto_msgTypes,
	}.Build()
	File_workspace_v1_todo_proto = out.File
	file_workspace_v1_todo_proto_goTypes = nil
	file_workspace_v1_todo_proto_depIdxs = nil
}
