// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/auth/contract"
	authv1 "github.com/hvritual/workspace/rpc/pb/auth/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type AgentServer struct {
	authv1.UnimplementedAgentServiceServer
	service contract.AgentService
}

func NewAgentServer(service contract.AgentService) *AgentServer {
	return &AgentServer{service: service}
}

func (s *AgentServer) RegisterAgent(ctx context.Context, request *authv1.RegisterAgentRequest) (*authv1.RegisterAgentResponse, error) {
	var input contract.RegisterAgentRequest
	if err := decodeAgentProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.RegisterAgent(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &authv1.RegisterAgentResponse{}
	if err := encodeAgentContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *AgentServer) GetAgent(ctx context.Context, request *authv1.GetAgentRequest) (*authv1.GetAgentResponse, error) {
	var input contract.GetAgentRequest
	if err := decodeAgentProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.GetAgent(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &authv1.GetAgentResponse{}
	if err := encodeAgentContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeAgentProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeAgentContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
