// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"github.com/multica-ai/multica/server/internal/modules/auth/contract"
)

type AgentClient struct{ service contract.AgentService }

func NewAgent(service contract.AgentService) *AgentClient { return &AgentClient{service: service} }

var _ contract.AgentService = (*AgentClient)(nil)
