// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"github.com/multica-ai/multica/server/internal/modules/auth/contract"
)

type MemberClient struct{ service contract.MemberService }

func NewMember(service contract.MemberService) *MemberClient { return &MemberClient{service: service} }

var _ contract.MemberService = (*MemberClient)(nil)
