// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	authv1 "github.com/multica-ai/multica/server/gen/go/auth/v1"
	"github.com/multica-ai/multica/server/internal/modules/auth/contract"
)

type AgentClient struct{ client authv1.AgentServiceClient }

func NewAgent(client authv1.AgentServiceClient) *AgentClient { return &AgentClient{client: client} }

var _ contract.AgentService = (*AgentClient)(nil)
