// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	authv1 "github.com/multica-ai/multica/server/gen/go/auth/v1"
	"github.com/multica-ai/multica/server/internal/modules/auth/contract"
)

type MemberClient struct{ client authv1.MemberServiceClient }

func NewMember(client authv1.MemberServiceClient) *MemberClient { return &MemberClient{client: client} }

var _ contract.MemberService = (*MemberClient)(nil)
