// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	authv1 "github.com/multica-ai/multica/server/gen/go/auth/v1"
	"github.com/multica-ai/multica/server/internal/modules/auth/contract"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type MemberClient struct{ client authv1.MemberServiceClient }

func NewMember(client authv1.MemberServiceClient) *MemberClient { return &MemberClient{client: client} }

func (c *MemberClient) ListMembers(ctx context.Context, request contract.Member_ListMembersRequest) (contract.Member_ListMembersResponse, error) {
	protoRequest := &authv1.ListMembersRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_ListMembersResponse{}, err
	}
	response, err := c.client.ListMembers(ctx, protoRequest)
	if err != nil {
		return contract.Member_ListMembersResponse{}, err
	}
	var result contract.Member_ListMembersResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_ListMembersResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) UpdateMemberRole(ctx context.Context, request contract.Member_UpdateMemberRoleRequest) (contract.Member_Member, error) {
	protoRequest := &authv1.UpdateMemberRoleRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_Member{}, err
	}
	response, err := c.client.UpdateMemberRole(ctx, protoRequest)
	if err != nil {
		return contract.Member_Member{}, err
	}
	var result contract.Member_Member
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_Member{}, err
	}
	return result, nil
}

func (c *MemberClient) DeleteMember(ctx context.Context, request contract.Member_DeleteMemberRequest) (contract.Member_DeleteMemberResponse, error) {
	protoRequest := &authv1.DeleteMemberRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_DeleteMemberResponse{}, err
	}
	response, err := c.client.DeleteMember(ctx, protoRequest)
	if err != nil {
		return contract.Member_DeleteMemberResponse{}, err
	}
	var result contract.Member_DeleteMemberResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_DeleteMemberResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) LeaveWorkspace(ctx context.Context, request contract.Member_LeaveWorkspaceRequest) (contract.Member_LeaveWorkspaceResponse, error) {
	protoRequest := &authv1.LeaveWorkspaceRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_LeaveWorkspaceResponse{}, err
	}
	response, err := c.client.LeaveWorkspace(ctx, protoRequest)
	if err != nil {
		return contract.Member_LeaveWorkspaceResponse{}, err
	}
	var result contract.Member_LeaveWorkspaceResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_LeaveWorkspaceResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) RevokeInvitation(ctx context.Context, request contract.Member_RevokeInvitationRequest) (contract.Member_RevokeInvitationResponse, error) {
	protoRequest := &authv1.RevokeInvitationRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_RevokeInvitationResponse{}, err
	}
	response, err := c.client.RevokeInvitation(ctx, protoRequest)
	if err != nil {
		return contract.Member_RevokeInvitationResponse{}, err
	}
	var result contract.Member_RevokeInvitationResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_RevokeInvitationResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) ListWorkspaceInvitations(ctx context.Context, request contract.Member_ListWorkspaceInvitationsRequest) (contract.Member_ListWorkspaceInvitationsResponse, error) {
	protoRequest := &authv1.ListWorkspaceInvitationsRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_ListWorkspaceInvitationsResponse{}, err
	}
	response, err := c.client.ListWorkspaceInvitations(ctx, protoRequest)
	if err != nil {
		return contract.Member_ListWorkspaceInvitationsResponse{}, err
	}
	var result contract.Member_ListWorkspaceInvitationsResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_ListWorkspaceInvitationsResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) CreateInvitation(ctx context.Context, request contract.Member_CreateInvitationRequest) (contract.Member_Invitation, error) {
	protoRequest := &authv1.CreateInvitationRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_Invitation{}, err
	}
	response, err := c.client.CreateInvitation(ctx, protoRequest)
	if err != nil {
		return contract.Member_Invitation{}, err
	}
	var result contract.Member_Invitation
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_Invitation{}, err
	}
	return result, nil
}

func (c *MemberClient) ListMyInvitations(ctx context.Context, request contract.Member_ListMyInvitationsRequest) (contract.Member_ListMyInvitationsResponse, error) {
	protoRequest := &authv1.ListMyInvitationsRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_ListMyInvitationsResponse{}, err
	}
	response, err := c.client.ListMyInvitations(ctx, protoRequest)
	if err != nil {
		return contract.Member_ListMyInvitationsResponse{}, err
	}
	var result contract.Member_ListMyInvitationsResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_ListMyInvitationsResponse{}, err
	}
	return result, nil
}

func (c *MemberClient) GetMyInvitation(ctx context.Context, request contract.Member_GetMyInvitationRequest) (contract.Member_GetMyInvitationResponse, error) {
	protoRequest := &authv1.GetMyInvitationRequest{}
	if err := encodeMemberContract(request, protoRequest); err != nil {
		return contract.Member_GetMyInvitationResponse{}, err
	}
	response, err := c.client.GetMyInvitation(ctx, protoRequest)
	if err != nil {
		return contract.Member_GetMyInvitationResponse{}, err
	}
	var result contract.Member_GetMyInvitationResponse
	if err := decodeMemberProto(response, &result); err != nil {
		return contract.Member_GetMyInvitationResponse{}, err
	}
	return result, nil
}

func decodeMemberProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeMemberContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.MemberService = (*MemberClient)(nil)
