// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type IssueClient struct{ service contract.IssueService }

func NewIssue(service contract.IssueService) *IssueClient { return &IssueClient{service: service} }

func (c *IssueClient) UpdateIssueStatus(ctx context.Context, request contract.Issue_UpdateIssueStatusRequest) (contract.Issue_Issue, error) {
	return c.service.UpdateIssueStatus(ctx, request)
}

var _ contract.IssueService = (*IssueClient)(nil)
