// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type ProjectClient struct{ service contract.ProjectService }

func NewProject(service contract.ProjectService) *ProjectClient {
	return &ProjectClient{service: service}
}

var _ contract.ProjectService = (*ProjectClient)(nil)
