// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type RelationshipClient struct{ service contract.RelationshipService }

func NewRelationship(service contract.RelationshipService) *RelationshipClient {
	return &RelationshipClient{service: service}
}

var _ contract.RelationshipService = (*RelationshipClient)(nil)
