// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type RequirementClient struct{ service contract.RequirementService }

func NewRequirement(service contract.RequirementService) *RequirementClient {
	return &RequirementClient{service: service}
}

var _ contract.RequirementService = (*RequirementClient)(nil)
