// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrIssueNotImplemented = errors.New("IssueService application method requires implementation")

type IssueService interface {
	CreateIssue(context.Context, CreateIssueRequest) (CreateIssueResponse, error)
	GetIssue(context.Context, GetIssueRequest) (GetIssueResponse, error)
	ListIssues(context.Context, ListIssuesRequest) (ListIssuesResponse, error)
	UpdateIssue(context.Context, UpdateIssueRequest) (UpdateIssueResponse, error)
	UpdateIssueStatus(context.Context, UpdateIssueStatusRequest) (UpdateIssueStatusResponse, error)
}
