// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrKnowledgeNotImplemented = errors.New("KnowledgeService application method requires implementation")

type KnowledgeService interface {
	CreateKnowledge(context.Context, CreateKnowledgeRequest) (CreateKnowledgeResponse, error)
	GetKnowledge(context.Context, GetKnowledgeRequest) (GetKnowledgeResponse, error)
}
