// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrProjectNotImplemented = errors.New("ProjectService application method requires implementation")

type ProjectService interface {
	CreateProject(context.Context, CreateProjectRequest) (CreateProjectResponse, error)
	GetProject(context.Context, GetProjectRequest) (GetProjectResponse, error)
	ListProjects(context.Context, ListProjectsRequest) (ListProjectsResponse, error)
	SearchProjects(context.Context, SearchProjectsRequest) (SearchProjectsResponse, error)
	UpdateProject(context.Context, UpdateProjectRequest) (UpdateProjectResponse, error)
	DeleteProject(context.Context, DeleteProjectRequest) (DeleteProjectResponse, error)
}
