// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrRequirementNotImplemented = errors.New("RequirementService application method requires implementation")

type RequirementService interface {
	SaveRequirementVersion(context.Context, SaveRequirementVersionRequest) (SaveRequirementVersionResponse, error)
	GetRequirement(context.Context, GetRequirementRequest) (GetRequirementResponse, error)
}
