// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrSettingNotImplemented = errors.New("SettingService application method requires implementation")

type SettingService interface {
	PutWorkspaceSetting(context.Context, PutWorkspaceSettingRequest) (PutWorkspaceSettingResponse, error)
	PutWorkspaceSkillBinding(context.Context, PutWorkspaceSkillBindingRequest) (PutWorkspaceSkillBindingResponse, error)
}
