// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrTodoNotImplemented = errors.New("TodoService application method requires implementation")

type TodoService interface {
	CreateTodo(context.Context, CreateTodoRequest) (CreateTodoResponse, error)
	GetTodo(context.Context, GetTodoRequest) (GetTodoResponse, error)
	ListTodos(context.Context, ListTodosRequest) (ListTodosResponse, error)
	UpdateTodo(context.Context, UpdateTodoRequest) (UpdateTodoResponse, error)
	UpdateTodoStatus(context.Context, UpdateTodoStatusRequest) (UpdateTodoStatusResponse, error)
	DeleteTodo(context.Context, DeleteTodoRequest) (DeleteTodoResponse, error)
	RestoreTodo(context.Context, RestoreTodoRequest) (RestoreTodoResponse, error)
	ReorderTodos(context.Context, ReorderTodosRequest) (ReorderTodosResponse, error)
}
