// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type IssueServer struct {
	workspacev1.UnimplementedIssueServiceServer
	service contract.IssueService
}

func NewIssueServer(service contract.IssueService) *IssueServer {
	return &IssueServer{service: service}
}

func (s *IssueServer) CreateIssue(ctx context.Context, request *workspacev1.CreateIssueRequest) (*workspacev1.CreateIssueResponse, error) {
	var input contract.CreateIssueRequest
	if err := decodeIssueProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.CreateIssue(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.CreateIssueResponse{}
	if err := encodeIssueContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *IssueServer) GetIssue(ctx context.Context, request *workspacev1.GetIssueRequest) (*workspacev1.GetIssueResponse, error) {
	var input contract.GetIssueRequest
	if err := decodeIssueProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.GetIssue(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.GetIssueResponse{}
	if err := encodeIssueContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *IssueServer) ListIssues(ctx context.Context, request *workspacev1.ListIssuesRequest) (*workspacev1.ListIssuesResponse, error) {
	var input contract.ListIssuesRequest
	if err := decodeIssueProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.ListIssues(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.ListIssuesResponse{}
	if err := encodeIssueContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *IssueServer) UpdateIssue(ctx context.Context, request *workspacev1.UpdateIssueRequest) (*workspacev1.UpdateIssueResponse, error) {
	var input contract.UpdateIssueRequest
	if err := decodeIssueProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.UpdateIssue(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.UpdateIssueResponse{}
	if err := encodeIssueContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *IssueServer) UpdateIssueStatus(ctx context.Context, request *workspacev1.UpdateIssueStatusRequest) (*workspacev1.UpdateIssueStatusResponse, error) {
	var input contract.UpdateIssueStatusRequest
	if err := decodeIssueProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.UpdateIssueStatus(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.UpdateIssueStatusResponse{}
	if err := encodeIssueContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeIssueProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeIssueContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
