// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type KnowledgeServer struct {
	workspacev1.UnimplementedKnowledgeServiceServer
	service contract.KnowledgeService
}

func NewKnowledgeServer(service contract.KnowledgeService) *KnowledgeServer {
	return &KnowledgeServer{service: service}
}

func (s *KnowledgeServer) CreateKnowledge(ctx context.Context, request *workspacev1.CreateKnowledgeRequest) (*workspacev1.CreateKnowledgeResponse, error) {
	var input contract.CreateKnowledgeRequest
	if err := decodeKnowledgeProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.CreateKnowledge(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.CreateKnowledgeResponse{}
	if err := encodeKnowledgeContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *KnowledgeServer) GetKnowledge(ctx context.Context, request *workspacev1.GetKnowledgeRequest) (*workspacev1.GetKnowledgeResponse, error) {
	var input contract.GetKnowledgeRequest
	if err := decodeKnowledgeProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.GetKnowledge(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.GetKnowledgeResponse{}
	if err := encodeKnowledgeContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeKnowledgeProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeKnowledgeContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
