// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type ProjectServer struct {
	workspacev1.UnimplementedProjectServiceServer
	service contract.ProjectService
}

func NewProjectServer(service contract.ProjectService) *ProjectServer {
	return &ProjectServer{service: service}
}

func (s *ProjectServer) CreateProject(ctx context.Context, request *workspacev1.CreateProjectRequest) (*workspacev1.CreateProjectResponse, error) {
	var input contract.CreateProjectRequest
	if err := decodeProjectProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.CreateProject(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.CreateProjectResponse{}
	if err := encodeProjectContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *ProjectServer) GetProject(ctx context.Context, request *workspacev1.GetProjectRequest) (*workspacev1.GetProjectResponse, error) {
	var input contract.GetProjectRequest
	if err := decodeProjectProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.GetProject(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.GetProjectResponse{}
	if err := encodeProjectContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *ProjectServer) ListProjects(ctx context.Context, request *workspacev1.ListProjectsRequest) (*workspacev1.ListProjectsResponse, error) {
	var input contract.ListProjectsRequest
	if err := decodeProjectProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.ListProjects(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.ListProjectsResponse{}
	if err := encodeProjectContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *ProjectServer) SearchProjects(ctx context.Context, request *workspacev1.SearchProjectsRequest) (*workspacev1.SearchProjectsResponse, error) {
	var input contract.SearchProjectsRequest
	if err := decodeProjectProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.SearchProjects(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.SearchProjectsResponse{}
	if err := encodeProjectContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *ProjectServer) UpdateProject(ctx context.Context, request *workspacev1.UpdateProjectRequest) (*workspacev1.UpdateProjectResponse, error) {
	var input contract.UpdateProjectRequest
	if err := decodeProjectProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.UpdateProject(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.UpdateProjectResponse{}
	if err := encodeProjectContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *ProjectServer) DeleteProject(ctx context.Context, request *workspacev1.DeleteProjectRequest) (*workspacev1.DeleteProjectResponse, error) {
	var input contract.DeleteProjectRequest
	if err := decodeProjectProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.DeleteProject(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.DeleteProjectResponse{}
	if err := encodeProjectContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeProjectProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeProjectContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
