// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type SettingServer struct {
	workspacev1.UnimplementedSettingServiceServer
	service contract.SettingService
}

func NewSettingServer(service contract.SettingService) *SettingServer {
	return &SettingServer{service: service}
}

func (s *SettingServer) PutWorkspaceSetting(ctx context.Context, request *workspacev1.PutWorkspaceSettingRequest) (*workspacev1.PutWorkspaceSettingResponse, error) {
	var input contract.PutWorkspaceSettingRequest
	if err := decodeSettingProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.PutWorkspaceSetting(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.PutWorkspaceSettingResponse{}
	if err := encodeSettingContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *SettingServer) PutWorkspaceSkillBinding(ctx context.Context, request *workspacev1.PutWorkspaceSkillBindingRequest) (*workspacev1.PutWorkspaceSkillBindingResponse, error) {
	var input contract.PutWorkspaceSkillBindingRequest
	if err := decodeSettingProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.PutWorkspaceSkillBinding(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.PutWorkspaceSkillBindingResponse{}
	if err := encodeSettingContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeSettingProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeSettingContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
