// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/workspace/contract"
	workspacev1 "github.com/hvritual/workspace/rpc/pb/workspace/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type TodoServer struct {
	workspacev1.UnimplementedTodoServiceServer
	service contract.TodoService
}

func NewTodoServer(service contract.TodoService) *TodoServer { return &TodoServer{service: service} }

func (s *TodoServer) CreateTodo(ctx context.Context, request *workspacev1.CreateTodoRequest) (*workspacev1.CreateTodoResponse, error) {
	var input contract.CreateTodoRequest
	if err := decodeTodoProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.CreateTodo(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.CreateTodoResponse{}
	if err := encodeTodoContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *TodoServer) GetTodo(ctx context.Context, request *workspacev1.GetTodoRequest) (*workspacev1.GetTodoResponse, error) {
	var input contract.GetTodoRequest
	if err := decodeTodoProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.GetTodo(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.GetTodoResponse{}
	if err := encodeTodoContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *TodoServer) ListTodos(ctx context.Context, request *workspacev1.ListTodosRequest) (*workspacev1.ListTodosResponse, error) {
	var input contract.ListTodosRequest
	if err := decodeTodoProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.ListTodos(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.ListTodosResponse{}
	if err := encodeTodoContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *TodoServer) UpdateTodo(ctx context.Context, request *workspacev1.UpdateTodoRequest) (*workspacev1.UpdateTodoResponse, error) {
	var input contract.UpdateTodoRequest
	if err := decodeTodoProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.UpdateTodo(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.UpdateTodoResponse{}
	if err := encodeTodoContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *TodoServer) UpdateTodoStatus(ctx context.Context, request *workspacev1.UpdateTodoStatusRequest) (*workspacev1.UpdateTodoStatusResponse, error) {
	var input contract.UpdateTodoStatusRequest
	if err := decodeTodoProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.UpdateTodoStatus(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.UpdateTodoStatusResponse{}
	if err := encodeTodoContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *TodoServer) DeleteTodo(ctx context.Context, request *workspacev1.DeleteTodoRequest) (*workspacev1.DeleteTodoResponse, error) {
	var input contract.DeleteTodoRequest
	if err := decodeTodoProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.DeleteTodo(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.DeleteTodoResponse{}
	if err := encodeTodoContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeTodoProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeTodoContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
