// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/member.proto

package authv1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionWorkspaceOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionWorkspaceOwnerRequest) Reset() {
	*x = ProvisionWorkspaceOwnerRequest{}
	mi := &file_auth_v1_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionWorkspaceOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionWorkspaceOwnerRequest) ProtoMessage() {}

func (x *ProvisionWorkspaceOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionWorkspaceOwnerRequest.ProtoReflect.Descriptor instead.
func (*ProvisionWorkspaceOwnerRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_member_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionWorkspaceOwnerRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ProvisionWorkspaceOwnerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ProvisionWorkspaceOwnerResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Member *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// False means the same completed Workspace/User command was replayed.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionWorkspaceOwnerResponse) Reset() {
	*x = ProvisionWorkspaceOwnerResponse{}
	mi := &file_auth_v1_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionWorkspaceOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionWorkspaceOwnerResponse) ProtoMessage() {}

func (x *ProvisionWorkspaceOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionWorkspaceOwnerResponse.ProtoReflect.Descriptor instead.
func (*ProvisionWorkspaceOwnerResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_member_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionWorkspaceOwnerResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *ProvisionWorkspaceOwnerResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type Member struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId      string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// role remains owner, admin, or member for existing JSON compatibility.
	Role          string  `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Name          string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Email         string  `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl     *string `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	CreatedAt     string  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_auth_v1_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_auth_v1_member_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *Member) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_auth_v1_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_member_proto_rawDescGZIP(), []int{3}
}

func (x *ListMembersRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_auth_v1_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_member_proto_rawDescGZIP(), []int{4}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_auth_v1_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_member_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMemberRoleRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleResponse) Reset() {
	*x = UpdateMemberRoleResponse{}
	mi := &file_auth_v1_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleResponse) ProtoMessage() {}

func (x *UpdateMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_member_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMemberRoleResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

var File_auth_v1_member_proto protoreflect.FileDescriptor

const file_auth_v1_member_proto_rawDesc = "" +
	"\n" +
	"\x14auth/v1/member.proto\x12\aauth.v1\x1a\x1bannotations/v1/access.proto\"\\\n" +
	"\x1eProvisionWorkspaceOwnerRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"d\n" +
	"\x1fProvisionWorkspaceOwnerResponse\x12'\n" +
	"\x06member\x18\x01 \x01(\v2\x0f.auth.v1.MemberR\x06member\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"\xe4\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\"\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAtB\r\n" +
	"\v_avatar_url\"7\n" +
	"\x12ListMembersRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"@\n" +
	"\x13ListMembersResponse\x12)\n" +
	"\amembers\x18\x01 \x03(\v2\x0f.auth.v1.MemberR\amembers\"m\n" +
	"\x17UpdateMemberRoleRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"C\n" +
	"\x18UpdateMemberRoleResponse\x12'\n" +
	"\x06member\x18\x01 \x01(\v2\x0f.auth.v1.MemberR\x06member2\xb5\x04\n" +
	"\rMemberService\x12\xe0\x01\n" +
	"\x17ProvisionWorkspaceOwner\x12'.auth.v1.ProvisionWorkspaceOwnerRequest\x1a(.auth.v1.ProvisionWorkspaceOwnerResponse\"r\xd2\xf3\x18n\n" +
	"%auth.member.provision_workspace_owner\x12\x19Provision workspace owner\x1a\vauth.member\"\x19provision_workspace_owner@\x01H\x01\x12\x81\x01\n" +
	"\vListMembers\x12\x1b.auth.v1.ListMembersRequest\x1a\x1c.auth.v1.ListMembersResponse\"7\xd2\xf3\x183\n" +
	"\x10auth.member.list\x12\fList members\x1a\vauth.member\"\x04list\x12\xa6\x01\n" +
	"\x10UpdateMemberRole\x12 .auth.v1.UpdateMemberRoleRequest\x1a!.auth.v1.UpdateMemberRoleResponse\"M\xd2\xf3\x18I\n" +
	"\x17auth.member.update_role\x12\x12Update member role\x1a\vauth.member\"\vupdate_role@\x01\x1a\x14\xca\xf3\x18\x10\n" +
	"\x04auth\x12\x04Auth\x1a\x02v1B5Z3github.com/hvritual/workspace/rpc/pb/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_member_proto_rawDescOnce sync.Once
	file_auth_v1_member_proto_rawDescData []byte
)

func file_auth_v1_member_proto_rawDescGZIP() []byte {
	file_auth_v1_member_proto_rawDescOnce.Do(func() {
		file_auth_v1_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_member_proto_rawDesc), len(file_auth_v1_member_proto_rawDesc)))
	})
	return file_auth_v1_member_proto_rawDescData
}

var file_auth_v1_member_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_v1_member_proto_goTypes = []any{
	(*ProvisionWorkspaceOwnerRequest)(nil),  // 0: auth.v1.ProvisionWorkspaceOwnerRequest
	(*ProvisionWorkspaceOwnerResponse)(nil), // 1: auth.v1.ProvisionWorkspaceOwnerResponse
	(*Member)(nil),                          // 2: auth.v1.Member
	(*ListMembersRequest)(nil),              // 3: auth.v1.ListMembersRequest
	(*ListMembersResponse)(nil),             // 4: auth.v1.ListMembersResponse
	(*UpdateMemberRoleRequest)(nil),         // 5: auth.v1.UpdateMemberRoleRequest
	(*UpdateMemberRoleResponse)(nil),        // 6: auth.v1.UpdateMemberRoleResponse
}
var file_auth_v1_member_proto_depIdxs = []int32{
	2, // 0: auth.v1.ProvisionWorkspaceOwnerResponse.member:type_name -> auth.v1.Member
	2, // 1: auth.v1.ListMembersResponse.members:type_name -> auth.v1.Member
	2, // 2: auth.v1.UpdateMemberRoleResponse.member:type_name -> auth.v1.Member
	0, // 3: auth.v1.MemberService.ProvisionWorkspaceOwner:input_type -> auth.v1.ProvisionWorkspaceOwnerRequest
	3, // 4: auth.v1.MemberService.ListMembers:input_type -> auth.v1.ListMembersRequest
	5, // 5: auth.v1.MemberService.UpdateMemberRole:input_type -> auth.v1.UpdateMemberRoleRequest
	1, // 6: auth.v1.MemberService.ProvisionWorkspaceOwner:output_type -> auth.v1.ProvisionWorkspaceOwnerResponse
	4, // 7: auth.v1.MemberService.ListMembers:output_type -> auth.v1.ListMembersResponse
	6, // 8: auth.v1.MemberService.UpdateMemberRole:output_type -> auth.v1.UpdateMemberRoleResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_v1_member_proto_init() }
func file_auth_v1_member_proto_init() {
	if File_auth_v1_member_proto != nil {
		return
	}
	file_auth_v1_member_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_member_proto_rawDesc), len(file_auth_v1_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_member_proto_goTypes,
		DependencyIndexes: file_auth_v1_member_proto_depIdxs,
		MessageInfos:      file_auth_v1_member_proto_msgTypes,
	}.Build()
	File_auth_v1_member_proto = out.File
	file_auth_v1_member_proto_goTypes = nil
	file_auth_v1_member_proto_depIdxs = nil
}
