// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: system/v1/agent_release.proto

package systemv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentReleaseService_PublishAgentRelease_FullMethodName = "/system.v1.AgentReleaseService/PublishAgentRelease"
	AgentReleaseService_ResolveAgentUpgrade_FullMethodName = "/system.v1.AgentReleaseService/ResolveAgentUpgrade"
)

// AgentReleaseServiceClient is the client API for AgentReleaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentReleaseService owns Agent release publication, immutable versions,
// compatible artifacts, and upgrade policy. auth.v1 owns Agent identity; asset
// content referenced by artifacts remains owned by space.v1.
type AgentReleaseServiceClient interface {
	PublishAgentRelease(ctx context.Context, in *PublishAgentReleaseRequest, opts ...grpc.CallOption) (*PublishAgentReleaseResponse, error)
	ResolveAgentUpgrade(ctx context.Context, in *ResolveAgentUpgradeRequest, opts ...grpc.CallOption) (*ResolveAgentUpgradeResponse, error)
}

type agentReleaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentReleaseServiceClient(cc grpc.ClientConnInterface) AgentReleaseServiceClient {
	return &agentReleaseServiceClient{cc}
}

func (c *agentReleaseServiceClient) PublishAgentRelease(ctx context.Context, in *PublishAgentReleaseRequest, opts ...grpc.CallOption) (*PublishAgentReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAgentReleaseResponse)
	err := c.cc.Invoke(ctx, AgentReleaseService_PublishAgentRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentReleaseServiceClient) ResolveAgentUpgrade(ctx context.Context, in *ResolveAgentUpgradeRequest, opts ...grpc.CallOption) (*ResolveAgentUpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAgentUpgradeResponse)
	err := c.cc.Invoke(ctx, AgentReleaseService_ResolveAgentUpgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentReleaseServiceServer is the server API for AgentReleaseService service.
// All implementations must embed UnimplementedAgentReleaseServiceServer
// for forward compatibility.
//
// AgentReleaseService owns Agent release publication, immutable versions,
// compatible artifacts, and upgrade policy. auth.v1 owns Agent identity; asset
// content referenced by artifacts remains owned by space.v1.
type AgentReleaseServiceServer interface {
	PublishAgentRelease(context.Context, *PublishAgentReleaseRequest) (*PublishAgentReleaseResponse, error)
	ResolveAgentUpgrade(context.Context, *ResolveAgentUpgradeRequest) (*ResolveAgentUpgradeResponse, error)
	mustEmbedUnimplementedAgentReleaseServiceServer()
}

// UnimplementedAgentReleaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentReleaseServiceServer struct{}

func (UnimplementedAgentReleaseServiceServer) PublishAgentRelease(context.Context, *PublishAgentReleaseRequest) (*PublishAgentReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishAgentRelease not implemented")
}
func (UnimplementedAgentReleaseServiceServer) ResolveAgentUpgrade(context.Context, *ResolveAgentUpgradeRequest) (*ResolveAgentUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveAgentUpgrade not implemented")
}
func (UnimplementedAgentReleaseServiceServer) mustEmbedUnimplementedAgentReleaseServiceServer() {}
func (UnimplementedAgentReleaseServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentReleaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentReleaseServiceServer will
// result in compilation errors.
type UnsafeAgentReleaseServiceServer interface {
	mustEmbedUnimplementedAgentReleaseServiceServer()
}

func RegisterAgentReleaseServiceServer(s grpc.ServiceRegistrar, srv AgentReleaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentReleaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentReleaseService_ServiceDesc, srv)
}

func _AgentReleaseService_PublishAgentRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishAgentReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentReleaseServiceServer).PublishAgentRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentReleaseService_PublishAgentRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentReleaseServiceServer).PublishAgentRelease(ctx, req.(*PublishAgentReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentReleaseService_ResolveAgentUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAgentUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentReleaseServiceServer).ResolveAgentUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentReleaseService_ResolveAgentUpgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentReleaseServiceServer).ResolveAgentUpgrade(ctx, req.(*ResolveAgentUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentReleaseService_ServiceDesc is the grpc.ServiceDesc for AgentReleaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentReleaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.v1.AgentReleaseService",
	HandlerType: (*AgentReleaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishAgentRelease",
			Handler:    _AgentReleaseService_PublishAgentRelease_Handler,
		},
		{
			MethodName: "ResolveAgentUpgrade",
			Handler:    _AgentReleaseService_ResolveAgentUpgrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system/v1/agent_release.proto",
}
