// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/v1/skill.proto

package systemv1

import (
	_ "github.com/hvritual/workspace/rpc/pb/annotations/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillDefinition) Reset() {
	*x = SkillDefinition{}
	mi := &file_system_v1_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillDefinition) ProtoMessage() {}

func (x *SkillDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillDefinition.ProtoReflect.Descriptor instead.
func (*SkillDefinition) Descriptor() ([]byte, []int) {
	return file_system_v1_skill_proto_rawDescGZIP(), []int{0}
}

func (x *SkillDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkillDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkillDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkillDefinition) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SkillVersion struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkillId string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Version string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Status  string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Each asset_id references content owned by space.v1.
	AssetIds      []string `protobuf:"bytes,5,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	PublishedAt   string   `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillVersion) Reset() {
	*x = SkillVersion{}
	mi := &file_system_v1_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillVersion) ProtoMessage() {}

func (x *SkillVersion) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillVersion.ProtoReflect.Descriptor instead.
func (*SkillVersion) Descriptor() ([]byte, []int) {
	return file_system_v1_skill_proto_rawDescGZIP(), []int{1}
}

func (x *SkillVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkillVersion) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SkillVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SkillVersion) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

func (x *SkillVersion) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type PublishSkillVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	AssetIds      []string               `protobuf:"bytes,3,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSkillVersionRequest) Reset() {
	*x = PublishSkillVersionRequest{}
	mi := &file_system_v1_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSkillVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSkillVersionRequest) ProtoMessage() {}

func (x *PublishSkillVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSkillVersionRequest.ProtoReflect.Descriptor instead.
func (*PublishSkillVersionRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_skill_proto_rawDescGZIP(), []int{2}
}

func (x *PublishSkillVersionRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *PublishSkillVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PublishSkillVersionRequest) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type PublishSkillVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *SkillDefinition       `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	Version       *SkillVersion          `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSkillVersionResponse) Reset() {
	*x = PublishSkillVersionResponse{}
	mi := &file_system_v1_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSkillVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSkillVersionResponse) ProtoMessage() {}

func (x *PublishSkillVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSkillVersionResponse.ProtoReflect.Descriptor instead.
func (*PublishSkillVersionResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_skill_proto_rawDescGZIP(), []int{3}
}

func (x *PublishSkillVersionResponse) GetSkill() *SkillDefinition {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *PublishSkillVersionResponse) GetVersion() *SkillVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Version       *string                `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_system_v1_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_skill_proto_rawDescGZIP(), []int{4}
}

func (x *GetSkillRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *GetSkillRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

type GetSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *SkillDefinition       `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	Version       *SkillVersion          `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillResponse) Reset() {
	*x = GetSkillResponse{}
	mi := &file_system_v1_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillResponse) ProtoMessage() {}

func (x *GetSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillResponse.ProtoReflect.Descriptor instead.
func (*GetSkillResponse) Descriptor() ([]byte, []int) {
	return file_system_v1_skill_proto_rawDescGZIP(), []int{5}
}

func (x *GetSkillResponse) GetSkill() *SkillDefinition {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *GetSkillResponse) GetVersion() *SkillVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_system_v1_skill_proto protoreflect.FileDescriptor

const file_system_v1_skill_proto_rawDesc = "" +
	"\n" +
	"\x15system/v1/skill.proto\x12\tsystem.v1\x1a\x1bannotations/v1/access.proto\"v\n" +
	"\x0fSkillDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\xab\x01\n" +
	"\fSkillVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tasset_ids\x18\x05 \x03(\tR\bassetIds\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\tR\vpublishedAt\"n\n" +
	"\x1aPublishSkillVersionRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tasset_ids\x18\x03 \x03(\tR\bassetIds\"\x82\x01\n" +
	"\x1bPublishSkillVersionResponse\x120\n" +
	"\x05skill\x18\x01 \x01(\v2\x1a.system.v1.SkillDefinitionR\x05skill\x121\n" +
	"\aversion\x18\x02 \x01(\v2\x17.system.v1.SkillVersionR\aversion\"W\n" +
	"\x0fGetSkillRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\tH\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"w\n" +
	"\x10GetSkillResponse\x120\n" +
	"\x05skill\x18\x01 \x01(\v2\x1a.system.v1.SkillDefinitionR\x05skill\x121\n" +
	"\aversion\x18\x02 \x01(\v2\x17.system.v1.SkillVersionR\aversion2\xe6\x02\n" +
	"\fSkillService\x12\xc0\x01\n" +
	"\x13PublishSkillVersion\x12%.system.v1.PublishSkillVersionRequest\x1a&.system.v1.PublishSkillVersionResponse\"Z\xd2\xf3\x18V\n" +
	"\x1csystem.skill.publish_version\x12\x15Publish skill version\x1a\fsystem.skill\"\x0fpublish_version@\x01\x12y\n" +
	"\bGetSkill\x12\x1a.system.v1.GetSkillRequest\x1a\x1b.system.v1.GetSkillResponse\"4\xd2\xf3\x180\n" +
	"\x10system.skill.get\x12\tGet skill\x1a\fsystem.skill\"\x03get\x1a\x18\xca\xf3\x18\x14\n" +
	"\x06system\x12\x06System\x1a\x02v1B9Z7github.com/hvritual/workspace/rpc/pb/system/v1;systemv1b\x06proto3"

var (
	file_system_v1_skill_proto_rawDescOnce sync.Once
	file_system_v1_skill_proto_rawDescData []byte
)

func file_system_v1_skill_proto_rawDescGZIP() []byte {
	file_system_v1_skill_proto_rawDescOnce.Do(func() {
		file_system_v1_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_skill_proto_rawDesc), len(file_system_v1_skill_proto_rawDesc)))
	})
	return file_system_v1_skill_proto_rawDescData
}

var file_system_v1_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_system_v1_skill_proto_goTypes = []any{
	(*SkillDefinition)(nil),             // 0: system.v1.SkillDefinition
	(*SkillVersion)(nil),                // 1: system.v1.SkillVersion
	(*PublishSkillVersionRequest)(nil),  // 2: system.v1.PublishSkillVersionRequest
	(*PublishSkillVersionResponse)(nil), // 3: system.v1.PublishSkillVersionResponse
	(*GetSkillRequest)(nil),             // 4: system.v1.GetSkillRequest
	(*GetSkillResponse)(nil),            // 5: system.v1.GetSkillResponse
}
var file_system_v1_skill_proto_depIdxs = []int32{
	0, // 0: system.v1.PublishSkillVersionResponse.skill:type_name -> system.v1.SkillDefinition
	1, // 1: system.v1.PublishSkillVersionResponse.version:type_name -> system.v1.SkillVersion
	0, // 2: system.v1.GetSkillResponse.skill:type_name -> system.v1.SkillDefinition
	1, // 3: system.v1.GetSkillResponse.version:type_name -> system.v1.SkillVersion
	2, // 4: system.v1.SkillService.PublishSkillVersion:input_type -> system.v1.PublishSkillVersionRequest
	4, // 5: system.v1.SkillService.GetSkill:input_type -> system.v1.GetSkillRequest
	3, // 6: system.v1.SkillService.PublishSkillVersion:output_type -> system.v1.PublishSkillVersionResponse
	5, // 7: system.v1.SkillService.GetSkill:output_type -> system.v1.GetSkillResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_system_v1_skill_proto_init() }
func file_system_v1_skill_proto_init() {
	if File_system_v1_skill_proto != nil {
		return
	}
	file_system_v1_skill_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_skill_proto_rawDesc), len(file_system_v1_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_skill_proto_goTypes,
		DependencyIndexes: file_system_v1_skill_proto_depIdxs,
		MessageInfos:      file_system_v1_skill_proto_msgTypes,
	}.Build()
	File_system_v1_skill_proto = out.File
	file_system_v1_skill_proto_goTypes = nil
	file_system_v1_skill_proto_depIdxs = nil
}
