// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: system/v1/system.proto

package systemv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSystemServicePing = "/system.v1.SystemService/Ping"

type SystemServiceHTTPServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterSystemServiceHTTPServer(s *http.Server, srv SystemServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/system/ping", _SystemService_Ping0_HTTP_Handler(srv))
}

func _SystemService_Ping0_HTTP_Handler(srv SystemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSystemServicePing)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*PingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingResponse)
		return ctx.Result(200, reply)
	}
}

type SystemServiceHTTPClient interface {
	Ping(ctx context.Context, req *PingRequest, opts ...http.CallOption) (rsp *PingResponse, err error)
}

type SystemServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSystemServiceHTTPClient(client *http.Client) SystemServiceHTTPClient {
	return &SystemServiceHTTPClientImpl{client}
}

func (c *SystemServiceHTTPClientImpl) Ping(ctx context.Context, in *PingRequest, opts ...http.CallOption) (*PingResponse, error) {
	var out PingResponse
	pattern := "/v1/system/ping"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSystemServicePing),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
