// Code generated by dddgen. DO NOT EDIT.
package space

import (
	kratoshttp "github.com/go-kratos/kratos/v3/transport/http"
	"github.com/hvritual/workspace/internal/modules/space/contract"
	"github.com/hvritual/workspace/internal/modules/space/internal/application"
	grpcadapter "github.com/hvritual/workspace/internal/modules/space/internal/interfaces/grpc"
	"github.com/hvritual/workspace/internal/modules/space/internal/interfaces/local"
	protoadapter "github.com/hvritual/workspace/internal/modules/space/internal/interfaces/proto"
	platformmodule "github.com/hvritual/workspace/internal/platform/module"
	spacev1 "github.com/hvritual/workspace/rpc/pb/space/v1"
	stdgrpc "google.golang.org/grpc"
)

type AssetExtension struct {
	local  contract.AssetService
	server *protoadapter.AssetServer
}

func NewAssetExtension() *AssetExtension {
	client := local.NewAsset(application.NewAssetService())
	return &AssetExtension{local: client, server: protoadapter.NewAssetServer(client)}
}

func init()                                               { RegisterExtension(func() platformmodule.Extension { return NewAssetExtension() }) }
func (e *AssetExtension) RegisterHTTP(*kratoshttp.Server) {}
func (e *AssetExtension) RegisterGRPC(registrar stdgrpc.ServiceRegistrar) {
	spacev1.RegisterAssetServiceServer(registrar, e.server)
}
func (e *AssetExtension) Local() contract.AssetService { return e.local }
func (m *Module) AssetLocal() contract.AssetService {
	for _, extension := range m.extensions {
		if typed, ok := extension.(*AssetExtension); ok {
			return typed.Local()
		}
	}
	panic("Asset extension is not registered")
}
func NewAssetGRPCClient(connection stdgrpc.ClientConnInterface) contract.AssetService {
	return grpcadapter.NewAsset(spacev1.NewAssetServiceClient(connection))
}
