// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrAssetNotImplemented = errors.New("AssetService application method requires implementation")

type AssetService interface {
	UploadAsset(context.Context, Asset_UploadAssetRequest) (Asset_UploadAssetResponse, error)
	GetAsset(context.Context, Asset_GetAssetRequest) (Asset_GetAssetResponse, error)
}

type Asset_Asset struct {
	Id               string `json:"id,omitempty"`
	WorkspaceId      string `json:"workspaceId,omitempty"`
	CurrentVersionId string `json:"currentVersionId,omitempty"`
	Filename         string `json:"filename,omitempty"`
	UploaderType     string `json:"uploaderType,omitempty"`
	UploaderId       string `json:"uploaderId,omitempty"`
	ObjectKey        string `json:"objectKey,omitempty"`
	Url              string `json:"url,omitempty"`
	MediaType        string `json:"mediaType,omitempty"`
	SizeBytes        string `json:"sizeBytes,omitempty"`
	Checksum         string `json:"checksum,omitempty"`
	CreatedAt        string `json:"createdAt,omitempty"`
}

type Asset_GetAssetRequest struct {
	AssetId string `json:"assetId,omitempty"`
}

type Asset_GetAssetResponse struct {
	Asset *Asset_Asset `json:"asset,omitempty"`
}

type Asset_UploadAssetRequest struct {
	WorkspaceId string `json:"workspaceId,omitempty"`
	Filename    string `json:"filename,omitempty"`
	MediaType   string `json:"mediaType,omitempty"`
	Content     []byte `json:"content,omitempty"`
}

type Asset_UploadAssetResponse struct {
	Asset          *Asset_Asset `json:"asset,omitempty"`
	DirectObjectId string       `json:"directObjectId,omitempty"`
	DirectUrl      string       `json:"directUrl,omitempty"`
	Filename       string       `json:"filename,omitempty"`
}
