// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrAssetNotImplemented = errors.New("AssetService application method requires implementation")

type AssetService interface {
}
