// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrAssetNotImplemented = errors.New("AssetService application method requires implementation")

type AssetService interface {
	UploadAsset(context.Context, UploadAssetRequest) (UploadAssetResponse, error)
	CreateAssetVersion(context.Context, CreateAssetVersionRequest) (CreateAssetVersionResponse, error)
	GetAsset(context.Context, GetAssetRequest) (GetAssetResponse, error)
}
