// Code generated by dddgen. DO NOT EDIT.
package contract

type Asset struct {
	Id               string         `json:"id,omitempty"`
	WorkspaceId      string         `json:"workspaceId,omitempty"`
	CurrentVersionId string         `json:"currentVersionId,omitempty"`
	Filename         string         `json:"filename,omitempty"`
	MediaType        string         `json:"mediaType,omitempty"`
	SizeBytes        string         `json:"sizeBytes,omitempty"`
	Checksum         string         `json:"checksum,omitempty"`
	Metadata         map[string]any `json:"metadata,omitempty"`
	AccessStatus     string         `json:"accessStatus,omitempty"`
	CreatedAt        string         `json:"createdAt,omitempty"`
	UpdatedAt        string         `json:"updatedAt,omitempty"`
}

type AssetVersion struct {
	Id        string         `json:"id,omitempty"`
	AssetId   string         `json:"assetId,omitempty"`
	MediaType string         `json:"mediaType,omitempty"`
	SizeBytes string         `json:"sizeBytes,omitempty"`
	Checksum  string         `json:"checksum,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
	CreatedAt string         `json:"createdAt,omitempty"`
}

type CreateAssetVersionRequest struct {
	WorkspaceId string         `json:"workspaceId,omitempty"`
	AssetId     string         `json:"assetId,omitempty"`
	MediaType   string         `json:"mediaType,omitempty"`
	Content     []byte         `json:"content,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

type CreateAssetVersionResponse struct {
	AssetId string        `json:"assetId,omitempty"`
	Asset   *Asset        `json:"asset,omitempty"`
	Version *AssetVersion `json:"version,omitempty"`
}

type GetAssetRequest struct {
	WorkspaceId string `json:"workspaceId,omitempty"`
	AssetId     string `json:"assetId,omitempty"`
}

type GetAssetResponse struct {
	Asset          *Asset        `json:"asset,omitempty"`
	CurrentVersion *AssetVersion `json:"currentVersion,omitempty"`
}

type Struct = map[string]any

type UploadAssetRequest struct {
	WorkspaceId string         `json:"workspaceId,omitempty"`
	Filename    string         `json:"filename,omitempty"`
	MediaType   string         `json:"mediaType,omitempty"`
	Content     []byte         `json:"content,omitempty"`
	Metadata    map[string]any `json:"metadata,omitempty"`
}

type UploadAssetResponse struct {
	AssetId string        `json:"assetId,omitempty"`
	Asset   *Asset        `json:"asset,omitempty"`
	Version *AssetVersion `json:"version,omitempty"`
}
