// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"github.com/multica-ai/multica/server/internal/modules/space/contract"
)

type AssetClient struct{ service contract.AssetService }

func NewAsset(service contract.AssetService) *AssetClient { return &AssetClient{service: service} }

var _ contract.AssetService = (*AssetClient)(nil)
