// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrAgentNotImplemented = errors.New("AgentService application method requires implementation")

type AgentService interface {
}
