// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrMemberNotImplemented = errors.New("MemberService application method requires implementation")

type MemberService interface {
	UpdateMemberRole(context.Context, Member_UpdateMemberRoleRequest) (Member_Member, error)
}

type Member_Member struct {
	Id          string  `json:"id,omitempty"`
	WorkspaceId string  `json:"workspaceId,omitempty"`
	UserId      string  `json:"userId,omitempty"`
	Role        string  `json:"role,omitempty"`
	CreatedAt   string  `json:"createdAt,omitempty"`
	Name        string  `json:"name,omitempty"`
	Email       string  `json:"email,omitempty"`
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
}

type Member_StringValue = string

type Member_UpdateMemberRoleRequest struct {
	WorkspaceId string `json:"workspaceId,omitempty"`
	MemberId    string `json:"memberId,omitempty"`
	Role        string `json:"role,omitempty"`
}
