// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrMemberNotImplemented = errors.New("MemberService application method requires implementation")

type MemberService interface {
}
