// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type IssueServer struct {
	workspacev1.UnimplementedIssueServiceServer
	service contract.IssueService
}

func NewIssueServer(service contract.IssueService) *IssueServer {
	return &IssueServer{service: service}
}

func (s *IssueServer) UpdateIssueStatus(ctx context.Context, request *workspacev1.UpdateIssueStatusRequest) (*workspacev1.Issue, error) {
	var input contract.Issue_UpdateIssueStatusRequest
	if err := decodeIssueProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.UpdateIssueStatus(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &workspacev1.Issue{}
	if err := encodeIssueContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeIssueProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeIssueContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
