// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type ProjectServer struct {
	workspacev1.UnimplementedProjectServiceServer
	service contract.ProjectService
}

func NewProjectServer(service contract.ProjectService) *ProjectServer {
	return &ProjectServer{service: service}
}
