// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type RelationshipServer struct {
	workspacev1.UnimplementedRelationshipServiceServer
	service contract.RelationshipService
}

func NewRelationshipServer(service contract.RelationshipService) *RelationshipServer {
	return &RelationshipServer{service: service}
}
