// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	workspacev1 "github.com/multica-ai/multica/server/gen/go/workspace/v1"
	"github.com/multica-ai/multica/server/internal/modules/workspace/contract"
)

type SettingServer struct {
	workspacev1.UnimplementedSettingServiceServer
	service contract.SettingService
}

func NewSettingServer(service contract.SettingService) *SettingServer {
	return &SettingServer{service: service}
}
