// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/system/contract"
)

type AgentReleaseClient struct{ service contract.AgentReleaseService }

func NewAgentRelease(service contract.AgentReleaseService) *AgentReleaseClient {
	return &AgentReleaseClient{service: service}
}

func (c *AgentReleaseClient) PublishAgentRelease(ctx context.Context, request contract.PublishAgentReleaseRequest) (contract.PublishAgentReleaseResponse, error) {
	return c.service.PublishAgentRelease(ctx, request)
}

func (c *AgentReleaseClient) ResolveAgentUpgrade(ctx context.Context, request contract.ResolveAgentUpgradeRequest) (contract.ResolveAgentUpgradeResponse, error) {
	return c.service.ResolveAgentUpgrade(ctx, request)
}

var _ contract.AgentReleaseService = (*AgentReleaseClient)(nil)
