// Code generated by dddgen. DO NOT EDIT.
package local

import (
	"context"

	"github.com/hvritual/workspace/internal/modules/system/contract"
)

type SkillClient struct{ service contract.SkillService }

func NewSkill(service contract.SkillService) *SkillClient { return &SkillClient{service: service} }

func (c *SkillClient) PublishSkillVersion(ctx context.Context, request contract.PublishSkillVersionRequest) (contract.PublishSkillVersionResponse, error) {
	return c.service.PublishSkillVersion(ctx, request)
}

func (c *SkillClient) GetSkill(ctx context.Context, request contract.GetSkillRequest) (contract.GetSkillResponse, error) {
	return c.service.GetSkill(ctx, request)
}

var _ contract.SkillService = (*SkillClient)(nil)
