// Code generated by dddgen. DO NOT EDIT.
package system

import (
	kratoshttp "github.com/go-kratos/kratos/v3/transport/http"
	"github.com/hvritual/workspace/internal/modules/system/contract"
	"github.com/hvritual/workspace/internal/modules/system/internal/application"
	grpcadapter "github.com/hvritual/workspace/internal/modules/system/internal/interfaces/grpc"
	"github.com/hvritual/workspace/internal/modules/system/internal/interfaces/local"
	protoadapter "github.com/hvritual/workspace/internal/modules/system/internal/interfaces/proto"
	platformmodule "github.com/hvritual/workspace/internal/platform/module"
	systemv1 "github.com/hvritual/workspace/rpc/pb/system/v1"
	stdgrpc "google.golang.org/grpc"
)

type SkillExtension struct {
	local  contract.SkillService
	server *protoadapter.SkillServer
}

func NewSkillExtension() *SkillExtension {
	client := local.NewSkill(application.NewSkillService())
	return &SkillExtension{local: client, server: protoadapter.NewSkillServer(client)}
}

func init()                                               { RegisterExtension(func() platformmodule.Extension { return NewSkillExtension() }) }
func (e *SkillExtension) RegisterHTTP(*kratoshttp.Server) {}
func (e *SkillExtension) RegisterGRPC(registrar stdgrpc.ServiceRegistrar) {
	systemv1.RegisterSkillServiceServer(registrar, e.server)
}
func (e *SkillExtension) Local() contract.SkillService { return e.local }
func (m *Module) SkillLocal() contract.SkillService {
	for _, extension := range m.extensions {
		if typed, ok := extension.(*SkillExtension); ok {
			return typed.Local()
		}
	}
	panic("Skill extension is not registered")
}
func NewSkillGRPCClient(connection stdgrpc.ClientConnInterface) contract.SkillService {
	return grpcadapter.NewSkill(systemv1.NewSkillServiceClient(connection))
}
