// Code generated by dddgen. DO NOT EDIT.
package contract

import "errors"

var ErrSkillNotImplemented = errors.New("SkillService application method requires implementation")

type SkillService interface {
}
