// Code generated by dddgen. DO NOT EDIT.
package proto

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/space/contract"
	spacev1 "github.com/hvritual/workspace/rpc/pb/space/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type AssetServer struct {
	spacev1.UnimplementedAssetServiceServer
	service contract.AssetService
}

func NewAssetServer(service contract.AssetService) *AssetServer {
	return &AssetServer{service: service}
}

func (s *AssetServer) UploadAsset(ctx context.Context, request *spacev1.UploadAssetRequest) (*spacev1.UploadAssetResponse, error) {
	var input contract.UploadAssetRequest
	if err := decodeAssetProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.UploadAsset(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &spacev1.UploadAssetResponse{}
	if err := encodeAssetContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *AssetServer) CreateAssetVersion(ctx context.Context, request *spacev1.CreateAssetVersionRequest) (*spacev1.CreateAssetVersionResponse, error) {
	var input contract.CreateAssetVersionRequest
	if err := decodeAssetProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.CreateAssetVersion(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &spacev1.CreateAssetVersionResponse{}
	if err := encodeAssetContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func (s *AssetServer) GetAsset(ctx context.Context, request *spacev1.GetAssetRequest) (*spacev1.GetAssetResponse, error) {
	var input contract.GetAssetRequest
	if err := decodeAssetProto(request, &input); err != nil {
		return nil, err
	}
	result, err := s.service.GetAsset(ctx, input)
	if err != nil {
		return nil, err
	}
	response := &spacev1.GetAssetResponse{}
	if err := encodeAssetContract(result, response); err != nil {
		return nil, err
	}
	return response, nil
}

func decodeAssetProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeAssetContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}
