// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrAgentNotImplemented = errors.New("AgentService application method requires implementation")

type AgentService interface {
	RegisterAgent(context.Context, RegisterAgentRequest) (RegisterAgentResponse, error)
	GetAgent(context.Context, GetAgentRequest) (GetAgentResponse, error)
}
