// Code generated by dddgen. DO NOT EDIT.
package contract

import (
	"context"
	"errors"
)

var ErrMemberNotImplemented = errors.New("MemberService application method requires implementation")

type MemberService interface {
	ProvisionWorkspaceOwner(context.Context, ProvisionWorkspaceOwnerRequest) (ProvisionWorkspaceOwnerResponse, error)
	ListMembers(context.Context, ListMembersRequest) (ListMembersResponse, error)
	UpdateMemberRole(context.Context, UpdateMemberRoleRequest) (UpdateMemberRoleResponse, error)
}
