// Code generated by dddgen. DO NOT EDIT.
package contract

type Agent struct {
	Id               string         `json:"id,omitempty"`
	WorkspaceId      string         `json:"workspaceId,omitempty"`
	Name             string         `json:"name,omitempty"`
	Status           string         `json:"status,omitempty"`
	IdentityMetadata map[string]any `json:"identityMetadata,omitempty"`
	CreatedAt        string         `json:"createdAt,omitempty"`
	UpdatedAt        string         `json:"updatedAt,omitempty"`
}

type GetAgentRequest struct {
	WorkspaceId string `json:"workspaceId,omitempty"`
	AgentId     string `json:"agentId,omitempty"`
}

type GetAgentResponse struct {
	Agent *Agent `json:"agent,omitempty"`
}

type ListMembersRequest struct {
	WorkspaceId string `json:"workspaceId,omitempty"`
}

type ListMembersResponse struct {
	Members []Member `json:"members,omitempty"`
}

type Member struct {
	Id          string  `json:"id,omitempty"`
	WorkspaceId string  `json:"workspaceId,omitempty"`
	UserId      string  `json:"userId,omitempty"`
	Role        string  `json:"role,omitempty"`
	Name        string  `json:"name,omitempty"`
	Email       string  `json:"email,omitempty"`
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	CreatedAt   string  `json:"createdAt,omitempty"`
}

type ProvisionWorkspaceOwnerRequest struct {
	WorkspaceId string `json:"workspaceId,omitempty"`
	UserId      string `json:"userId,omitempty"`
}

type ProvisionWorkspaceOwnerResponse struct {
	Member  *Member `json:"member,omitempty"`
	Created bool    `json:"created,omitempty"`
}

type RegisterAgentRequest struct {
	WorkspaceId      string         `json:"workspaceId,omitempty"`
	Name             string         `json:"name,omitempty"`
	IdentityMetadata map[string]any `json:"identityMetadata,omitempty"`
}

type RegisterAgentResponse struct {
	Agent *Agent `json:"agent,omitempty"`
}

type Struct = map[string]any

type UpdateMemberRoleRequest struct {
	WorkspaceId string `json:"workspaceId,omitempty"`
	MemberId    string `json:"memberId,omitempty"`
	Role        string `json:"role,omitempty"`
}

type UpdateMemberRoleResponse struct {
	Member *Member `json:"member,omitempty"`
}
