// Code generated by dddgen. DO NOT EDIT.
package system

import (
	kratoshttp "github.com/go-kratos/kratos/v3/transport/http"
	systemv1 "github.com/multica-ai/multica/server/gen/go/system/v1"
	"github.com/multica-ai/multica/server/internal/modules/system/contract"
	"github.com/multica-ai/multica/server/internal/modules/system/internal/application"
	grpcadapter "github.com/multica-ai/multica/server/internal/modules/system/internal/interfaces/grpc"
	"github.com/multica-ai/multica/server/internal/modules/system/internal/interfaces/local"
	protoadapter "github.com/multica-ai/multica/server/internal/modules/system/internal/interfaces/proto"
	platformmodule "github.com/multica-ai/multica/server/internal/platform/module"
	stdgrpc "google.golang.org/grpc"
)

type AgentReleaseExtension struct {
	local  contract.AgentReleaseService
	server *protoadapter.AgentReleaseServer
}

func NewAgentReleaseExtension() *AgentReleaseExtension {
	client := local.NewAgentRelease(application.NewAgentReleaseService())
	return &AgentReleaseExtension{local: client, server: protoadapter.NewAgentReleaseServer(client)}
}

func init()                                                      { RegisterExtension(func() platformmodule.Extension { return NewAgentReleaseExtension() }) }
func (e *AgentReleaseExtension) RegisterHTTP(*kratoshttp.Server) {}
func (e *AgentReleaseExtension) RegisterGRPC(registrar stdgrpc.ServiceRegistrar) {
	systemv1.RegisterAgentReleaseServiceServer(registrar, e.server)
}
func (e *AgentReleaseExtension) Local() contract.AgentReleaseService { return e.local }
func (m *Module) AgentReleaseLocal() contract.AgentReleaseService {
	for _, extension := range m.extensions {
		if typed, ok := extension.(*AgentReleaseExtension); ok {
			return typed.Local()
		}
	}
	panic("AgentRelease extension is not registered")
}
func NewAgentReleaseGRPCClient(connection stdgrpc.ClientConnInterface) contract.AgentReleaseService {
	return grpcadapter.NewAgentRelease(systemv1.NewAgentReleaseServiceClient(connection))
}
