// Code generated by dddgen. DO NOT EDIT.
package grpc

import (
	"context"
	"encoding/json"

	"github.com/hvritual/workspace/internal/modules/system/contract"
	systemv1 "github.com/hvritual/workspace/rpc/pb/system/v1"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type SkillClient struct{ client systemv1.SkillServiceClient }

func NewSkill(client systemv1.SkillServiceClient) *SkillClient { return &SkillClient{client: client} }

func (c *SkillClient) PublishSkillVersion(ctx context.Context, request contract.PublishSkillVersionRequest) (contract.PublishSkillVersionResponse, error) {
	protoRequest := &systemv1.PublishSkillVersionRequest{}
	if err := encodeSkillContract(request, protoRequest); err != nil {
		return contract.PublishSkillVersionResponse{}, err
	}
	response, err := c.client.PublishSkillVersion(ctx, protoRequest)
	if err != nil {
		return contract.PublishSkillVersionResponse{}, err
	}
	var result contract.PublishSkillVersionResponse
	if err := decodeSkillProto(response, &result); err != nil {
		return contract.PublishSkillVersionResponse{}, err
	}
	return result, nil
}

func (c *SkillClient) GetSkill(ctx context.Context, request contract.GetSkillRequest) (contract.GetSkillResponse, error) {
	protoRequest := &systemv1.GetSkillRequest{}
	if err := encodeSkillContract(request, protoRequest); err != nil {
		return contract.GetSkillResponse{}, err
	}
	response, err := c.client.GetSkill(ctx, protoRequest)
	if err != nil {
		return contract.GetSkillResponse{}, err
	}
	var result contract.GetSkillResponse
	if err := decodeSkillProto(response, &result); err != nil {
		return contract.GetSkillResponse{}, err
	}
	return result, nil
}

func decodeSkillProto(input proto.Message, output any) error {
	data, err := protojson.Marshal(input)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, output)
}

func encodeSkillContract(input any, output proto.Message) error {
	data, err := json.Marshal(input)
	if err != nil {
		return err
	}
	return protojson.Unmarshal(data, output)
}

var _ contract.SkillService = (*SkillClient)(nil)
