// Code generated by dddgen. DO NOT EDIT.
package contract_test

import (
	"context"
	"net"
	"reflect"
	"testing"

	"github.com/hvritual/workspace/internal/modules/system"
	"github.com/hvritual/workspace/internal/modules/system/contract"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/test/bufconn"
)

func TestSystemSkillAdaptersShareContract(t *testing.T) {
	extension := system.NewSkillExtension()
	request := contract.PublishSkillVersionRequest{}
	localResult, localErr := extension.Local().PublishSkillVersion(context.Background(), request)

	listener := bufconn.Listen(1024 * 1024)
	grpcServer := grpc.NewServer()
	extension.RegisterGRPC(grpcServer)
	go func() { _ = grpcServer.Serve(listener) }()
	defer grpcServer.Stop()
	connection, err := grpc.NewClient("passthrough:///bufnet",
		grpc.WithContextDialer(func(context.Context, string) (net.Conn, error) { return listener.Dial() }),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = connection.Close() }()
	grpcResult, grpcErr := system.NewSkillGRPCClient(connection).PublishSkillVersion(context.Background(), request)
	if !reflect.DeepEqual(grpcResult, localResult) || (grpcErr == nil) != (localErr == nil) {
		t.Fatalf("gRPC result=%+v err=%v; local result=%+v err=%v", grpcResult, grpcErr, localResult, localErr)
	}
}
